// Fictional records for the local preview only. Never imported by the production entry.
export function academy(roles){
 const today=new Date().toISOString().slice(0,10),month=today.slice(0,7)
 roles.Admin.full_name='Teen Academy';roles.Teacher.full_name='Nimal Perera';roles.Student.full_name='Amaya Fernando'
 const subjects=['Business foundations','Accounting principles','Economics','Marketing','Business communication','Human resources','Entrepreneurship','Business law','Digital commerce','Project management','Business analytics','Capstone project']
 const names=['Nimal Perera','Dilini Fernando','Kasun Jayasinghe','Nethmi Silva','Arun Sivalingam','Shalini Rodrigo','Malith Senanayake','Fathima Azeez','Dinesh Wijesinghe','Kavindi Samarasinghe','Ravi Kumar','Sachini De Alwis','Hasini Bandara','Imran Nazeer']
 const teachers=names.map((full_name,i)=>({name:i===0?roles.Teacher.name:`TC-TA-${String(i+1).padStart(4,'0')}`,user:i===0?roles.Teacher.user:`teacher${i+1}@example.invalid`,full_name,role:'Teacher',active:1,profile_image:`/demo/teacher-${i+1}.svg`}))
 const students=Array.from({length:320},(_,i)=>({name:i===0?roles.Student.name:`ST-TA-${String(i+1).padStart(5,'0')}`,user:i===0?roles.Student.user:`student${i+1}@example.invalid`,full_name:i===0?roles.Student.full_name:`${['Amaya','Kavindu','Nethuli','Aarav','Fathima','Sahan','Anjali','Rizwan'][i%8]} ${['Perera','Silva','Fernando','Kumar','Jayasinghe'][Math.floor(i/8)%5]} ${Math.floor(i/40)+1}`,role:'Student',active:1}))
 const institute={name:'preview-workspace',title:'Teen Academy',code:'TA0000500',language:'en',accent:'#9874ba',logo:'/demo/academy.svg'}
 const profile={name:'teen-academy',user:roles.Admin.user,display_name:'Teen Academy',username:'teenacademysl',kind:'Institute',country:'Sri Lanka',workspace:institute.name,status:'Verified',code:institute.code,tagline:'Big ideas. A brighter tomorrow.',bio:'A fictional academy bringing business programmes and Edexcel subject classes together. Explore the full learning journey in this local preview.',curriculum:'Business diploma · Edexcel International GCSE',languages:'English, Sinhala',grades:'O/L · Professional programmes',profile_image:'/demo/academy.svg',cover_image:'/demo/academy-banner.svg',socials:{}}
 const profiles=[profile,...teachers.map((t,i)=>({name:`teacher-profile-${i+1}`,user:t.user,display_name:t.full_name,username:t.full_name.toLowerCase().replaceAll(' ',''),kind:'Teacher',country:'Sri Lanka',status:'Verified',code:`TC${String(i+1).padStart(7,'0')}`,tagline:i===0?'Make complicated ideas feel simple.':'A little curiosity goes a long way.',qualifications:i%2?'BSc · PGDE':'BCom · MBA',bio:'Fictional teacher profile for the SISU preview. Teaching with practical examples, clear explanations and space for every question.',curriculum:subjects[i%12],grades:i===0?'Grades 6–11 · Business programme':'O/L · Diploma',languages:'English, Sinhala',profile_image:t.profile_image,cover_image:`/demo/banner-${i%4}.svg`,socials:{}})),{name:'student-profile',user:roles.Student.user,kind:'Student',display_name:roles.Student.full_name,username:'amayaf',country:'Sri Lanka',status:'Verified',socials:{},bio:'One small step every day.',profile_image:'/demo/teacher-4.svg'}]
 const links=teachers.map((t,i)=>({name:`membership-${i+1}`,profile:profile.name,user:t.user,kind:'Teacher membership',status:i<12?'Active':'Pending',creation:today}))
 for(let i=0;i<140;i++)links.push({name:`follow-${i}`,profile:profile.name,user:students[i].user,kind:'Follow',status:'Active'})
 const room=(name,title,teacher,index,extra={})=>({name,title,subject:title,teacher:teacher.name,teacher_name:teacher.full_name,institute:institute.name,owner_type:'Institute',owner_user:roles.Admin.user,public_provider:profile.name,teacher_access:'Teaching only',teacher_assignment_active:1,billing_type:'Monthly',fee:8000,fee_mode:'Paid',font:'sans',active:1,published:1,description:'Live teaching, lesson resources and a supportive learning community.',profile_image:teacher.profile_image,cover_image:`/demo/banner-${index%4}.svg`,schedule_label:'Sundays · 5:00–7:00 PM · Asia/Colombo',teaching_medium:'English',grade:'Edexcel O/L',comments_enabled:1,...extra})
 const rooms=subjects.map((subject,i)=>room(`module-${i+1}`,subject,teachers[i],i,{billing_type:'Programme module',programme:'teen-master-business',fee:0,grade:'Professional programme',schedule_label:`Module ${i+1} · weeks ${i*2+1}–${i*2+2}`}))
 rooms.push(room('edexcel-business','Edexcel O/L · Business',teachers[0],0),room('edexcel-accounting','Edexcel O/L · Accounting',teachers[1],1),room('edexcel-economics','Edexcel O/L · Economics',teachers[2],2),room('independent-maths','නිමල් සර්ගේ ගණන් පන්තිය',teachers[0],3,{owner_type:'Teacher',owner_user:teachers[0].user,public_provider:'teacher-profile-1',teacher_access:'Full control',font:'handwritten',subject:'Mathematics',grade:'Grade 10',teaching_medium:'Sinhala',schedule_label:'Saturdays · 9:00–11:00 AM · Asia/Colombo'}))
 const programmes=[{name:'teen-master-business',title:'Teen Master Business',institute:institute.name,provider:profile.name,description:'From your first business idea to a confident final project. Twelve specialist teachers guide one complete programme.',cover_image:'/demo/academy-banner.svg',duration_months:6,fee:135000,currency:'LKR',active:1,students:80,modules:subjects.map((title,i)=>({classroom:`module-${i+1}`,title,teacher:teachers[i].name,teacher_name:teachers[i].full_name,duration_weeks:2}))}]
 const enrollments=[],invoices=[]
 for(let i=0;i<80;i++){for(let m=0;m<12;m++)enrollments.push({name:`enroll-program-${i}-${m}`,student:students[i].name,classroom:`module-${m+1}`,active:1,access_override:'Automatic',programme_enrollment:`programme-enroll-${i}`});invoices.push({name:`INV-P-${i+1}`,student:students[i].name,classroom:'module-1',enrollment:`enroll-program-${i}-0`,programme:'teen-master-business',amount:135000,currency:'LKR',status:i%5?'Paid':'Unpaid',due_date:today,beneficiary:'Institute',recipient:'Teen Academy',platform_minor:0,beneficiary_minor:13500000})}
 for(let i=80;i<320;i++){const r=rooms[12+(i%3)],name=`enroll-month-${i}`;enrollments.push({name,student:students[i].name,classroom:r.name,active:1,access_override:'Automatic'});invoices.push({name:`INV-M-${i}`,student:students[i].name,classroom:r.name,enrollment:name,amount:8000,currency:'LKR',status:i%4?'Paid':'Unpaid',due_date:today,billing_month:month,beneficiary:'Institute',recipient:'Teen Academy',platform_minor:0,beneficiary_minor:800000})}
 for(const r of [rooms[12],rooms[15]]){const name='amaya-'+r.name;enrollments.push({name,student:roles.Student.name,classroom:r.name,active:1,access_override:'Automatic'});invoices.push({name:'INV-'+name,student:roles.Student.name,enrollment:name,classroom:r.name,amount:8000,currency:'LKR',status:'Paid',due_date:today,billing_month:month,beneficiary:r.owner_type,recipient:r.owner_type==='Institute'?'Teen Academy':teachers[0].full_name,platform_minor:0,beneficiary_minor:800000})}
 const sessions=rooms.map((r,i)=>({name:`session-${i}`,classroom:r.name,title:`${r.subject} · Welcome lesson`,starts_at:`${today}T${i%2?'18':'16'}:00`,ends_at:`${today}T${i%2?'20':'18'}:00`,mode:'Online',status:'Scheduled',comments:'Inherit',meeting_provider:['YouTube','Zoom','Google Meet'][i%3],youtube_id:i%3===0?'YSul9yrAvN4':'',meeting_url:'',description:i%3?'Add your real meeting URL before the class starts.':'Example video supplied for the local preview.'}))
 return {institute,rooms,programmes,teachers,students,enrollments,invoices,sessions,profiles,links,news:[],notifications:[],papers:[],attempts:[],assignments:[],tickets:[],replies:[],attendance:[],grants:[],scenario:'teen-academy-v1'}
}
