<script setup>
import {ref} from 'vue'
const emit=defineEmits(['login'])
const email=ref(''),password=ref(''),error=ref('')
const accounts=[['Student','student@admin.com'],['Teacher','teacher@admin.com'],['Admin','institute@admin.com'],['Super Admin','superadmin@admin.com']]
function login(){const account=accounts.find(a=>a[1]===email.value.trim().toLowerCase());if(!account||password.value!=='1234'){error.value='Use one of the preview accounts below with password 1234.';return}emit('login',account[0])}
</script>
<template><main class="preview-login"><section><span class="eyebrow">SISU · YOUR LOCAL PLAYGROUND</span><h1>A little space.<br>A world to explore.</h1><p>Try each workspace with a preview account. These credentials work only in this local interface preview.</p><form @submit.prevent="login"><label>Email<input type="email" v-model="email" autocomplete="off" required placeholder="teacher@admin.com"/></label><label>Password<input type="password" v-model="password" autocomplete="off" required placeholder="1234"/></label><p v-if="error" role="alert">{{error}}</p><button class="button primary">Open my workspace →</button></form><div class="preview-accounts"><button v-for="a in accounts" @click="email=a[1];password='1234';error=''" :key="a[0]"><strong>{{a[0]==='Admin'?'Institute Admin':a[0]}}</strong><span>{{a[1]}}</span><small>Password: 1234</small></button></div><small>Fictional academy · No charges · No emails sent · No production access</small><a href="/">Back to real sign-in</a></section></main></template>
<style scoped>.preview-login{min-height:100vh;display:grid;place-items:center;background:radial-gradient(ellipse at top left,#e8dcfa,transparent 65%),#f8f4fc;padding:35px 20px;color:#4d3c61}.preview-login section{max-width:650px;width:100%;padding:40px;background:#fffcff;border:1px solid #e9dff3;border-radius:30px;box-shadow:0 25px 70px #69508310}.preview-login h1{font-size:38px;margin:20px 0}.preview-login p{font-size:13px;margin-bottom:20px}.preview-login form{display:grid;gap:15px;margin:25px 0}.preview-login label{display:grid;gap:8px;font-size:12px}.preview-login input{padding:14px;border:1px solid #ddd0eb;border-radius:12px;background:#faf7fd;color:inherit}.preview-accounts{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:25px}.preview-accounts button{display:grid;gap:6px;text-align:left;padding:14px;border:1px solid #e7dcf0;border-radius:14px;background:#f8f2fd}.preview-accounts strong{font-size:12px}.preview-accounts span{font-size:11px;overflow-wrap:anywhere}.preview-login a{display:block;margin-top:20px;font-size:12px;text-decoration:underline}@media(max-width:500px){.preview-login section{padding:25px}.preview-login h1{font-size:30px}.preview-accounts{grid-template-columns:1fr}}</style>
