<script setup>
import {ref,defineAsyncComponent,computed} from 'vue'
import Login from './Login.vue'
import {selectPreviewRole,loadAcademy} from './adapter'
const Campus=defineAsyncComponent(()=>import('../App.vue')),Owner=defineAsyncComponent(()=>import('../native/SuperAdmin.vue'))
const Signup=defineAsyncComponent(()=>import('../native/RegistrationFlow.vue')),showSignup=ref(false)
const linkNotice=ref('')
function guardLink(event){const a=event.target.closest('a');if(!a)return;const u=new URL(a.href,location.href);if(u.origin===location.origin&&/^\/(api|lms|login|me)(\/|$)/.test(u.pathname)){event.preventDefault();event.stopPropagation();linkNotice.value='This page requires a connected Frappe site. Your frontend preview remains open.'}}
const loggedIn=ref(sessionStorage.getItem('sisu-preview-login')==='yes')
function login(value){role.value=value;changeRole();loggedIn.value=true;sessionStorage.setItem('sisu-preview-login','yes')}
function logout(){loggedIn.value=false;sessionStorage.removeItem('sisu-preview-login')}
const role=ref(sessionStorage.getItem('sisu-preview-role')||'Student'),revision=ref(0),screen=ref(location.hash.slice(1)||'dashboard')
if(!['Student','Teacher','Admin','Super Admin'].includes(role.value))role.value='Student'
loadAcademy();selectPreviewRole(role.value)
const screens=computed(()=>[{id:'dashboard',label:'Dashboard'},{id:'classrooms',label:'Classrooms'},{id:'schedule',label:'Schedule'},{id:'programmes',label:'Programmes'},...(role.value==='Admin'?[{id:'team',label:'Teaching team'}]:[{id:'papers',label:'Papers'}]),{id:'profile',label:'My profile'},{id:'connections',label:'Profiles & connections'},{id:'operations',label:'Attendance & support'},{id:'news',label:'Keep Me Update'},{id:'payments',label:'Class fees'},...(role.value==='Student'?[{id:'study',label:'Study Room'}]:[{id:'wallet',label:'Wallet & payouts'},{id:'live',label:'YouTube Live'}]),{id:'settings',label:'Settings'}])
function changeRole(){sessionStorage.setItem('sisu-preview-role',role.value);selectPreviewRole(role.value);screen.value='dashboard';location.hash='dashboard';revision.value++}
function changeScreen(){location.hash=screen.value;revision.value++}
</script>
<template><Login v-if="!loggedIn" @login="login"/><div v-else class="preview-platform" @click.capture="guardLink"><header class="preview-toolbar"><div><strong>✦ Platform preview</strong><span>Browser-only · No payments or messages sent</span></div><label>View as<select v-model="role" @change="changeRole"><option>Student</option><option>Teacher</option><option value="Admin">Institute Admin</option><option>Super Admin</option></select></label><label v-if="role!=='Super Admin'">Open screen<select v-model="screen" @change="changeScreen"><option v-for="s in screens" :value="s.id">{{s.label}}</option></select></label><button @click="showSignup=!showSignup">{{showSignup?'Back to workspace':'Preview signup'}}</button><button @click="logout">Sign out of preview</button></header><div class="preview-explanation">Teen Academy example · 320 fictional students, 12 member teachers and 2 requests. Original illustrated profiles. No affiliation with a real academy; no real payments or messages.</div><p v-if="linkNotice" role="status" class="preview-explanation">{{linkNotice}} <button @click="linkNotice=''">Dismiss</button></p><Signup v-if="showSignup" @back="showSignup=false"/><Owner v-else-if="role==='Super Admin'" :key="revision" :session="{user:'superadmin@admin.com',role:'Super Admin'}"/><Campus v-else :key="revision"/></div></template>
<style>.preview-toolbar{position:sticky;top:0;z-index:200;background:#554369;color:#fff;padding:12px 24px;display:flex;align-items:center;gap:24px;flex-wrap:wrap;box-shadow:0 3px 12px #30213919}.preview-toolbar>div{display:flex;flex-direction:column;gap:5px;margin-right:auto}.preview-toolbar strong{font-size:13px}.preview-toolbar span{font-size:10px;color:#e0d1ef}.preview-toolbar label{display:flex;align-items:center;gap:10px;font-size:11px}.preview-toolbar select{padding:9px 12px;border:1px solid #baa5cf;border-radius:9px;background:#6b547f;color:#fff;font:inherit}.preview-toolbar a{font-size:11px;color:#eee2ff}.preview-explanation{padding:10px 24px;background:#ede3f6;color:#695579;font-size:11px;line-height:1.7}.preview-platform .app-shell{margin-top:0}.preview-platform .sidebar{position:sticky;top:76px;height:calc(100vh - 76px);flex-shrink:0}.preview-platform .workspace{margin-left:0;margin-right:0;flex:1;min-width:0}.preview-toolbar>button{font-size:11px}@media(max-width:760px){.preview-platform .sidebar{position:fixed;top:155px;height:calc(100vh - 155px)}}.preview-platform .owner-shell{min-height:calc(100vh - 110px)}@media(max-width:650px){.preview-toolbar{gap:12px;padding:12px 15px}.preview-toolbar>div{flex-basis:100%}.preview-toolbar label{flex:1}.preview-toolbar select{max-width:180px}.preview-explanation{padding:10px 15px}}
</style>
