<script setup>
import {ref,onMounted} from 'vue'
import Icon from '../Icon.vue'
import {request} from './client'
const emit=defineEmits(['navigate']),access=ref({}),quote=ref(null),error=ref(''),busy=ref(false)
const products=[{id:'study',product:'Study Space',icon:'Headphones',title:'A little room to focus.',body:'Living scenery, gentle sounds and a clock that moves at your pace.',color:'lilac'},{id:'todo',product:'To-do',icon:'CheckCheck',title:'One small step.',body:'Give your plans a place to land. Make today a little lighter.',color:'blue'},{id:'journal',product:'Journal',icon:'NotebookPen',title:'A page for you.',body:'Your thoughts, small wins and all the things worth remembering.',color:'rose'}]
async function open(p){error.value='';busy.value=true;try{if(access.value[p.product]&&p.id==='study'){emit('navigate','study');return}quote.value=await request('owner_pricing','quote',{product:p.product})}catch(e){error.value=e.message}finally{busy.value=false}}
onMounted(async()=>{try{access.value=await request('owner_pricing','entitlements')}catch(e){error.value=e.message}})
const money=(n,c)=>new Intl.NumberFormat(undefined,{style:'currency',currency:c}).format(n/100)
</script>
<template><section><div class="page-heading"><div><span class="eyebrow">LITTLE APPS. MORE ROOM FOR YOU.</span><h1>Your everyday companions.</h1><p>Quiet corners for focus, plans and reflections. Choose what feels like you.</p></div><span class="badge violet">✦ Premium apps</span></div><p v-if="error" role="alert" class="form-note">{{error}}</p><div class="native-app-grid"><article v-for="p in products" class="panel native-app-card"><div class="native-app-art" :class="p.color"><span>✧</span><Icon :name="p.icon" :size="66"/><i>✦</i></div><div><small>✦ {{p.product}}</small><h2>{{p.title}}</h2><p>{{p.body}}</p><button class="button primary" :disabled="busy" @click="open(p)">{{access[p.product]&&p.id==='study'?'Open app':'View my checkout'}}<Icon name="ArrowUpRight" :size="15"/></button></div></article></div><section v-if="quote" class="panel checkout-card" role="region" aria-label="Assigned checkout price"><div class="section-heading"><h2>Your {{quote.product||'app'}} checkout</h2><button class="text-button" @click="quote=null">Close</button></div><p>Your administrator’s assigned agreement · {{quote.period}}</p><dl><dt>Subtotal</dt><dd>{{money(quote.breakdown.subtotal_minor,quote.currency)}}</dd><dt>Discount</dt><dd>−{{money(quote.breakdown.discount_minor,quote.currency)}}</dd><dt>Tax</dt><dd>{{money(quote.breakdown.tax_minor,quote.currency)}}</dd><dt>Total</dt><dd><strong>{{money(quote.breakdown.total_minor,quote.currency)}}</strong></dd></dl><p>Quote valid for 15 minutes. No payment has been taken.</p><p v-if="!quote.payment_available" class="form-note">Subscription checkout is awaiting payment-provider integration. Contact your administrator to arrange access.</p></section></section></template>
<style>.native-app-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:25px;margin:35px 0}.native-app-card{overflow:hidden}.native-app-card>div:last-child{padding:28px}.native-app-art{height:210px;display:flex;align-items:center;justify-content:center;gap:20px;color:#8764a5;background:radial-gradient(at 20% 5%,#f5edfd,#ded0ef)}.native-app-art>svg{padding:20px;box-sizing:content-box;border:4px solid #fff9;border-radius:28px;background:#f6eeff80;transform:rotate(-9deg);box-shadow:10px 13px 0 #9470b225}.native-app-art.blue{background:linear-gradient(140deg,#eeeefe,#cdd5ed);color:#7884b2}.native-app-art.rose{background:linear-gradient(140deg,#fcf0e8,#e9d0e3);color:#ae7b9e}.native-app-art span{align-self:flex-start;margin-top:38px;font-size:28px}.native-app-art i{align-self:flex-end;margin-bottom:42px;font-style:normal}.native-app-card h2{font-size:23px;margin:20px 0}.native-app-card p{font-size:13px;line-height:1.9;margin:15px 0 25px;min-height:70px}.native-app-card small{font-size:11px;color:#9a80ad}.checkout-card{max-width:650px;padding:30px}.checkout-card p{margin:18px 0;font-size:12px;line-height:1.8}.checkout-card dl{display:grid;grid-template-columns:1fr 1fr;gap:18px;font-size:14px}.checkout-card dd{text-align:right}.checkout-card strong{font-size:25px}@media(max-width:800px){.native-app-grid{grid-template-columns:1fr}.native-app-card p{min-height:0}}</style>
