<script setup>
import {ref,onMounted} from 'vue'
import {request} from './client'
import {previewMode} from '../preview/mode'
const props=defineProps({member:Object}),emit=defineEmits(['changed'])
const email=ref(''),rows=ref([]),message=ref(''),error=ref(''),busy=ref(false)
async function load(){rows.value=await request('invitations','list_invitations')}
async function send(){busy.value=true;error.value='';try{const r=await request('invitations',props.member.role==='Admin'?'invite_teacher':'request_by_email',{email:email.value});message.value=previewMode?'Saved in this preview only. No email was sent.':r.message||'Invitation email queued. The teacher signs in with that email to respond.';email.value='';await load();emit('changed')}catch(e){error.value=e.message}finally{busy.value=false}}
async function respond(r,decision){busy.value=true;error.value='';try{await request('invitations','respond',{name:r.name,decision});message.value=decision==='Accepted'?'Membership request submitted for institute approval.':'Invitation declined.';await load();emit('changed')}catch(e){error.value=e.message}finally{busy.value=false}}
onMounted(()=>load().catch(e=>error.value=e.message))
</script>
<template><section class="panel membership-mail"><h2>{{member.role==='Admin'?'Invite a teacher by email':'Connect with an institute'}}</h2><p>{{member.role==='Admin'?'Invite teachers using the email they use for SISU. Invitations expire after seven days.':'Enter the institute owner’s registered email to request membership, or respond to an invitation below.'}}</p><form class="inline wrap" @submit.prevent="send"><label>{{member.role==='Admin'?'Teacher email':'Institute owner email'}}<input v-model="email" type="email" required maxlength="254" placeholder="name@example.com"></label><button class="button primary" :disabled="busy">{{member.role==='Admin'?'Send teacher invitation':'Request to join by email'}}</button></form><p v-if="message" role="status">{{message}}</p><p v-if="error" role="alert" class="error">{{error}}</p><article v-for="r in rows" :key="r.name" class="invitation-row"><div><strong>{{member.role==='Admin'?r.invite_email:r.institute_title}}</strong><small>{{r.expired?'Expired':r.status}} · Expires {{String(r.expires_at).slice(0,10)}}</small></div><template v-if="member.role==='Teacher'&&!r.expired&&r.status==='Pending'"><button class="button subtle small" :disabled="busy" @click="respond(r,'Accepted')">Accept invitation</button><button class="text-button" :disabled="busy" @click="respond(r,'Declined')">Decline</button></template></article><small>Invitation acceptance submits a membership request. Classroom access starts after institute approval and assignment.</small></section></template>
<style>.membership-mail{padding:26px;margin:26px 0}.membership-mail h2{font-size:21px}.membership-mail p{font-size:13px;line-height:1.8;margin:12px 0}.membership-mail form{align-items:end;gap:16px;margin:20px 0}.membership-mail label{display:grid;gap:8px;font-size:12px;flex:1;min-width:200px}.membership-mail input{border:1px solid var(--student-border);border-radius:12px;padding:12px;background:var(--student-card);color:var(--student-ink)}.membership-mail small{display:block;font-size:11px;line-height:1.8;color:var(--student-muted)}.invitation-row{display:flex;gap:12px;flex-wrap:wrap;align-items:center;padding:16px 0;border-top:1px solid var(--student-border)}.invitation-row>div{flex:1}.invitation-row strong{font-size:13px}</style>
