<script setup>
import {ref,onMounted} from 'vue'
import {request} from './client'
const policy=ref({privacy_policy_url:'',privacy_policy_version:'',provider_applications_enabled:false}),applications=ref([]),reason=ref(''),message=ref(''),busy=ref(false)
async function run(fn){busy.value=true;message.value='';try{await fn()}catch(e){message.value=e.message}finally{busy.value=false}}
async function load(){[policy.value,applications.value]=await Promise.all([request('portal_policy','public',{},'GET'),request('registration','applications')])}
async function save(){await run(async()=>{policy.value=await request('portal_policy','save',policy.value);message.value='Onboarding settings saved.'})}
async function review(a,decision){await run(async()=>{await request('registration','review_application',{name:a.name,decision,reason:reason.value});await load();message.value='Application '+decision.toLowerCase()+'. Approved applicants receive secure password setup when their account is created.'})}
function details(a){try{return JSON.parse(a.details)}catch{return {}}}
onMounted(()=>run(load))
</script>
<template><section><p v-if="message" class="form-note" role="status">{{message}}</p><form class="panel owner-block" @submit.prevent="save"><span class="eyebrow">A CLEAR START FOR EVERYONE</span><h2>Signup & privacy</h2><p>Your privacy-policy space is ready. Leave it empty until your policy is published. Provider applications stay closed until a policy URL and version are supplied and you enable applications.</p><div class="owner-fields"><label>Published privacy-policy URL<input v-model="policy.privacy_policy_url" type="url" placeholder="https://your-domain.com/privacy"></label><label>Policy version<input v-model="policy.privacy_policy_version" maxlength="80" placeholder="For example: 2026-10-01"></label></div><label class="policy-toggle"><input v-model="policy.provider_applications_enabled" type="checkbox">Accept provider applications</label><p>Google sign-in: {{policy.google_available?'configured':'awaiting site configuration'}}. Students complete their profile and mobile verification after Google sign-in.</p><button class="button primary" :disabled="busy">Save signup settings</button></form><section class="panel owner-block"><h2>Teacher & institute applications</h2><p>Review the submitted identity and business details before approving an account. Profile verification and code issuance remain a separate review.</p><label>Review reason<textarea v-model="reason" maxlength="1000" placeholder="Record the evidence reviewed"></textarea></label><article v-for="a in applications" :key="a.name" class="owner-review"><div><strong>{{details(a).organization||details(a).full_name}}</strong><p>{{a.email}} · {{a.account_type}}</p><details><summary>Application details</summary><dl class="application-review-details"><template v-for="(value,key) in details(a)" :key="key"><dt>{{key.replaceAll('_',' ')}}</dt><dd>{{value||'—'}}</dd></template></dl></details></div><button class="button primary" :disabled="busy||!reason.trim()" @click="review(a,'Approved')">Approve application</button><button class="button subtle" :disabled="busy||!reason.trim()" @click="review(a,'Rejected')">Reject</button></article><p v-if="!applications.length">No applications awaiting review.</p><p v-if="applications.length===30">Showing the first 30 pending applications. More appear as these are reviewed.</p></section></section></template>
<style>.owner-block .policy-toggle{display:flex;flex-direction:row;align-items:center}.application-review-details{display:grid;grid-template-columns:1fr 2fr;gap:10px;font-size:12px;max-width:650px;margin-top:20px}.application-review-details dd{margin:0;overflow-wrap:anywhere}.application-review-details dt{text-transform:capitalize;color:#82718c}</style>
