<script setup>
import {ref,onMounted,computed} from 'vue'
import {request} from './client'
const props=defineProps({member:Object,rooms:Array}),emit=defineEmits(['refresh','room','navigate'])
const programmes=ref([]),selected=ref(null),editing=ref(false),error=ref(''),note=ref(''),busy=ref(false),form=ref({title:'',description:'',fee:0,duration_months:6,modules:[]})
const eligible=computed(()=>props.rooms.filter(r=>r.owner_type!=='Teacher'&&!r.programme))
async function load(){try{programmes.value=await request('teaching','programmes')}catch(e){error.value=e.message}}
async function save(){busy.value=true;error.value='';try{await request('teaching','save_programme',{data:form.value});editing.value=false;await load();emit('refresh')}catch(e){error.value=e.message}finally{busy.value=false}}
async function join(p){busy.value=true;error.value='';try{await request('teaching','enroll_programme',{programme:p.name});note.value='Programme enrollment created. One invoice covers every module. Review it in Class fees; no payment has been taken.';emit('refresh')}catch(e){error.value=e.message}finally{busy.value=false}}
onMounted(load)
</script>
<template><section class="programme-page"><div class="page-heading"><div><span class="eyebrow">ONE JOURNEY. EVERY MODULE INCLUDED.</span><h1>Room for your next chapter.</h1><p>Complete programmes, guided by a team of teachers.</p></div><button v-if="member.role==='Admin'" class="button primary" @click="editing=!editing">Create programme</button></div><p v-if="error" class="error" role="alert">{{error}}</p><p v-if="note" class="form-note" role="status">{{note}} <button class="text-button" @click="emit('navigate','payments')">View class fees →</button></p>
<form v-if="editing" class="panel programme-form" @submit.prevent="save"><h2>Bring your modules together.</h2><p>Create institute classrooms first, then select a different classroom for each module. Existing enrollments cannot be moved into a bundle.</p><label>Programme name<input v-model="form.title" required maxlength="120"></label><label>Description<textarea v-model="form.description" maxlength="1500"></textarea></label><div class="form-row"><label>Total tuition · LKR<input v-model.number="form.fee" type="number" min="0" step="0.01" required></label><label>Duration · months<input v-model.number="form.duration_months" type="number" min="1" max="60"></label></div><div v-for="(m,i) in form.modules" class="module-edit"><label>Module {{i+1}}<select v-model="m.classroom" required><option value="">Choose a classroom</option><option v-for="r in eligible" :value="r.name">{{r.title}} · {{r.teacher_name}}</option></select></label><label>Weeks<input v-model.number="m.duration_weeks" type="number" min="1" max="52"></label><button type="button" class="text-button" @click="form.modules.splice(i,1)">Remove</button></div><button type="button" class="button subtle" @click="form.modules.push({classroom:'',duration_weeks:2})">Add module</button> <button class="button primary" :disabled="busy||!form.modules.length">Save programme</button></form>
<div class="programme-grid"><article v-for="p in programmes" class="panel programme-card"><img v-if="p.cover_image" :src="p.cover_image" alt=""><div class="programme-copy"><span class="badge violet">{{p.duration_months}} months · {{p.modules.length}} modules</span><h2>{{p.title}}</h2><p>{{p.description}}</p><div class="programme-price"><strong>LKR {{Number(p.fee).toLocaleString()}}</strong><span>one programme tuition payment</span></div><p class="field-help">Paid to the institute. All modules included; no separate teacher charges. Any assigned platform fee is shown on your invoice.</p><button class="button subtle" @click="selected=selected?.name===p.name?null:p">{{selected?.name===p.name?'Hide modules':'Explore the modules'}}</button> <button v-if="member.role==='Student'" class="button primary" :disabled="busy" @click="join(p)">Enroll in programme</button></div></article></div>
<section v-if="selected" class="panel programme-syllabus"><span class="eyebrow">YOUR LEARNING JOURNEY</span><h2>{{selected.title}} · module plan</h2><article v-for="(m,i) in selected.modules"><span class="module-number">{{String(i+1).padStart(2,'0')}}</span><div><h3>{{m.title}}</h3><p>{{m.teacher_name||m.teacher}} · {{m.duration_weeks}} weeks</p></div><button v-if="rooms.some(r=>r.name===m.classroom)" class="text-button" @click="emit('room',rooms.find(r=>r.name===m.classroom))">Open classroom →</button></article></section><p v-if="!programmes.length&&!editing" class="panel empty-mini">Programmes will appear here when your institute adds them.</p></section></template>
<style>.programme-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:25px}.programme-card{overflow:hidden}.programme-card>img{width:100%;aspect-ratio:3;object-fit:cover}.programme-copy{padding:30px}.programme-copy h2{font-size:27px;margin:18px 0}.programme-copy p{font-size:13px;line-height:1.9;margin:15px 0}.programme-price{display:flex;flex-direction:column;gap:8px;margin:26px 0}.programme-price strong{font-size:29px;color:var(--student-accent)}.programme-price span{font-size:11px}.programme-syllabus,.programme-form{padding:30px;margin:28px 0}.programme-syllabus h2{margin:18px 0}.programme-syllabus article{display:flex;align-items:center;gap:20px;padding:20px 0;border-bottom:1px solid var(--student-border)}.programme-syllabus article>div{flex:1}.programme-syllabus h3{font-size:15px}.programme-syllabus p{font-size:12px;margin-top:8px}.module-number{background:var(--student-soft);color:var(--student-accent);width:43px;height:43px;display:grid;place-items:center;border-radius:14px}.programme-form label{display:flex;flex-direction:column;gap:10px;margin:20px 0;font-size:12px}.programme-form :is(input,select,textarea){padding:13px;border:1px solid var(--student-border);border-radius:12px;background:var(--student-card);color:var(--student-ink)}.programme-form p{font-size:12px;line-height:1.8;margin:15px 0}.module-edit{display:grid;grid-template-columns:1fr 100px 70px;gap:15px;align-items:center}@media(max-width:850px){.programme-grid{grid-template-columns:1fr}.programme-syllabus article{flex-wrap:wrap}}</style>
