<script setup>
import {ref,computed,onMounted} from 'vue'
import {request} from './client'
import Icon from '../Icon.vue'
import MembershipMail from './MembershipMail.vue'
const props=defineProps({member:Object,institute:Object,teamOnly:Boolean}),emit=defineEmits(['navigate','create','room'])
const data=ref(null),error=ref(''),busy=ref(false),decision=ref(null)
const admin=computed(()=>props.member.role==='Admin'),pending=computed(()=>data.value?.memberships.filter(l=>l.status==='Pending')||[])
const money=n=>new Intl.NumberFormat('en-LK',{maximumFractionDigits:0}).format(n)
async function load(){try{data.value=await request('teaching','overview');data.value.memberships.sort((a,b)=>(b.status==='Pending')-(a.status==='Pending'))}catch(e){error.value=e.message}}
async function act(link,status){busy.value=true;error.value='';try{await request('teaching','membership',{name:link.name,status});decision.value=null;await load()}catch(e){error.value=e.message}finally{busy.value=false}}
onMounted(load)
</script>
<template><section class="provider-home"><div class="page-heading"><div><span class="eyebrow">GOOD TEACHING STARTS WITH A LITTLE CLARITY</span><h1>{{teamOnly?'Your teaching team.':admin?institute.title+', together.':'Hello, '+member.full_name.split(' ')[0]+'.'}}</h1><p>{{admin?'Your people, programmes and class fees. All in one place.':'A clear view of your institute teaching and independent classes.'}}</p></div><button v-if="!teamOnly" class="button primary" @click="emit('create')"><Icon name="Plus" :size="17"/>{{admin?'Create institute class':'Create personal class'}}</button></div><p v-if="error" class="error" role="alert">{{error}}</p><p v-if="!data&&!error">Opening your workspace…</p><template v-if="data">
<template v-if="!teamOnly"><div class="provider-metrics"><article class="panel"><span>Enrolled students</span><strong>{{data.students}}</strong><small>Unique learners in your classes</small></article><article class="panel"><span>{{admin?'Approved teachers':'Teaching spaces'}}</span><strong>{{admin?data.teachers:data.memberships.filter(l=>l.status==='Active').length+1}}</strong><small>{{admin?'Verified institute memberships':'Institutes + your personal workspace'}}</small></article><article class="panel"><span>Active classrooms</span><strong>{{data.classrooms.length}}</strong><small>Monthly subjects & programme modules</small></article><article class="panel"><span>{{admin?'Teacher requests':'Institute requests'}}</span><strong>{{pending.length}}</strong><small>{{admin?'Waiting for your review':'Memberships awaiting a decision'}}</small></article></div>
<div class="provider-columns"><section class="academy-feature"><div><span class="eyebrow">ONE PROGRAMME. MANY POSSIBILITIES.</span><h2>{{data.programmes[0]?.title||'Build a complete learning journey.'}}</h2><p>{{data.programmes[0]?`${data.programmes[0].duration_months} months · ${data.programmes[0].modules.length} modules · one programme enrollment`:'Bring your subject modules and teachers together in a programme.'}}</p><button class="button primary" @click="emit('navigate','programmes')">Explore programmes <Icon name="ArrowRight" :size="16"/></button></div><span class="programme-art">✦<span>learn<br>grow<br>become.</span></span></section><section class="panel fee-summary"><span class="eyebrow">TUITION · PLATFORM FEES EXCLUDED</span><h2>{{admin?'Paid to your institute.':'Know where each payment goes.'}}</h2><p>{{admin?'SISU settles institute-owned class and programme fees to the institute. You arrange teacher compensation separately.':'Institute classes pay the institute. Only your independently owned classes credit your teacher wallet.'}}</p><div v-for="row in data.totals" class="fee-total"><span>{{row.status}}</span><strong>{{row.currency}} {{money(row.amount)}}</strong></div><button class="text-button" @click="emit('navigate','payments')">View fee records →</button></section></div></template>
<MembershipMail :member="member" @changed="load"/><div class="section-heading"><div><h2>{{admin?'People who make it happen.':'Your institute memberships.'}}</h2><p>{{admin?'Teachers apply with their own verified account. You choose who joins.':'Keep institute work and personal classes side by side.'}}</p></div><button v-if="!admin" class="button subtle" @click="emit('navigate','connections')">Find an institute</button></div><div class="provider-team"><article v-for="l in data.memberships" :key="l.name" class="panel team-card"><img v-if="l.person?.cover_image" class="team-cover" :src="l.person.cover_image" alt=""><div class="team-content"><img v-if="l.person?.profile_image" :src="l.person.profile_image" class="team-face" alt=""><span class="badge" :class="l.status==='Pending'?'amber':'green'">{{l.status==='Pending'?'Request to join':'Member'}}</span><h3>{{l.person?.display_name||l.user||l.profile}}</h3><p>{{l.person?.qualifications||'Verified education profile'}}</p><small>@{{l.person?.username}}</small><div class="team-actions"><template v-if="admin&&l.status==='Pending'"><button class="button primary small" :disabled="busy" @click="act(l,'Active')">Accept teacher</button><button class="text-button" :disabled="busy" @click="act(l,'Rejected')">Decline</button></template><button v-else class="text-button" @click="decision=l">{{admin?'Remove from institute':'Leave institute'}}</button></div></div></article><p v-if="!data.memberships.length" class="panel empty-mini">Membership requests and approved teachers will appear here.</p></div>
<section v-if="decision" class="panel membership-confirm" role="alert"><h3>{{admin?'Remove teacher membership?':'Leave this institute?'}}</h3><p>This ends access to the institute’s class assignments. The teacher’s account and personal classes remain available.</p><button class="button primary" :disabled="busy" @click="act(decision,admin?'Removed':'Left')">Confirm {{admin?'removal':'leave'}}</button><button class="button subtle" @click="decision=null">Keep membership</button></section>
</template></section></template>
<style>.provider-metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:18px;margin-bottom:26px}.provider-metrics article{padding:24px;display:flex;flex-direction:column;gap:14px}.provider-metrics span{font-size:12px}.provider-metrics strong{font-size:38px;font-weight:650;color:#8163a1}.provider-metrics small{font-size:10px;line-height:1.6;color:var(--student-muted)}.provider-columns{display:grid;grid-template-columns:1.4fr 1fr;gap:24px;margin-bottom:38px}.academy-feature{background:linear-gradient(125deg,#eee4fa,#e3d6f1 58%,#f4e7ed);border:1px solid #ddd0ed;border-radius:27px;padding:36px;display:flex;gap:24px;align-items:center;overflow:hidden;color:#554465}.academy-feature h2{font-size:29px;line-height:1.3;margin:18px 0}.academy-feature p{line-height:1.8;font-size:13px;margin-bottom:24px}.programme-art{font-size:80px;display:flex;flex-direction:column;align-items:center;color:#9d7fc2;transform:rotate(-7deg);min-width:120px}.programme-art span{font-family:Georgia,serif;font-size:28px;line-height:1.1;color:#826195}.fee-summary{padding:28px}.fee-summary h2{font-size:22px;margin:15px 0}.fee-summary p{font-size:12px;line-height:1.8;margin-bottom:15px}.fee-total{display:flex;justify-content:space-between;padding:11px 0;border-bottom:1px solid var(--student-border);font-size:12px}.fee-summary .text-button{margin-top:18px}.provider-team{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:20px}.team-card{overflow:hidden}.team-cover{width:100%;aspect-ratio:2.8;object-fit:cover}.team-content{padding:0 20px 22px}.team-face{width:70px;height:70px;border:4px solid var(--student-card,#fff);border-radius:50%;object-fit:cover;margin-top:-32px;position:relative;display:block;margin-bottom:12px}.team-content h3{font-size:17px;line-height:1.5;margin:12px 0 7px}.team-content p,.team-content small{font-size:11px;line-height:1.8;color:var(--student-muted)}.team-actions{margin-top:20px;display:flex;gap:12px;align-items:center;flex-wrap:wrap}.membership-confirm{position:sticky;bottom:20px;padding:25px;box-shadow:0 10px 60px #5e3f6230}.membership-confirm p{margin:16px 0}.membership-confirm button{margin-inline-end:10px}@media(max-width:1150px){.provider-team{grid-template-columns:repeat(3,1fr)}.provider-metrics{grid-template-columns:repeat(2,1fr)}}@media(max-width:850px){.provider-columns{grid-template-columns:1fr}.provider-team{grid-template-columns:repeat(2,1fr)}}@media(max-width:560px){.provider-team{grid-template-columns:1fr}.provider-metrics article{padding:18px}.academy-feature{padding:26px}.programme-art{display:none}}</style>
