import test from 'node:test'
import assert from 'node:assert/strict'
import {tableRecords,parseCsv,pdfRecords,pdfTextRows,validateResults,checkXlsxSize} from '../src/resultImport.js'
import {rankDiscovery,keywords} from '../src/discoveryRanking.js'
test('CSV handles quoted cells, UTF-8 BOM and blank credits',()=>{const r=tableRecords(parseCsv('\uFEFFStudent ID,Grade,Credits\r\n"ST-TA0051-00001","A-",\r\n'));assert.equal(r[0].student,'ST-TA0051-00001');assert.equal(r[0].credits,null);assert.throws(()=>parseCsv('"broken'))})
test('bulk validation rejects duplicate, foreign, unknown grade and invalid credits',()=>{const rows=[{student:'ST-1',grade:'A',credits:3},{student:'ST-1',grade:'B',credits:3},{student:'FOREIGN',grade:'Z',credits:-1}];const v=validateResults(rows,[{student:'ST-1',classroom:'math',active:1}],{classroom:'math',term:'Term 1'});assert.equal(v[0].errors.length,0);assert.equal(v[1].errors.length,1);assert.equal(v[2].errors.length,3)})
test('PDF extraction orders positioned text and refuses ambiguous student rows',()=>{const lines=pdfTextRows([{str:'3',transform:[1,0,0,1,200,70]},{str:'ST-BC-00001',transform:[1,0,0,1,10,70]},{str:'B+',transform:[1,0,0,1,150,70]}]);assert.equal(pdfRecords(lines)[0].grade,'B+');assert.throws(()=>pdfRecords(['ST-BC-00001 Alice A 3']));assert.throws(()=>pdfRecords(['Scanned content']))})
test('malformed Excel archives are rejected before loading',()=>{assert.throws(()=>checkXlsxSize(new ArrayBuffer(24)))})
test('keyword caps count unique normalized keywords in any language',()=>{assert.deepEqual(keywords('Maths, mathematics, නිමල්, العربية',5),['mathematics','නිමල්','العربية']);assert.throws(()=>keywords(['a','b','c','d','e','f'],5));assert.throws(()=>keywords(Array.from({length:16},(_,i)=>'subject'+i),15))})
test('discovery combines interest relevance and engagement; popularity sort is explicit',()=>{const p=[{name:'a',title:'Academy',keywords:['mathematics']},{name:'b',title:'Art school',keywords:['arts']}],c=[{provider:'a',active_learners_30d:80},{provider:'b',active_learners_30d:100}];const r=rankDiscovery(p,c,['maths']);assert.equal(r[0].name,'a');assert(r[0].discovery.reason.includes('mathematics'));assert.equal(rankDiscovery(p,c,['maths'],[],'Most active')[0].name,'b');assert.equal(rankDiscovery(p,c,[],[])[0].name,'b')})
