import test from 'node:test'
import assert from 'node:assert/strict'
const storage=new Map()
globalThis.sessionStorage={getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,value)}
const {previewRequest:call,selectPreviewRole:role,resetPreview,loadAcademy}=await import('../src/preview/adapter.js')
test('empty preview supports role navigation and a local paper lifecycle without provider calls',async()=>{
 resetPreview();role('Teacher')
 assert.equal((await call('api','bootstrap')).member.role,'Teacher')
 assert.deepEqual(await call('api','classrooms'),[])
 const classroom=await call('api','save_classroom',{data:{title:'Preview QA'}})
 const paper=await call('papers','draft',{data:{title:'Practice',classroom,duration_minutes:30,questions:[{kind:'True/False',prompt:'One plus one is two.',answer:0,marks:1}]}})
 await call('papers','publish',{name:paper.name});role('Student')
 assert.equal((await call('papers','listing')).length,1)
 const attempt=await call('papers','start',{name:paper.name})
 assert.equal(attempt.questions[0].answer,undefined)
 assert.equal((await call('papers','submit',{attempt:attempt.attempt,answers:[0]})).score,1)
 await assert.rejects(call('papers','generate'),/requires the real server/)
 await assert.rejects(call('wallet','request_payout'),/connected backend/)
 resetPreview()
})
test('preview prices are unassigned until explicitly set by owner',async()=>{
 resetPreview();role('Student')
 await assert.rejects(call('owner_pricing','quote',{product:'Journal'}),/No price is assigned/)
 await assert.rejects(call('owner_pricing','assign',{data:{}}),/Super Admin/)
 role('Super Admin')
 await call('owner_pricing','assign',{data:{customer:'student@admin.com',product:'Journal',base_minor:100,included_units:1,unit_minor:0,discount_bps:0,tax_bps:0,currency:'USD',period:'Monthly'}})
 role('Student')
 const quote=await call('owner_pricing','quote',{product:'Journal'})
 assert.equal(quote.breakdown.total_minor,100)
 assert.equal(quote.payment_available,false)
 resetPreview()
})

test('classroom deletion hides sessions, denies students and restores without losing content',async()=>{
 resetPreview();role('Teacher')
 const name=await call('api','save_classroom',{data:{title:'Removal test'}})
 await call('api','save_session',{data:{classroom:name,title:'Session'}})
 await call('api','set_classroom_deleted',{name,deleted:1})
 assert.deepEqual(await call('api','classrooms'),[])
 assert.deepEqual(await call('api','schedule'),[])
 assert.equal((await call('api','classrooms',{deleted:1})).length,1)
 role('Student')
 await assert.rejects(call('api','classroom_detail',{name}),/unavailable/)
 await assert.rejects(call('api','set_classroom_deleted',{name,deleted:0}),/permission/)
 role('Admin');await assert.rejects(call('api','set_classroom_deleted',{name,deleted:0}),/permission/);role('Teacher');await call('api','set_classroom_deleted',{name,deleted:0})
 assert.equal((await call('api','schedule')).length,1)
 assert.equal((await call('api','classrooms')).length,1)
 resetPreview()
})

test('privacy placeholder stays blank and applications need published policy',async()=>{
 resetPreview();role('Student')
 assert.equal((await call('portal_policy','public')).privacy_policy_url,'')
 await assert.rejects(call('portal_policy','save',{privacy_policy_url:'https://example.invalid/privacy',privacy_policy_version:'1',provider_applications_enabled:true}),/Owner/)
 role('Super Admin')
 await assert.rejects(call('portal_policy','save',{privacy_policy_url:'',privacy_policy_version:'',provider_applications_enabled:true}),/policy URL/)
 await call('portal_policy','save',{privacy_policy_url:'',privacy_policy_version:'',provider_applications_enabled:false})
 assert.equal((await call('portal_policy','public')).provider_applications_enabled,false)
 resetPreview()
})

test('academy programme is one payment; institutional classes never pay the teacher',async()=>{
 resetPreview();loadAcademy();role('Admin')
 const overview=await call('teaching','overview')
 assert.equal(overview.students,320);assert.equal(overview.teachers,12)
 assert.equal(overview.memberships.filter(m=>m.status==='Pending').length,2)
 assert.equal(overview.classrooms.some(r=>r.owner_type==='Teacher'),false)
 const programmes=await call('teaching','programmes')
 assert.equal(programmes[0].fee,135000);assert.equal(programmes[0].modules.length,12)
 assert.equal(new Set(programmes[0].modules.map(m=>m.teacher)).size,12)
 role('Teacher')
 const rooms=await call('api','classrooms')
 assert.equal(rooms.length,3)
 const institutional=rooms.find(r=>r.owner_type==='Institute'),personal=rooms.find(r=>r.owner_type==='Teacher')
 assert.equal(institutional.permissions.delete,false);assert.equal(personal.permissions.delete,true)
 await assert.rejects(call('api','set_classroom_deleted',{name:institutional.name,deleted:1}),/permission/)
 role('Student')
 await call('teaching','enroll_programme',{programme:programmes[0].name})
 await call('teaching','enroll_programme',{programme:programmes[0].name})
 const invoices=await call('api','invoices')
 assert.equal(invoices.filter(i=>i.programme===programmes[0].name).length,1)
 assert.equal(invoices.find(i=>i.programme).recipient,'Teen Academy')
 assert.equal(invoices.find(i=>i.classroom===personal.name).recipient,'Nimal Perera')
 const month=new Date().toISOString().slice(0,7)
 const a=await call('teaching','month_invoice',{classroom:'edexcel-business',month})
 const b=await call('teaching','month_invoice',{classroom:'edexcel-business',month})
 assert.equal(a.invoice,b.invoice)
 resetPreview()
})

test('leaving an institute removes its assignments while personal classes survive',async()=>{
 resetPreview();loadAcademy();role('Teacher')
 await call('teaching','membership',{name:'membership-1',status:'Left'})
 const rooms=await call('api','classrooms')
 assert.equal(rooms.length,1);assert.equal(rooms[0].owner_type,'Teacher')
 role('Admin')
 assert.equal((await call('api','classrooms')).length,15)
 resetPreview()
})
