export const planRows=[{id:'Free',max:100,prices:[0,0,0,0,0]},{id:'Starter',max:250,prices:[20,30,40,49,59]},{id:'Growth',max:500,prices:[40,60,79,99,119]},{id:'Professional',max:1000,prices:[72,109,143,179,215]},{id:'Business',max:2500,prices:[120,179,239,299,359]},{id:'Scale',max:5000,prices:[200,299,399,499,599]},{id:'Enterprise',max:1000000,prices:[null,null,null,null,null]}]
export const featureCatalog=[
 ['courses','Courses','Learning',true],['classrooms','Classrooms','Learning',true],['videos','External video lessons','Learning',true],['live','Live meeting links','Learning',true],['assignments','Assignments','Assessment',true],['quizzes','Quizzes & exams','Assessment',true],['attendance','Attendance','Assessment',true],['certificates','Certificates','Assessment',true],['results','Academic results','Assessment',true],['rewards','Rewards & stickers','Engagement',true],['games','Learning games','Engagement',false],['marketing','Teacher promotion','Engagement',true],['news','Campus updates','Engagement',true],['email','Email notifications','Communication',true],['whatsapp','WhatsApp notifications','Communication',true],['payments','Payments','Commerce',true],['reports','Reports & exports','Operations',true],['study','Study Space','Learning',true],['custom_domain','Custom domain','Branding',false],['white_label','White-label branding','Branding',false],['ai','AI tools','Coming soon',false],['calendar_sync','External calendar sync','Coming soon',false],['marketplace','Public marketplace','Coming soon',false],['mobile','Native mobile apps','Coming soon',false],['parent','Parent portal','Coming soon',false]
].map(([key,label,category,value])=>({key,label,category,value,comingSoon:category==='Coming soon'}))
export const paygCatalog=[{id:'storage',name:'Extra storage / 10 GB',price:5},{id:'seat',name:'Additional staff seat',price:5},{id:'domain',name:'Custom domain',price:10},{id:'white_label',name:'White-label branding',price:49},{id:'analytics',name:'Advanced exam analytics',price:15},{id:'games',name:'Games & rewards pack',price:10},{id:'support',name:'Priority support',price:25}]
export function defaultConfig(){return {tier:'A',country:'Sri Lanka',students:360,prices:structuredClone(planRows),features:{},countryOverrides:{},planDefaults:{},locks:{ai:true,calendar_sync:true,marketplace:true,mobile:true,parent:true},limits:{students:500,teachers:25,courses:50,assignment_mb:15,storage_gb:10,exam_questions:100,exam_attempts:2},billing:{cardSignup:false,cardFree:false,collectionDay:1,graceDays:7,retries:'1,3,7',payg:false,manualInvoice:false,tax:0,discount:0},branding:{name:'Sisu Lanka Demo Academy',color:'#967bb1',domain:'',support:''},exam:{negative:false,answers:true,scheduled:false,ranking:false,randomQuestions:true,randomAnswers:true},rewards:{points:true,badges:true,streaks:true,leaderboard:false},payg:structuredClone(paygCatalog),audit:[]}}
export function quotePlan(count,tier='D',rows=planRows){if(!Number.isInteger(count)||count<0||count>1000000)throw Error('Enter a valid active-student count');const idx='ABCDE'.indexOf(tier);if(idx<0)throw Error('Select a market tier');const plan=rows.find(r=>count<=r.max);return {...plan,amount:plan.prices[idx],remaining:Math.max(0,plan.max-count)}}
export function effectiveFeature(key,config,at=Date.now()){
 const item=featureCatalog.find(f=>f.key===key);if(!item)return {value:false,source:'Unknown feature'}
 if(item.comingSoon||config.locks[key])return {value:false,source:'Platform lock'}
 const o=config.features[key];if(o&&(!o.from||Date.parse(o.from)<=at)&&(!o.until||Date.parse(o.until)>at))return {value:!!o.value,source:'Tenant contract'}
 if(key in config.countryOverrides)return {value:!!config.countryOverrides[key],source:'Country override'}
 if(key in config.planDefaults)return {value:!!config.planDefaults[key],source:'Plan default'}
 return {value:item.value,source:'Global default'}
}
export function readConfig(){try{const v=JSON.parse(localStorage.getItem('sisu-launch-v2'));return v?{...defaultConfig(),...v}:defaultConfig()}catch{return defaultConfig()}}
export function saveConfig(value,actor,reason){if(!reason?.trim())throw Error('Add a reason for this configuration change');const previous=readConfig();value.audit=[{at:new Date().toISOString(),actor,reason:reason.trim(),before:{...previous,audit:undefined},after:{...value,audit:undefined}},...previous.audit].slice(0,100);localStorage.setItem('sisu-launch-v2',JSON.stringify(value));window.dispatchEvent(new Event('sisu-config'))}
