<script setup>
import {computed,ref,onMounted} from 'vue'
import Icon from './Icon.vue'
import BulkResults from './BulkResults.vue'
import HelpTip from './HelpTip.vue'
import {call} from './service'
import {calculateGpa,demoScale} from './grades'
const props=defineProps({member:Object,rooms:Array,institute:Object})
const emit=defineEmits(['notify'])
const data=ref(null),error=ref(''),form=ref({classroom:props.rooms[0]?.name||'',student:'',term:'Semester 1',credits:3,grade:'A',excluded:false}),scenario=ref([]),term=ref('All terms'),busy=ref(false)
const student=computed(()=>props.member.role==='Student')
const eligible=computed(()=>data.value?.enrollments.filter(e=>e.classroom===form.value.classroom)||[])
const results=computed(()=>data.value?.results.filter(r=>term.value==='All terms'||r.term===term.value)||[])
const gpa=computed(()=>{try{return calculateGpa(scenario.value)}catch(e){return {error:e.message}}})
const official=computed(()=>calculateGpa(results.value))
async function refresh(){data.value=await call('academic_results')}
async function unlock(){try{await call('gpa_unlock');await refresh();loadResults();emit('notify','GPA calculator unlocked in the demo. No money was collected.')}catch(e){error.value=e.message}}
function loadResults(){scenario.value=results.value.map(r=>({...r}));error.value=''}
async function publish(){busy.value=true;error.value='';try{await call('publish_result',{data:form.value});await refresh();emit('notify','Demo academic result published to the selected student.')}catch(e){error.value=e.message}finally{busy.value=false}}
onMounted(refresh)
</script>
<template><div class="page-heading"><div><div class="eyebrow">EVERY CREDIT. EVERY STEP FORWARD.</div><h1>Results & academic progress.</h1><p>{{institute.title}} · Published course results and credit-weighted planning.</p></div><span class="stat-icon mint"><Icon name="GraduationCap" :size="28"/></span></div><template v-if="data"><p v-if="error" class="error" role="alert">{{error}}</p><BulkResults v-if="!student" :rooms="rooms" :data="data" @published="refresh" @notify="$emit('notify',$event)"/><section class="panel"><div class="section-heading"><div><h2>{{student?'Your published results':'Published results'}}</h2><p>Academic records stay available without a calculator subscription.</p></div><select v-model="term" aria-label="Results term"><option>All terms</option><option v-for="t in [...new Set(data.results.map(r=>r.term))]">{{t}}</option></select></div><div class="table-wrap"><table><thead><tr><th>Course</th><th v-if="!student">Student</th><th>Term</th><th>Credits</th><th>Grade</th><th>GPA inclusion</th></tr></thead><tbody><tr v-for="r in results.slice(0,50)" :key="r.name"><td>{{rooms.find(c=>c.name===r.classroom)?.subject||r.classroom}}</td><td v-if="!student">{{r.student}}</td><td>{{r.term}}</td><td>{{r.credits}}</td><td><span class="badge violet">{{r.grade}}</span></td><td>{{r.excluded?'Excluded':'Included'}}</td></tr></tbody></table></div><p v-if="!results.length" class="empty-mini">No results have been published for this account and term yet.</p><p v-if="results.length>50" class="field-help">Showing the first 50 results. Filter by term to narrow the list.</p></section>
<section v-if="student&&!data.unlocked" class="quiz-upgrade"><span class="stat-icon violet"><Icon name="GraduationCap" :size="30"/></span><div><span class="badge violet">Optional student purchase</span><h2>Make your next semester a little clearer.</h2><p>Unlock the GPA calculator to import published grades and explore what-if scenarios. Your results remain freely visible above.</p><small>Price to be configured. This button simulates the purchase; it does not collect money.</small></div><button class="button primary" @click="unlock"><Icon name="LockKeyhole" :size="16"/>Simulate GPA purchase</button></section>
<section v-if="student&&data.unlocked" class="panel gpa-calculator"><div class="section-heading"><div><span class="badge green">Demo calculator unlocked</span><h2>Your GPA, with perspective. <HelpTip text="GPA = sum of credits × grade points ÷ included credits. Pass/fail, repeat-course, transfer-credit and rounding rules differ by institute. This demo uses an illustrative 4.0 scale."/></h2><p>One institute · illustrative 4.0 scale · {{term}}</p></div><button class="button subtle" @click="loadResults">Import published results</button></div><div class="gpa-summary"><div><small>Published-results estimate</small><strong>{{official.gpa===null?'—':official.gpa.toFixed(2)}}</strong><span>{{official.credits}} included credits</span></div><div><small>Your what-if estimate</small><strong>{{gpa.gpa==null?'—':gpa.gpa.toFixed(2)}}</strong><span>{{gpa.credits||0}} included credits</span></div></div><p v-if="gpa.error" class="error">{{gpa.error}}</p><div v-for="(r,i) in scenario" :key="i" class="gpa-row"><label>Course<input v-model="r.title" :placeholder="rooms.find(c=>c.name===r.classroom)?.subject||'Course name'"></label><label>Credits<input v-model.number="r.credits" type="number" min="0.5" max="60" step="0.5"></label><label>Grade<select v-model.number="r.points"><option v-for="(points,grade) in demoScale" :value="points">{{grade}} · {{points}}</option></select></label><label class="checkbox-label"><input v-model="r.excluded" type="checkbox">Exclude</label><button class="icon-button" :aria-label="'Remove GPA course '+(i+1)" @click="scenario.splice(i,1)"><Icon name="X" :size="17"/></button></div><button class="button subtle" @click="scenario.push({title:'',credits:3,points:3,excluded:false})"><Icon name="Plus" :size="17"/>Add what-if course</button><p class="field-help">What-if edits never change published grades. This estimate is not an official transcript. HND merit/distinction classifications or other GPA scales require your institute’s approved rules before production use.</p></section></template></template>
