<script setup>
import {computed,ref,onMounted} from 'vue'
import {call,isDemo} from './service'
import Icon from './Icon.vue'
import {previewMode} from './preview/mode'
import {sendPasswordReset} from './lib/auth'
const props=defineProps({member:Object,rooms:Array,institute:Object})
const emit=defineEmits(['refresh','notify'])
const data=ref(null),query=ref(''),provider=ref('home'),classroom=ref(props.rooms[0]?.name||''),error=ref(''),confirm=ref(null),typed=ref(''),reason=ref(''),verified=ref(false),busy=ref(false)
const admin=computed(()=>props.member.role==='Admin')
const rows=computed(()=>(data.value?.memberships||[]).filter(m=>m.provider===provider.value&&(m.full_name+' '+m.teacher_id).toLowerCase().includes(query.value.toLowerCase())))
const learners=computed(()=>(data.value?.enrollments||[]).filter(e=>e.classroom===classroom.value&&e.active!==0).filter(e=>(e.student+' '+e.full_name).toLowerCase().includes(query.value.toLowerCase())).slice(0,30))
async function refresh(){data.value=await call('account_controls',{},'accounts')}
function ask(kind,target,title){confirm.value={kind,target,title};typed.value='';reason.value='';verified.value=false;error.value=''}
async function submit(){if(!confirm.value||typed.value!=='CONFIRM'||!reason.value.trim())return;busy.value=true;error.value='';try{await call('account_action',{data:{...confirm.value,reason:reason.value.trim(),verified:verified.value,confirmation:typed.value}},'accounts');confirm.value=null;await refresh();emit('refresh');emit('notify','Account request or membership change saved.')}catch(e){error.value=e.message}finally{busy.value=false}}
async function resetPassword(){if(previewMode){emit('notify','Password reset is disabled in the fictional preview.');return}busy.value=true;error.value='';try{await sendPasswordReset(props.member.user);emit('notify','Password reset email requested.')}catch(e){error.value=e.message}finally{busy.value=false}}
onMounted(()=>refresh().catch(e=>error.value=e.message))
</script>
<template><section class="panel account-controls"><div class="section-heading"><div><span class="eyebrow">YOUR MEMBERSHIPS. YOUR CHOICES.</span><h2>Account & workspace controls</h2><p>Class access, institute membership and account deletion are separate actions.</p></div><Icon name="ShieldCheck" :size="26"/></div><p v-if="error" class="error" role="alert">{{error}}</p><template v-if="data"><div v-if="isDemo&&admin"><h3>Verify institute teachers</h3><div class="form-row"><label>Institute workspace<select v-model="provider"><option v-for="p in data.providers" :value="p.name">{{p.title}}</option></select></label><label>Search teachers<input v-model="query" placeholder="Name or teacher ID"></label></div><div class="table-wrap"><table><thead><tr><th>Teacher</th><th>Membership</th><th>Review</th></tr></thead><tbody><tr v-for="m in rows"><td>{{m.full_name}}<small>{{m.teacher_id}}</small></td><td><span class="badge violet">{{m.status}}</span></td><td><button v-if="m.status==='Pending'" class="text-button" @click="ask('approve_teacher',m.name,'Approve '+m.full_name)">Review & approve</button><button v-if="m.status!=='Removed'" class="text-button" @click="ask('remove_teacher',m.name,'Remove '+m.full_name+' from this institute')">Remove from institute</button></td></tr></tbody></table></div><p v-if="!rows.length" class="field-help">No teacher requests in this workspace. Teachers can submit a private invitation code in Education workspace.</p></div>
<div v-if="member.role==='Teacher'||admin"><h3>Manage classroom students</h3><div class="form-row"><label>Your classroom<select v-model="classroom"><option v-for="r in rooms" :value="r.name">{{r.subject}}</option></select></label><label>Find an enrolled student<input v-model="query" placeholder="Student name or ID"></label></div><div class="table-wrap"><table><thead><tr><th>Student</th><th>Class access</th></tr></thead><tbody><tr v-for="e in learners"><td>{{e.full_name}}<small>{{e.student}}</small></td><td><button class="text-button" @click="ask('remove_student',e.name,'Remove '+e.full_name+' from this class')">Remove from class</button><button v-if="admin" class="text-button" @click="ask('remove_member',e.student,'Remove '+e.full_name+' from this institute')">Remove from institute</button></td></tr></tbody></table></div><p class="field-help">Showing up to 30 matches. Class removal stops access to this class; it does not delete the student’s other memberships or payment history.</p></div>
<div v-if="isDemo&&data.memberships.some(m=>m.account===member.name&&m.status!=='Removed')"><h3>Your institute memberships</h3><article v-for="m in data.memberships.filter(m=>m.account===member.name&&m.status!=='Removed')" class="teacher-metric"><div><strong>{{m.provider_title}}</strong><small>{{m.teacher_id}} · {{m.status}}</small></div><button class="text-button" @click="ask('leave_institute',m.name,'Leave '+m.provider_title)">Leave institute</button></article></div>
<div class="account-danger"><h3>Profile, privacy & sign-in</h3><p>Password resets go to your authenticated account email. Never give your password to a teacher, administrator or SOUL.</p><button class="button subtle small" :disabled="busy" @click="resetPassword">Reset password</button><button class="text-button" @click="ask('delete_profile',member.name,'Request deletion of your profile')">Delete my profile</button><button v-if="admin" class="text-button" @click="ask('delete_institute','home','Request institute account closure')">Delete institute account</button><template v-if="isDemo"><article v-for="p in data.owned_profiles" class="teacher-metric"><div><strong>{{p.title}}</strong><small>@{{p.username}} · {{p.deleted?'Unpublished':'Public profile'}}</small></div><button v-if="!p.deleted" class="text-button" @click="ask('delete_public_profile',p.name,'Unpublish '+p.title+' and request deletion')">Delete public profile</button></article></template><p class="field-help">Deletion creates a tracked request for the account owner or operator. Financial and learning records are reviewed before erasure; submitting a request does not claim they have already been deleted. Institute closure requires checking active students, teachers and outstanding payments.</p><article v-for="r in data.requests" class="teacher-metric"><div><strong>{{r.title||r.kind}}</strong><small>{{r.status}} · {{r.created_at||r.creation}}</small></div></article></div>
<form v-if="confirm" class="account-confirm" @submit.prevent="submit"><h3>{{confirm.title}}</h3><p>This affects only the stated class, workspace or profile. A reason will be recorded.</p><label v-if="confirm.kind==='approve_teacher'" class="checkbox-label"><input v-model="verified" type="checkbox" required>I have checked the teacher’s identity, qualifications and intended role with this institute.</label><label>Reason<textarea v-model="reason" maxlength="500" required></textarea></label><label>Type CONFIRM<input v-model="typed" autocomplete="off" required></label><div class="inline wrap"><button class="button primary" :disabled="busy||typed!=='CONFIRM'||!reason.trim()||(confirm.kind==='approve_teacher'&&!verified)">Confirm action</button><button type="button" class="button subtle" @click="confirm=null">Cancel</button></div></form></template></section></template>
<style scoped>.account-controls{margin-top:24px}.account-controls h2{margin-top:8px}.account-controls h3{font-size:16px;margin-top:25px}.account-controls p{font-size:12px;line-height:1.9;color:#8a7995}.account-controls label{display:block;font-size:12px;margin:12px 0}.account-controls input:not([type=checkbox]),.account-controls select,.account-controls textarea{display:block;width:100%;padding:11px;border:1px solid #e1d7e9;border-radius:10px;background:white;margin-top:7px}.account-controls td>small{display:block;font-size:9px;color:#9988a4}.account-controls td .text-button{margin-inline-end:15px}.account-danger{border-top:1px solid #ece2ef;margin-top:25px}.account-danger>.text-button{margin-inline-start:16px;font-size:11px}.account-confirm{padding:20px;border:1px solid #d6bbde;background:#faf5fc;border-radius:16px;margin-top:25px}.account-confirm h3{margin-top:0}.account-controls .checkbox-label{display:flex;gap:8px;align-items:center}</style>
