<script setup>
import {computed,ref,watch} from 'vue'
import Icon from './Icon.vue'
import {lkr} from './rules'
const props=defineProps({data:Object,teachers:Boolean})
defineEmits(['create'])
const query=ref(''),category=ref('All'),page=ref(0),selected=ref(null)
const filtered=computed(()=> (props.teachers?props.data.teachers:props.data.students).filter(s=>(category.value==='All'||s.category===category.value)&&`${s.full_name} ${s.name} ${s.district||''}`.toLowerCase().includes(query.value.toLowerCase())))
const shown=computed(()=>filtered.value.slice(page.value*20,page.value*20+20))
watch([query,category,()=>props.teachers],()=>{page.value=0;selected.value=null})
const progress=computed(()=>props.data.progress.filter(p=>p.student===selected.value?.name))
</script>
<template><div class="page-heading"><div><div class="eyebrow">THE PEOPLE WHO MAKE IT POSSIBLE</div><h1>{{teachers?'Meet your teachers.':'Every learner has a story.'}}</h1><p>{{teachers?data.teachers.length+' fictional teachers':data.students.length+' registered demo students'}} · Sisu Lanka Demo Academy</p></div><button v-if="!teachers" class="button primary" @click="$emit('create')"><Icon name="UserPlus" :size="16"/>Register a student</button></div>
<section class="panel"><div class="toolbar"><label class="search"><Icon name="Search" :size="17"/><input v-model="query" aria-label="Search community" placeholder="Search name, ID or district"></label><label v-if="!teachers" class="compact-filter">Programme<select v-model="category"><option>All</option><option v-for="c in data.categories">{{c.name}}</option></select></label></div><div class="table-wrap"><table><thead><tr><th>{{teachers?'Teacher':'Student'}}</th><th>Institute ID</th><th>{{teachers?'Classrooms':'Programme'}}</th><th>{{teachers?'Students':'Medium'}}</th><th>{{teachers?'Collected this month':'District'}}</th><th>{{teachers?'Progress':'Profile'}}</th></tr></thead><tbody><tr v-for="s in shown" :key="s.name"><td><div class="inline"><span class="teacher-avatar">{{s.full_name[0]}}</span><strong>{{s.full_name}}</strong></div></td><td>{{s.name}}</td><td>{{teachers?s.classes:s.category}}</td><td>{{teachers?s.students:s.medium}}</td><td>{{teachers?lkr(s.paid):s.district}}</td><td><span v-if="teachers">{{s.progress}}%</span><button v-else class="text-button" @click="selected=s">View profile</button></td></tr></tbody></table></div><div class="community-pager"><span>{{filtered.length?'Showing '+(page*20+1)+'–'+Math.min((page+1)*20,filtered.length):'No matches'}} of {{filtered.length}}</span><div class="inline"><button class="button subtle small" :disabled="page===0" @click="page--">Previous</button><button class="button subtle small" :disabled="(page+1)*20>=filtered.length" @click="page++">Next</button></div></div></section>
<section v-if="selected" class="panel student-detail"><div class="section-heading"><div><span class="eyebrow">SYNTHETIC STUDENT RECORD</span><h2>{{selected.full_name}}</h2><p>{{selected.name}}</p></div><button class="icon-button" aria-label="Close student profile" @click="selected=null"><Icon name="X"/></button></div><div class="profile-fields"><div v-for="field in [['Programme',selected.category],['Grade / stream',selected.grade+' · '+selected.stream],['School / institute',selected.school],['Teaching medium',selected.medium],['District / branch',selected.district+' · '+selected.branch],['Guardian',selected.guardian],['Guardian contact',selected.guardian_contact],['Email',selected.user]]"><small>{{field[0]}}</small><strong>{{field[1]||'Not supplied'}}</strong></div></div><h3>Learning progress</h3><div v-for="p in progress" class="category-meter"><div><strong>{{p.subject}}</strong><span>{{p.completed}} / {{p.total}} lessons · Quiz {{p.quiz}}% · Attendance {{p.attendance}}%</span></div><div class="meter-track"><i :style="{width:p.completed/p.total*100+'%'}"></i></div></div><p class="field-help">Names are fictional. No real phone numbers or national identity numbers are stored in these sample records.</p></section></template>
