<script setup>
import {ref,onMounted} from 'vue'
import {previewMode} from './preview/mode'
import Icon from './Icon.vue'
import {call,isDemo} from './service'
const props=defineProps({member:Object});const emit=defineEmits(['notify'])
const state=ref({email:'',verified:false,email_opt_in:false,calendar:{status:'Disconnected'}}),email=ref(''),code=ref(''),pending=ref(false),busy=ref(false),consent=ref(false),error=ref(''),message=ref('')
let demoChallenge=null
const key='sisu-contact:'+props.member.name
function persist(){localStorage.setItem(key,JSON.stringify(state.value))}
async function refresh(){if(isDemo){try{state.value=JSON.parse(localStorage.getItem(key))||state.value}catch{}}else state.value=await call('status',{},'contact');email.value=state.value.email}
async function request(){busy.value=true;error.value='';try{if(!/^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(email.value)||email.value.length>254)throw Error('Enter a valid email address');if(isDemo){demoChallenge={email:email.value.trim().toLowerCase(),expiresAt:Date.now()+600000,attempts:0};message.value='Demo only: enter 123456 below. No email was sent.'}else{await call('request_verification',{email:email.value},'contact');message.value=previewMode?'Preview only: use 123456. No email was sent.':'Verification email queued. Enter its six-digit code within 10 minutes.'}pending.value=true;code.value=''}catch(e){error.value=e.message}finally{busy.value=false}}
async function verify(){busy.value=true;error.value='';try{if(isDemo){if(!demoChallenge||Date.now()>=demoChallenge.expiresAt||demoChallenge.attempts>=5)throw Error('Code expired. Request a new one');demoChallenge.attempts++;if(code.value!=='123456')throw Error('Code did not match');state.value={email:demoChallenge.email,verified:true,email_opt_in:false,calendar:{status:'Disconnected'}};persist()}else{await call('verify',{code:code.value},'contact');await refresh()}pending.value=false;message.value='Email verified. Choose whether to receive class emails.'}catch(e){error.value=e.message}finally{busy.value=false}}
async function save(){busy.value=true;error.value='';try{if(!state.value.verified&&state.value.email_opt_in)throw Error('Verify your email first');if(isDemo)persist();else await call('preferences',{email_opt_in:state.value.email_opt_in},'contact');emit('notify','Email notification preference saved.')}catch(e){error.value=e.message}finally{busy.value=false}}
async function connect(){if(!consent.value)return;busy.value=true;error.value='';try{if(isDemo){state.value.calendar={status:'Connected',google_email:state.value.email};persist();message.value='Demo calendar connected. No Google account was accessed and no events were created.'}else{const result=await call('connect',{},'calendar_sync');const url=new URL(result.url);if(url.origin!=='https://accounts.google.com')throw Error('Unexpected calendar authorization destination');location.assign(url.href)}}catch(e){error.value=e.message}finally{busy.value=false}}
async function disconnect(){busy.value=true;try{if(isDemo){state.value.calendar={status:'Disconnected'};persist()}else{await call('disconnect',{},'calendar_sync');await refresh()}consent.value=false;message.value='Future calendar updates stopped. Existing copied events remain in your Google Calendar; remove that calendar there if you no longer want them.'}catch(e){error.value=e.message}finally{busy.value=false}}
onMounted(async()=>{try{await refresh()}catch(e){error.value=e.message}})
</script>
<template><section class="panel contact-settings"><div class="section-heading"><div><span class="eyebrow">YOUR CLASSES, CLOSE AT HAND</span><h2>Email & calendar connection</h2></div><Icon name="CalendarCheck2" :size="26"/></div><p>Verify where we should send your schedule, then choose your updates.</p><ol class="connection-steps"><li :class="{done:state.verified}">Verify email</li><li :class="{done:state.email_opt_in}">Choose updates</li></ol><form @submit.prevent="request"><label>Schedule contact email<input v-model="email" type="email" maxlength="254" required autocomplete="email" placeholder="you@example.com"></label><div class="inline wrap"><button class="button subtle" :disabled="busy">{{state.verified?'Verify another email':'Send verification code'}}</button><span v-if="state.verified" class="badge green">{{isDemo?'Verified in demo':'Verified'}} · {{state.email}}</span></div></form><form v-if="pending" class="verify-email-code" @submit.prevent="verify"><label>Six-digit email code<input v-model="code" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6" required placeholder="000000"></label><button class="button primary" :disabled="busy">Verify email</button></form><label class="checkbox-label"><input v-model="state.email_opt_in" type="checkbox" :disabled="!state.verified">Email me class schedules, changes, materials and payment updates</label><button class="button subtle small" :disabled="busy||!state.verified" @click="save">Save email preference</button><p class="field-help">This is your notification address; it does not change your login email or password. WhatsApp consent and number are managed separately above.</p><div v-if="member.role==='Student'" class="calendar-connect"><h3>Google & Outlook Calendar <span class="badge peach">Coming soon</span></h3><p>Your classes and dated to-do tasks appear in the LMS calendar. External account synchronization is planned for a later release.</p></div><p v-if="message" class="form-note" role="status">{{message}}</p><p v-if="error" class="error" role="alert">{{error}}</p></section></template>
<style>.contact-settings{margin:22px 0}.contact-settings h2{margin:10px 0}.contact-settings>p,.calendar-connect>p{font-size:12px;line-height:1.8}.connection-steps{display:flex;gap:18px;flex-wrap:wrap;padding-inline-start:20px;margin:22px 0;color:#8b7998;font-size:11px}.connection-steps .done{color:#588b6d;font-weight:700}.contact-settings label{display:block;font-size:12px;margin:15px 0}.contact-settings input:not([type=checkbox]){border:1px solid #ded1e6;border-radius:10px;padding:12px;display:block;max-width:420px;width:100%;font:inherit;margin-top:8px}.contact-settings .checkbox-label{display:flex;align-items:center;gap:9px}.verify-email-code{padding:12px 20px;background:#a586c010;border-radius:14px;margin-top:18px}.calendar-connect{margin-top:24px;border-top:1px solid #dfd2e5;padding-top:20px}.calendar-connect h3{font-size:15px}.calendar-connect h3 span{margin-inline-start:8px}.calendar-connect .text-button{display:block;margin-top:12px}</style>
