import { dayKey } from './rules'
const shifted = n => dayKey(new Date(Date.now() + n * 86400000))
const svg = (color, label) => 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="800" height="400"><rect width="800" height="400" fill="${color}"/><circle cx="670" cy="110" r="150" fill="white" opacity=".25"/><circle cx="720" cy="280" r="170" fill="white" opacity=".22"/><path d="M570 230l65-120 65 120z" fill="white" opacity=".7"/><text x="44" y="205" font-family="sans-serif" font-size="42" font-weight="700" fill="#242145">${label}</text></svg>`)
export function seed() {
  const rooms = [
    { name: 'maths', title: 'නිමල් සර්ගේ ගණන් පන්තිය', subject: 'Combined Mathematics', description: 'A little practice, every day. Build your confidence in pure and applied mathematics with clear explanations, guided papers and a supportive classroom.', teacher: 'TC-BC-0001', teacher_name: 'Nimal Perera', fee: 6000, exam_date: shifted(76), motivation: 'පුංචි පියවර, ලොකු හීන', font: 'sans', comments_enabled: 1, allow_teacher_access_override: 1, students: 86, active: 1, color: 'violet', tag: '2026 A/L', progress: 68 },
    { name: 'physics', title: 'Physics, made clear.', subject: 'Physics', description: 'Understand the why behind the world. Weekly theory, practical discussions and past-paper workshops.', teacher: 'TC-BC-0002', teacher_name: 'Kasun Fernando', fee: 4500, exam_date: shifted(76), motivation: 'Small steps. Big discoveries.', font: 'sans', comments_enabled: 1, students: 64, active: 1, color: 'peach', tag: '2026 A/L', progress: 42 },
    { name: 'chemistry', title: 'A little chemistry. A lot of possibility.', subject: 'Chemistry', description: 'Your complete revision space for organic, inorganic and physical chemistry.', teacher: 'TC-BC-0003', teacher_name: 'Dilini Silva', fee: 4000, motivation: 'Your future starts today.', font: 'sans', comments_enabled: 1, students: 72, active: 1, color: 'mint', tag: '2026 A/L', progress: 54 },
  ]
  return {
    institute: { name: 'BC', code: 'BC', title: 'Brightway College', accent: '#7563e6', logo: '', base_fee: 15000 },
    members: [{ name: 'ST-BC-00001', user: 'anuki@example.com', full_name: 'Anuki Jayasinghe', role: 'Student', active: 1, phone: '+94771234567', language: 'en', whatsapp_opt_in: 1 }, ...rooms.map(r => ({ name: r.teacher, user: r.teacher+'@example.com', full_name: r.teacher_name, role: 'Teacher', active: 1 })), { name: 'AD-BC-0001', full_name: 'Sanduni Perera', role: 'Admin', active: 1 }],
    rooms, sessions: [
      { name: 'session-1', classroom: 'maths', title: 'Integration, one step at a time', description: 'Bring your revision workbook. We will work through definite integrals together.', starts_at: shifted(0)+' 16:00:00', ends_at: shifted(0)+' 18:00:00', mode: 'Online', status: 'Scheduled', comments: 'Inherit', location: 'YouTube Live' },
      { name: 'session-2', classroom: 'physics', title: 'Waves & oscillations', starts_at: shifted(0)+' 18:30:00', ends_at: shifted(0)+' 20:00:00', mode: 'Physical', location: 'Nugegoda · Hall 02', status: 'Scheduled', comments: 'Inherit' },
      { name: 'session-3', classroom: 'chemistry', title: 'Organic chemistry workshop', starts_at: shifted(1)+' 09:00:00', ends_at: shifted(1)+' 11:00:00', mode: 'Online', status: 'Scheduled', comments: 'Inherit' },
      { name: 'session-4', classroom: 'maths', title: 'Differentiation · Revision 04', starts_at: shifted(-3)+' 16:00:00', ends_at: shifted(-3)+' 18:00:00', mode: 'Online', status: 'Completed', comments: 'Inherit' },
    ],
    enrollments: rooms.map((r,i) => ({ name: 'enrollment-'+i, classroom: r.name, student: 'ST-BC-00001', fee: r.fee, active: 1, access_override: 'Automatic' })),
    invoices: [{ name: 'INV-001', enrollment: 'enrollment-0', classroom: 'maths', student: 'ST-BC-00001', amount: 3000, installment: 1, due_date: shifted(-12), status: 'Paid', receipt_number: 'RC-INV-001', paid_at: shifted(-12) }, { name: 'INV-002', enrollment: 'enrollment-0', classroom: 'maths', student: 'ST-BC-00001', amount: 3000, installment: 2, due_date: shifted(5), status: 'Unpaid' }, { name: 'INV-003', enrollment: 'enrollment-1', classroom: 'physics', student: 'ST-BC-00001', amount: 4500, installment: 1, due_date: shifted(-10), status: 'Paid', receipt_number: 'RC-INV-003' }, { name: 'INV-004', enrollment: 'enrollment-2', classroom: 'chemistry', student: 'ST-BC-00001', amount: 4000, installment: 1, due_date: shifted(-2), status: 'Overdue' }],
    materials: [{ name: 'material-1', classroom: 'maths', title: 'Differentiation revision notes', kind: 'Document', description: 'Teacher material example · add your own resource URL', url: 'https://www.e-thaksalawa.moe.gov.lk/' }],
    feedback: [{ name: 'feedback-1', classroom: 'maths', session: 'session-4', student: 'ST-BC-00001', body: 'The worked examples were really helpful. Thank you, sir!', creation: shifted(-2) }],
    news: [{ name: 'news-1', headline: 'Your next chapter starts here.', description: '2027 A/L registrations are open. Meet your teachers, explore your subjects and find your place at Brightway.', cta_label: 'Explore classrooms', starts_on: shifted(-7), ends_on: shifted(30), images: [{ image: svg('#e5e0ff', 'A fresh start. A bright future.'), alt: 'A fresh start at Brightway' }, { image: svg('#d9f1e8', 'Learn together. Grow together.'), alt: 'Learn together at Brightway' }] }, { name: 'news-2', headline: 'A space to ask. A place to grow.', description: 'Join our free weekend study circle. Bring your questions and work through them with your classmates.', starts_on: shifted(-1), ends_on: shifted(8), images: [{ image: svg('#ffe9d9', 'The weekend study circle'), alt: 'Weekend study circle' }] }],
    announcements: [{ name: 'announcement-1', classroom: 'maths', headline: 'A little preparation for today', body: 'Please complete questions 1–5 in your revision workbook before our next class.' }],
    notifications: [{ name: 'notice-1', body: 'Your mathematics class is scheduled for today at 4:00 PM.', status: 'Accepted', creation: shifted(0) }, { name: 'notice-2', body: 'Payment received: LKR 3,000. Receipt RC-INV-001.', status: 'Accepted', creation: shifted(-12) }], audits: [],
  }
}
