<script setup>
import {ref,watch} from 'vue'
import {call} from './service'
import {keywords} from './discoveryRanking'
const props=defineProps({interests:Array})
const emit=defineEmits(['saved'])
const selected=ref([...(props.interests||[])]),custom=ref(''),error=ref(''),saved=ref(false)
const choices=['Mathematics','Science','English','Grade 5','O/L','A/L','Computing','Business','Languages','University','Cambridge','Arts','Arabic','Technology']
watch(()=>props.interests,v=>selected.value=[...(v||[])])
function toggle(value){value=value.toLowerCase();selected.value=selected.value.includes(value)?selected.value.filter(k=>k!==value):[...selected.value,value];saved.value=false}
async function save(){error.value='';try{const list=keywords([...selected.value,...keywords(custom.value,20)],20);await call('save_interests',{interests:list});selected.value=list;custom.value='';saved.value=true;emit('saved')}catch(e){error.value=e.message}}
</script>
<template><section class="interest-panel"><div><span class="eyebrow">MAKE DISCOVERY YOURS</span><h2>What are you curious about?</h2><p>Choose your interests. Suggestions also consider classes you joined and recent learner activity.</p></div><div class="interest-chips"><button v-for="choice in choices" :aria-pressed="selected.includes(choice.toLowerCase())" :class="{chosen:selected.includes(choice.toLowerCase())}" @click="toggle(choice)">{{selected.includes(choice.toLowerCase())?'✓ ': '+ '}}{{choice}}</button><button v-for="k in selected.filter(k=>!choices.some(c=>c.toLowerCase()===k))" class="chosen" @click="toggle(k)">{{k}} ×</button></div><div class="interest-actions"><input v-model="custom" aria-label="Other interest keywords" placeholder="Other interests, separated by commas" maxlength="500"><button class="button primary small" @click="save">Save interests</button><button class="text-button" @click="selected=[];custom='';save()">Clear interests</button><span v-if="saved" role="status">Interests saved</span></div><p v-if="error" class="error" role="alert">{{error}}</p><small>Up to 20 interests, in any language. Recommendation controls do not change your classes or create a learning path.</small></section></template>
<style>.interest-panel{padding:24px;border:1px solid #e8dff0;background:linear-gradient(125deg,#faf7ff,#f5faf6);border-radius:20px;margin:22px 0}.interest-panel h2{font-size:19px;margin:8px 0}.interest-panel p{font-size:12px;color:#82738d;line-height:1.8}.interest-chips{display:flex;flex-wrap:wrap;gap:8px;margin:18px 0}.interest-chips button{font-size:11px;padding:8px 12px;border-radius:20px;border:1px solid #dfd4eb;background:#fff;color:#7a6888;cursor:pointer}.interest-chips .chosen{background:#8870af;color:#fff;border-color:#8870af}.interest-actions{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.interest-actions input{flex:1;min-width:200px;border:1px solid #e2d7eb;border-radius:10px;padding:11px;font-size:12px}.interest-actions span,.interest-panel>small{font-size:10px;color:#8a7996}.interest-panel>small{display:block;margin-top:12px}.recommendation-reason{font-size:10px!important;color:#6e8060!important;margin:10px 0!important}.provider-keywords{display:flex;gap:5px;flex-wrap:wrap;margin:12px 0}.provider-keywords span{font-size:9px;background:#f4effa;color:#8c739e;border-radius:6px;padding:4px 7px}</style>
