<script setup>
import {computed} from 'vue'
import Icon from './Icon.vue'
const props=defineProps({role:String,demo:Boolean})
defineEmits(['tour','navigate'])
const guides=computed(()=>props.role==='Student'?[
 {icon:'BookOpen',title:'Find your next lesson',page:'classrooms',steps:['Open My classrooms and choose a subject.','Check the access label; settle a due installment if needed.','Open Sessions or Materials and press Watch.']},
 {icon:'Wallet',title:'Pay an installment',page:'payments',steps:['Filter your payment history to unpaid or overdue.','Check the invoice and installment amount in LKR.','Continue to the configured gateway. Access updates after server verification.']},
 {icon:'CalendarDays',title:'Plan your learning week',page:'schedule',steps:['Choose a day on the calendar.','Check the venue or online session in Sri Lanka time.','Open your classroom for the latest announcements.']},
 {icon:'MessageCircle',title:'Keep in touch',page:'settings',steps:['Review your notification preferences.','Add your own or an authorised guardian’s contact.','Opt in to class updates; you can change this later.']}
]:[
 {icon:'Building2',title:props.role==='Admin'?'Set up your institute':'Build your classroom profile',page:props.role==='Admin'?'settings':'classrooms',steps:props.role==='Admin'?['Add your institute name, logo and brand colour.','Confirm the unique institute code before registration.','Students and teachers receive institute-prefixed IDs.']:['Create a classroom and add its subject and title.','Upload a cover and profile image for your teaching brand.','Set your exam date, motivation line and comment controls.']},
 {icon:'CalendarDays',title:'Schedule your first session',page:'schedule',steps:['Choose a classroom, date, start time and end time.','Select physical or online; add a venue or YouTube link.','Save the schedule. Opted-in learners can receive updates.']},
 {icon:'Wallet',title:'Manage fees and access',page:'payments',steps:['Review paid, unpaid and overdue installments.','Use classroom student access controls for authorised exceptions.','Record a reason for overrides and review grace-period deadlines.']},
 {icon:'Megaphone',title:'Promote a new intake',page:props.demo?'marketing':'news',steps:['Choose a classroom and create a concise promotional card.','Add dates, an offer or trial code, and a clear call to action.','Preview before sharing; manage enquiries and follow up only with consent.']}
])
</script>
<template><div class="page-heading"><div><div class="eyebrow">A LITTLE GUIDANCE GOES A LONG WAY</div><h1>Make yourself at home.</h1><p>Quick walkthroughs for your {{role.toLowerCase()}} workspace.</p></div><button class="button primary" @click="$emit('tour')"><Icon name="Play" :size="17"/>Start product tour</button></div><section class="walkthrough-intro"><span class="stat-icon mint"><Icon name="Globe2" :size="28"/></span><div><h2>Local roots. A global learning community.</h2><p>Choose your country, education system and teaching languages when creating a workspace. Discover institutes and independent teachers, or start with one small task below.</p></div></section><div class="walkthrough-grid"><article v-for="(g,i) in guides" :key="g.title" class="panel"><div class="section-heading"><span class="stat-icon violet"><Icon :name="g.icon" :size="24"/></span><span class="eyebrow">WALKTHROUGH {{String(i+1).padStart(2,'0')}}</span></div><h2>{{g.title}}</h2><ol><li v-for="(s,j) in g.steps" :key="s"><span>{{j+1}}</span><p>{{s}}</p></li></ol><button class="button subtle" @click="$emit('navigate',g.page)">Open workspace <Icon name="ArrowRight" :size="16"/></button></article></div><section class="panel integration-status"><span class="stat-icon peach"><Icon name="ShieldCheck" :size="25"/></span><div><h3>payments.lk integration</h3><p>Selected for the next payment rollout. Merchant credentials, verified webhooks and sandbox acceptance must be completed before accepting real payments. This preview never collects money.</p><a href="https://payments.lk/developers" target="_blank" rel="noopener noreferrer" class="text-button">Official integration guide <Icon name="ArrowUpRight" :size="15"/></a></div></section></template>
