export const labels = {
 en: { dashboard:'Overview',classrooms:'My classrooms',schedule:'My schedule',learning:'Learning hub',payments:'Payments',news:'Campus updates',notifications:'Notifications',people:'People',settings:'Settings',welcome:'A little progress, every day.',hello:'Hello',today:'Today’s schedule',viewAll:'View all',classTitle:'Your learning, in good company.',continue:'Continue learning',search:'Search your classrooms…',workspace:'LEARNING SPACE',manage:'YOUR CAMPUS',help:'A little help goes a long way.',helpBody:'Your institute is here for you.',support:'Contact your institute',open:'Open classroom',upcoming:'Upcoming',all:'All classrooms',subtitle:'Let’s make room for something wonderful today.' },
 si: { dashboard:'දළ විශ්ලේෂණය',classrooms:'මගේ පන්ති',schedule:'කාලසටහන',learning:'ඉගෙනුම් මධ්‍යස්ථානය',payments:'ගෙවීම්',news:'ආයතන පුවත්',notifications:'දැනුම්දීම්',people:'සාමාජිකයන්',settings:'සැකසුම්',welcome:'හැම දවසකම පුංචි ප්‍රගතියක්.',hello:'ආයුබෝවන්',today:'අද කාලසටහන',viewAll:'සියල්ල බලන්න',classTitle:'එකට ඉගෙන ගනිමු.',continue:'ඉගෙනීම දිගටම',search:'ඔබේ පන්ති සොයන්න…',workspace:'ඉගෙනුම් අවකාශය',manage:'ඔබේ ආයතනය',help:'ඔබට සහාය අවශ්‍යද?',helpBody:'ඔබේ ආයතනය ඔබ සමඟයි.',support:'ආයතනය අමතන්න',open:'පන්තිය විවෘත කරන්න',upcoming:'ඉදිරි පන්ති',all:'සියලුම පන්ති',subtitle:'අද දවස අලුත් දැනුමෙන් පුරවමු.' },
 ta: { dashboard:'கண்ணோட்டம்',classrooms:'எனது வகுப்புகள்',schedule:'கால அட்டவணை',learning:'கற்றல் மையம்',payments:'கொடுப்பனவுகள்',news:'நிறுவனச் செய்திகள்',notifications:'அறிவிப்புகள்',people:'உறுப்பினர்கள்',settings:'அமைப்புகள்',welcome:'ஒவ்வொரு நாளும் சிறு முன்னேற்றம்.',hello:'வணக்கம்',today:'இன்றைய அட்டவணை',viewAll:'அனைத்தையும் காண்க',classTitle:'ஒன்றாகக் கற்போம்.',continue:'கற்றலைத் தொடர்க',search:'வகுப்புகளைத் தேடுங்கள்…',workspace:'கற்றல் வெளி',manage:'உங்கள் நிறுவனம்',help:'உதவி தேவையா?',helpBody:'உங்கள் நிறுவனம் உங்களுடன்.',support:'நிறுவனத்தைத் தொடர்புகொள்க',open:'வகுப்பைத் திறக்கவும்',upcoming:'எதிர்வரும் வகுப்புகள்',all:'அனைத்து வகுப்புகள்',subtitle:'இன்று புதிதாக ஒன்றைக் கற்போம்.' }
}

labels.ar={dashboard:'نظرة عامة',classrooms:'فصولي',schedule:'جدولي',learning:'مركز التعلم',payments:'المدفوعات',news:'أخبار المؤسسة',notifications:'الإشعارات',people:'المجتمع',settings:'الإعدادات',welcome:'خطوة إلى الأمام كل يوم',hello:'مرحباً',today:'جدول اليوم',viewAll:'عرض الكل',classTitle:'نتعلم وننمو معاً',continue:'مواصلة التعلم',search:'ابحث عن فصولك…',workspace:'مساحة التعلم',manage:'مؤسستك',help:'نحن هنا لمساعدتك',helpBody:'تواصل مع مؤسستك التعليمية',support:'تواصل مع المؤسسة',open:'فتح الفصل',upcoming:'القادم',all:'كل الفصول',subtitle:'لنجعل اليوم فرصة جديدة للتعلم',discover:'اكتشف',setup:'المساحة التعليمية',guide:'دليل البدء',marketing:'استوديو التسويق',teachers:'المعلمون',competition:'التحدي الشهري',quizzes:'اختبارات الدروس',results:'النتائج والمعدل',live:'البث المباشر'}

labels["fr"]={"dashboard": "Vue d’ensemble", "classrooms": "Mes classes", "schedule": "Mon emploi du temps", "learning": "Apprentissage", "payments": "Paiements", "news": "Actualités", "notifications": "Notifications", "people": "Communauté", "settings": "Paramètres", "discover": "Découvrir", "setup": "Espace éducatif", "guide": "Bien démarrer", "marketing": "Marketing", "teachers": "Enseignants", "competition": "Défi du mois", "quizzes": "Quiz", "results": "Résultats et moyenne", "live": "Studio en direct"}

labels["es"]={"dashboard": "Resumen", "classrooms": "Mis clases", "schedule": "Mi horario", "learning": "Aprendizaje", "payments": "Pagos", "news": "Novedades", "notifications": "Notificaciones", "people": "Comunidad", "settings": "Ajustes", "discover": "Descubrir", "setup": "Espacio educativo", "guide": "Primeros pasos", "marketing": "Marketing", "teachers": "Docentes", "competition": "Reto mensual", "quizzes": "Cuestionarios", "results": "Resultados y promedio", "live": "Estudio en vivo"}

labels["de"]={"dashboard": "Übersicht", "classrooms": "Meine Kurse", "schedule": "Mein Stundenplan", "learning": "Lernzentrum", "payments": "Zahlungen", "news": "Neuigkeiten", "notifications": "Benachrichtigungen", "people": "Gemeinschaft", "settings": "Einstellungen", "discover": "Entdecken", "setup": "Bildungsbereich", "guide": "Erste Schritte", "marketing": "Marketing", "teachers": "Lehrkräfte", "competition": "Monatsaufgabe", "quizzes": "Quiz", "results": "Ergebnisse und Noten", "live": "Live-Studio"}

labels["pt"]={"dashboard": "Visão geral", "classrooms": "Minhas aulas", "schedule": "Meu horário", "learning": "Aprendizagem", "payments": "Pagamentos", "news": "Novidades", "notifications": "Notificações", "people": "Comunidade", "settings": "Configurações", "discover": "Descobrir", "setup": "Espaço educativo", "guide": "Primeiros passos", "marketing": "Marketing", "teachers": "Professores", "competition": "Desafio mensal", "quizzes": "Questionários", "results": "Resultados e média", "live": "Estúdio ao vivo"}

labels["hi"]={"dashboard": "अवलोकन", "classrooms": "मेरी कक्षाएँ", "schedule": "मेरी समय सारणी", "learning": "अध्ययन केंद्र", "payments": "भुगतान", "news": "समाचार", "notifications": "सूचनाएँ", "people": "समुदाय", "settings": "सेटिंग्स", "discover": "खोजें", "setup": "शिक्षा कार्यक्षेत्र", "guide": "शुरुआत करें", "marketing": "मार्केटिंग", "teachers": "शिक्षक", "competition": "मासिक चुनौती", "quizzes": "प्रश्नोत्तरी", "results": "परिणाम और जीपीए", "live": "लाइव स्टूडियो"}

labels["ur"]={"dashboard": "جائزہ", "classrooms": "میری کلاسیں", "schedule": "میرا شیڈول", "learning": "تعلیمی مرکز", "payments": "ادائیگیاں", "news": "خبریں", "notifications": "اطلاعات", "people": "کمیونٹی", "settings": "ترتیبات", "discover": "دریافت کریں", "setup": "تعلیمی جگہ", "guide": "شروع کریں", "marketing": "مارکیٹنگ", "teachers": "اساتذہ", "competition": "ماہانہ چیلنج", "quizzes": "کوئز", "results": "نتائج اور جی پی اے", "live": "لائیو اسٹوڈیو"}

labels["zh"]={"dashboard": "概览", "classrooms": "我的课堂", "schedule": "我的课表", "learning": "学习中心", "payments": "付款", "news": "校园动态", "notifications": "通知", "people": "社区", "settings": "设置", "discover": "发现", "setup": "教育工作空间", "guide": "入门指南", "marketing": "营销中心", "teachers": "教师", "competition": "每月挑战", "quizzes": "测验", "results": "成绩与绩点", "live": "直播教室"}

labels["ja"]={"dashboard": "概要", "classrooms": "マイクラス", "schedule": "時間割", "learning": "学習センター", "payments": "支払い", "news": "お知らせ", "notifications": "通知", "people": "コミュニティ", "settings": "設定", "discover": "探す", "setup": "教育ワークスペース", "guide": "はじめに", "marketing": "マーケティング", "teachers": "講師", "competition": "月間チャレンジ", "quizzes": "クイズ", "results": "成績とGPA", "live": "ライブスタジオ"}

labels["ko"]={"dashboard": "개요", "classrooms": "내 수업", "schedule": "시간표", "learning": "학습 센터", "payments": "결제", "news": "소식", "notifications": "알림", "people": "커뮤니티", "settings": "설정", "discover": "둘러보기", "setup": "교육 공간", "guide": "시작하기", "marketing": "마케팅", "teachers": "교사", "competition": "월간 도전", "quizzes": "퀴즈", "results": "성적 및 학점", "live": "라이브 스튜디오"}

labels["tr"]={"dashboard": "Genel bakış", "classrooms": "Derslerim", "schedule": "Programım", "learning": "Öğrenme merkezi", "payments": "Ödemeler", "news": "Haberler", "notifications": "Bildirimler", "people": "Topluluk", "settings": "Ayarlar", "discover": "Keşfet", "setup": "Eğitim alanı", "guide": "Başlangıç", "marketing": "Pazarlama", "teachers": "Öğretmenler", "competition": "Aylık meydan okuma", "quizzes": "Kısa sınavlar", "results": "Sonuçlar ve ortalama", "live": "Canlı stüdyo"}

labels["id"]={"dashboard": "Ringkasan", "classrooms": "Kelas saya", "schedule": "Jadwal saya", "learning": "Pusat belajar", "payments": "Pembayaran", "news": "Berita", "notifications": "Notifikasi", "people": "Komunitas", "settings": "Pengaturan", "discover": "Jelajahi", "setup": "Ruang pendidikan", "guide": "Panduan awal", "marketing": "Pemasaran", "teachers": "Pengajar", "competition": "Tantangan bulanan", "quizzes": "Kuis", "results": "Hasil dan IPK", "live": "Studio langsung"}

labels["it"]={"dashboard": "Panoramica", "classrooms": "Le mie classi", "schedule": "Il mio orario", "learning": "Centro didattico", "payments": "Pagamenti", "news": "Novità", "notifications": "Notifiche", "people": "Comunità", "settings": "Impostazioni", "discover": "Esplora", "setup": "Spazio educativo", "guide": "Primi passi", "marketing": "Marketing", "teachers": "Docenti", "competition": "Sfida mensile", "quizzes": "Quiz", "results": "Risultati e media", "live": "Studio dal vivo"}

labels.en.videos='Video courses'
labels.ar.videos='دورات الفيديو'

Object.assign(labels.en,{study:"Study Space",plans:"Plans & add-ons"})
Object.assign(labels.ar,{study:"مساحة الدراسة",plans:"الخطط والإضافات"})
