<script setup>
import { computed } from 'vue'
import Icon from './Icon.vue'
import Art from './Art.vue'
import { lkr } from './rules'
const props=defineProps({data:Object,member:Object})
defineEmits(['navigate','room','create','video'])
const admin=computed(()=>props.member.role==='Admin')
const maxRevenue=computed(()=>Math.max(1,...props.data.revenue.map(r=>r.amount)))
</script>
<template>
  <div class="page-heading"><div><div class="eyebrow">{{admin?'YOUR INSTITUTE, AT A GLANCE':'A LITTLE INSPIRATION. A BIG DIFFERENCE.'}}</div><h1>{{admin?'A brighter campus starts here.':'Hello, '+member.full_name.split(' ')[0]+'.'}} <span class="greeting-spark">✺</span></h1><p>{{admin?'Students, teachers and every little milestone. Together in one place.':'Your classes, your community, your next chapter.'}}</p></div><button class="button primary" @click="$emit('create',admin?'member':'session')"><Icon :name="admin?'UserPlus':'Plus'" :size="17"/>{{admin?'Register a student':'Schedule a class'}}</button></div>
  <section class="insight-hero"><div><span class="hero-label">SISU LANKA · FICTIONAL DEMO ACADEMY</span><h2>{{admin?'Small steps.\nExtraordinary futures.':'Good teaching deserves\na bigger audience.'}}</h2><p>{{admin?'Five learning pathways. One connected community.':'Turn curiosity into your next classroom. Build a campaign, invite enquiries and welcome new learners.'}}</p><button class="button dark" @click="$emit('navigate',admin?'people':'marketing')">{{admin?'Meet your community':'Open marketing studio'}} <Icon name="ArrowRight" :size="16"/></button></div><Art/></section>
  <div class="insight-stats"><button @click="$emit('navigate','people')"><span class="stat-icon violet"><Icon name="Users"/></span><strong>{{data.totals.students}}</strong><small>{{admin?'Active students':'My students'}}</small></button><button @click="$emit('navigate',admin?'teachers':'classrooms')"><span class="stat-icon peach"><Icon name="GraduationCap"/></span><strong>{{admin?data.totals.teachers:data.totals.classes}}</strong><small>{{admin?'Registered teachers':'My classrooms'}}</small></button><button @click="$emit('navigate','payments')"><span class="stat-icon mint"><Icon name="Wallet"/></span><strong>{{lkr(data.totals.collected)}}</strong><small>Collected · {{data.month}}</small></button><button @click="$emit('navigate','competition')"><span class="stat-icon violet"><Icon name="Award"/></span><strong>{{data.totals.completion}}%</strong><small>This month’s learning completion</small></button></div>
  <div class="insight-grid"><section class="panel"><div class="section-heading"><div><h2>{{admin?'Learning across your campus':'Your classroom pulse'}}</h2><p>{{data.totals.classes}} classrooms · {{data.totals.progress}}% overall lesson completion</p></div><Icon name="BookOpen"/></div><div v-for="c in data.categories" :key="c.name" class="category-meter"><div><strong>{{c.name}}</strong><span>{{c.students}} students · {{c.classes}} classes</span></div><div class="meter-track"><i :style="{width:Math.max(4,c.students/data.totals.students*100)+'%'}"></i></div></div><button class="text-button" @click="$emit('navigate','classrooms')">Explore classrooms <Icon name="ArrowRight" :size="15"/></button></section>
  <section class="panel"><div class="section-heading"><div><h2>Payments, with perspective</h2><p>Six months of synthetic collections</p></div><Icon name="Receipt"/></div><div class="revenue-chart"><div v-for="r in data.revenue" :key="r.key"><span>{{Math.round(r.amount/1000)}}k</span><div class="revenue-track"><i :style="{height:Math.max(2,r.amount/maxRevenue*100)+'%'}"></i></div><small>{{r.label}}</small></div></div><div class="revenue-foot"><span><i class="preview-dot"></i> LKR collected</span><button class="text-button" @click="$emit('navigate','payments')">{{data.totals.overdue}} overdue invoices <Icon name="ArrowRight" :size="14"/></button></div></section></div>
  <div class="insight-grid"><section class="panel"><div class="section-heading"><div><h2>{{admin?'Teachers who make it happen':'Your next great class'}}</h2><p>{{admin?'Unique students per teacher; a learner may study with several teachers.':'Your classroom profiles, ready to share.'}}</p></div><button class="text-button" @click="$emit('navigate',admin?'teachers':'classrooms')">View all</button></div><template v-if="admin"><div v-for="(teacher,i) in data.teachers.slice(0,4)" :key="teacher.name" class="teacher-metric"><span class="teacher-avatar" :class="i%2?'peach':'violet'">{{teacher.full_name[0]}}</span><div><strong>{{teacher.full_name}}</strong><small>{{teacher.classes}} classes · {{teacher.students}} students</small></div><span>{{teacher.progress}}%<small>progress</small></span></div></template><template v-else><button v-for="r in data.rooms" :key="r.name" class="teacher-metric room-metric" @click="$emit('room',r)"><span class="stat-icon violet"><Icon name="BookOpen"/></span><div><strong>{{r.title}}</strong><small>{{r.category}} · {{r.students}} students</small></div><Icon name="ArrowUpRight"/></button></template></section>
  <section class="challenge-card"><span class="stat-icon white"><Icon name="Award" :size="28"/></span><span class="eyebrow">THIS MONTH’S LEARNING CHALLENGE</span><h2>A little practice.<br>A reason to celebrate.</h2><p>{{data.leaderboard.length}} demo learners · Quiz practice, lesson completion and attendance.</p><div class="podium-mini"><span v-for="s in data.leaderboard.slice(0,3)" :key="s.student"><b>#{{s.rank}}</b>{{s.alias}}<strong>{{s.score}} pts</strong></span></div><button class="button dark" @click="$emit('navigate','competition')">View monthly challenge <Icon name="ArrowRight" :size="16"/></button></section></div>
  <button class="video-teaser" @click="$emit('video')"><span class="video-play"><Icon name="Play" :size="24"/></span><div><span class="eyebrow">YOUR YOUTUBE EXAMPLE IS HERE</span><h3>Step inside the classroom.</h3><p>Play the supplied video right here in your LMS.</p></div><Icon name="ArrowUpRight"/></button>
</template>
