<script setup>
import {ref,onMounted} from 'vue'
import {call} from './service'
import Icon from './Icon.vue'
import HelpTip from './HelpTip.vue'
const props=defineProps({member:Object})
const emit=defineEmits(['notify'])
const data=ref(null),institute=ref('home'),code=ref(''),error=ref(''),busy=ref(false),issued=ref(null)
async function refresh(){data.value=await call('teacher_memberships')}
async function issue(){try{issued.value=await call('issue_teacher_invite',{provider:institute.value});await refresh()}catch(e){error.value=e.message}}
async function join(){error.value='';busy.value=true;try{await call('join_institute',{code:code.value});code.value='';await refresh();emit('notify','Join request submitted. Your institute must verify and approve the membership.')}catch(e){error.value=e.message}finally{busy.value=false}}
async function revoke(invite){try{await call('revoke_teacher_invite',{name:invite.name});await refresh();emit('notify','Unused invitation revoked.')}catch(e){error.value=e.message}}
onMounted(refresh)
</script>
<template><section v-if="data" class="panel membership-panel"><div class="section-heading"><div><span class="eyebrow">TEACH INDEPENDENTLY, OR AS PART OF A TEAM</span><h2>{{member.role==='Admin'?'Invite a teacher to your institute.':'Join your teaching institute.'}}</h2></div><Icon name="IdCard" :size="27"/></div><p>An institute code identifies the organisation. A private, one-use invitation code lets a teacher request membership. The institute then verifies and approves access. Each institute keeps its own teacher ID and permissions.</p><template v-if="member.role==='Admin'"><div class="form-row"><label>Institute<select v-model="institute"><option v-for="p in data.providers" :value="p.name">{{p.title}} · {{p.code}}</option></select></label><button class="button primary" @click="issue"><Icon name="UserPlus" :size="17"/>Create teacher invitation</button></div><div v-if="issued" class="issued-invite"><span class="eyebrow">SHARE PRIVATELY WITH YOUR TEACHER</span><code>{{issued.code}}</code><p>Expires {{issued.expires_at.slice(0,10)}} · one use · Teacher role only</p><small>Demo token is stored locally. Production must deliver invitations privately and store only a token hash.</small></div><article v-for="i in data.invites" class="teacher-metric"><span class="stat-icon violet"><Icon name="IdCard"/></span><div><strong>{{i.provider_code}} · {{i.status}}</strong><small>Expires {{i.expires_at.slice(0,10)}}</small></div><button v-if="i.status==='Active'" class="text-button" @click="revoke(i)">Revoke</button></article></template><template v-else-if="member.role==='Teacher'"><form @submit.prevent="join"><label>Private teacher invitation code <HelpTip text="Ask your institute admin for a teacher invitation. The public institute code alone is never sufficient to join. Invitations expire in seven days and can be used only once."/><input v-model="code" required placeholder="Paste the private code from your institute" autocomplete="off" maxlength="100"></label><button class="button primary" :disabled="busy">{{busy?'Joining…':'Request to join institute'}}</button></form><p class="field-help">Try the seeded demo invitation: <code>TA0051-DEMO-TEACHER</code>. This works only in the local preview, once.</p><article v-for="m in data.memberships" class="teacher-metric"><span class="stat-icon mint"><Icon name="Building2"/></span><div><strong>{{m.provider_title}}</strong><small>{{m.teacher_id}} · Teacher · {{m.status}}</small></div></article></template><p v-else class="field-help">Choose the Teacher preview account to join an institute, or Institute Admin to issue invitations.</p><p v-if="error" class="error" role="alert">{{error}}</p></section></template>
