<script setup>
import {computed,ref,onMounted,onBeforeUnmount} from 'vue'
import Icon from './Icon.vue'
import {locales,flagPath} from './locales'
const props=defineProps({modelValue:String})
const emit=defineEmits(['update:modelValue'])
const root=ref(null),open=ref(false),search=ref(''),custom=ref(''),error=ref('')
const selected=computed(()=>locales.find(l=>l.code===props.modelValue)||{native:props.modelValue,title:props.modelValue})
const filtered=computed(()=>locales.filter(l=>(l.native+' '+l.title+' '+l.code).toLowerCase().includes(search.value.toLowerCase())))
function pick(code){emit('update:modelValue',code);open.value=false;search.value='';error.value=''}
function add(){try{const tag=Intl.getCanonicalLocales(custom.value.trim())[0];if(!tag)throw Error();pick(tag)}catch{error.value='Enter a valid language tag, such as es-MX or ar-QA.'}}
function outside(e){if(!root.value?.contains(e.target))open.value=false}
onMounted(()=>document.addEventListener('pointerdown',outside));onBeforeUnmount(()=>document.removeEventListener('pointerdown',outside))
</script>
<template><div ref="root" class="locale-picker" @keydown.esc.stop="open=false"><button class="locale-trigger" aria-label="Choose interface language" :aria-expanded="open" @click="open=!open"><img v-if="selected.country" :src="flagPath(selected.country)" alt=""><Icon v-else name="Globe2" :size="17"/><span>{{selected.native}}</span><Icon name="ChevronDown" :size="13"/></button><section v-if="open" class="locale-menu" aria-label="Language options"><header><strong>Your language, your space.</strong><p>Flags identify regional examples, not everyone who speaks a language.</p></header><label class="search"><Icon name="Search" :size="16"/><input v-model="search" aria-label="Search languages" placeholder="Search languages…"></label><div class="locale-options"><button v-for="locale in filtered" :key="locale.code" :aria-pressed="modelValue===locale.code" @click="pick(locale.code)"><img :src="flagPath(locale.country)" alt=""><span><b>{{locale.native}}</b><small>{{locale.title}}</small></span><Icon v-if="modelValue===locale.code" name="Check" :size="16"/></button></div><details><summary>Another language or region</summary><label>Language tag<input v-model="custom" placeholder="es-MX, ar-QA…" maxlength="35"></label><button class="button subtle small" @click="add">Use this locale</button><p v-if="error" class="error">{{error}}</p></details><footer>Navigation translation coverage varies. English appears where a translation is not yet available; uploaded course content stays in its original language.</footer></section></div></template>
<style>.locale-picker{position:relative}.locale-trigger{border:0;background:none;display:flex;gap:8px;align-items:center;color:#81778f;font-size:12px;padding:9px 3px;cursor:pointer}.locale-trigger>span{max-width:100px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.locale-picker img{width:21px;height:15px;object-fit:cover;border-radius:3px;box-shadow:0 0 0 1px #0000000d}.locale-menu{position:absolute;top:42px;inset-inline-end:0;width:310px;max-width:calc(100vw - 24px);background:white;border:1px solid #e8e0ed;border-radius:18px;padding:16px;z-index:70;box-shadow:0 16px 55px #39234425;text-align:start}.locale-menu header strong{font-size:14px;color:#655173}.locale-menu p{font-size:10px;line-height:1.6;color:#95879f}.locale-menu .search input{min-width:0;width:100%;font-size:11px}.locale-options{max-height:285px;overflow:auto;margin-top:12px;scrollbar-width:thin}.locale-options button{display:flex;gap:12px;align-items:center;width:100%;border:0;background:white;text-align:start;padding:10px;border-radius:10px;color:#6c5b7c;cursor:pointer}.locale-options button:hover,.locale-options button[aria-pressed=true]{background:#f5effb}.locale-options button span{flex:1}.locale-options b{font-size:12px;font-weight:550}.locale-options small{display:block;color:#9b8da6;font-size:9px;margin-top:2px}.locale-menu footer{border-top:1px solid #eee7f2;padding-top:11px;margin-top:10px;font-size:9px;color:#9c8aa7;line-height:1.7}.locale-menu details{font-size:11px;padding-top:10px;color:#826c92}.locale-menu details input{display:block;width:100%;margin:8px 0;border:1px solid #dfd6e7;border-radius:8px;padding:8px}@media(max-width:500px){.locale-trigger span{max-width:70px}.locale-menu{position:fixed;top:65px;inset-inline-end:12px}}</style>
