<script setup>
import {computed,ref} from 'vue'
import Icon from './Icon.vue'
import {call} from './service'
import {dayKey,graphemes} from './rules'
const props=defineProps({data:Object})
const emit=defineEmits(['refresh','notify'])
const editing=ref(false),preview=ref(null),error=ref(''),saving=ref(false)
const form=ref({})
const leads=computed(()=>props.data.leads)
const total=key=>props.data.campaigns.reduce((s,c)=>s+Number(c[key]||0),0)
function create(){form.value={classroom:props.data.rooms[0]?.name,headline:'',description:'',cta_label:'Reserve a free trial',channel:'WhatsApp',starts_on:dayKey(),ends_on:dayKey(),code:'',color:'#e5e0ff'};editing.value=true;error.value=''}
async function save(){saving.value=true;try{await call('save_campaign',{data:form.value});editing.value=false;emit('refresh');emit('notify','Demo campaign saved. Nothing was published externally.')}catch(e){error.value=e.message}finally{saving.value=false}}
async function move(lead,status){try{await call('update_lead',{name:lead.name,status});emit('refresh')}catch(e){emit('notify',e.message)}}
async function copy(c){const room=props.data.rooms.find(r=>r.name===c.classroom);const text=`${c.headline}\n${room?.teacher_name} · ${room?.category}\n${c.description}\n${c.cta_label} · Reference ${c.code}\n${location.origin}/#marketing?campaign=${encodeURIComponent(c.name)}\nLocal demo link — not a public registration page.`;try{await navigator.clipboard.writeText(text);emit('notify','Promotional copy and local preview link copied.')}catch{emit('notify','Clipboard unavailable. Select the text in the campaign preview to copy.')}}
async function trial(c){try{await call('add_demo_lead',{campaign:c.name});emit('refresh');emit('notify','Demo trial enquiry added to the pipeline. No real registration or message sent.')}catch(e){emit('notify',e.message)}}
const room=c=>props.data.rooms.find(r=>r.name===c.classroom)
</script>
<template><div class="page-heading"><div><div class="eyebrow">YOUR TEACHING. A LITTLE MORE VISIBLE.</div><h1>Make room for new learners.</h1><p>Your teacher marketing studio · Campaigns, trial classes and enquiries.</p></div><button class="button primary" @click="create"><Icon name="Plus" :size="17"/>Create a campaign</button></div><div class="insight-stats"><div><span class="stat-icon violet"><Icon name="Megaphone"/></span><strong>{{data.campaigns.length}}</strong><small>Demo campaigns</small></div><div><span class="stat-icon peach"><Icon name="Users"/></span><strong>{{total('views').toLocaleString()}}</strong><small>Sample impressions</small></div><div><span class="stat-icon mint"><Icon name="ArrowUpRight"/></span><strong>{{total('clicks')}}</strong><small>Sample link clicks</small></div><div><span class="stat-icon violet"><Icon name="UserPlus"/></span><strong>{{leads.length}}</strong><small>Demo enquiries</small></div></div>
<section v-if="editing" class="panel campaign-editor"><div class="section-heading"><h2>A new reason to join your class</h2><button class="icon-button" aria-label="Close campaign editor" @click="editing=false"><Icon name="X"/></button></div><form @submit.prevent="save"><p v-if="error" class="error" role="alert">{{error}}</p><div class="form-row"><label>Classroom<select v-model="form.classroom" required><option v-for="r in data.rooms" :value="r.name">{{r.title}}</option></select></label><label>Promotional channel<select v-model="form.channel"><option>WhatsApp</option><option>Facebook</option><option>Referral</option><option>Instagram</option></select></label></div><label>Headline · {{graphemes(form.headline)}} / 80<input v-model="form.headline" required></label><label>Description · {{graphemes(form.description)}} / 240<textarea v-model="form.description" required></textarea></label><div class="form-row"><label>Start date<input v-model="form.starts_on" type="date" required></label><label>End date<input v-model="form.ends_on" type="date" :min="form.starts_on" required></label></div><div class="form-row"><label>Call to action<input v-model="form.cta_label" maxlength="24" required></label><label>Referral / trial code<input v-model="form.code" maxlength="24" placeholder="MATHSTRIAL" required pattern="[A-Za-z0-9_-]+"></label></div><p class="field-help">Saved in this browser only. Referral codes label enquiries; they do not change invoice amounts. Promotional image carousels are available under Campus updates.</p><button class="button primary" :disabled="saving">{{saving?'Saving…':'Save demo campaign'}}</button></form></section>
<div class="campaign-grid"><article v-for="c in data.campaigns" :key="c.name" class="campaign-card"><div class="campaign-art" :style="{background:c.color}"><span class="eyebrow">{{room(c)?.category}} · {{room(c)?.medium}}</span><h2>{{c.headline}}</h2><span class="campaign-star">✳</span><div class="teacher-line"><span class="teacher-avatar white">{{room(c)?.teacher_name?.[0]}}</span>{{room(c)?.teacher_name}}</div></div><div class="campaign-copy"><div class="inline spread"><span class="badge violet">{{c.channel}}</span><small>Auto-delete: {{new Date(new Date(c.published_at||c.starts_on).getTime()+30*86400000).toISOString().slice(0,10)}}</small></div><p>{{c.description}}</p><div class="campaign-counts"><span><b>{{c.views}}</b> views</span><span><b>{{c.clicks}}</b> clicks</span><span><b>{{leads.filter(l=>l.campaign===c.name).length}}</b> enquiries</span></div><div class="inline wrap"><button class="button primary small" @click="preview=c">Preview promotion</button><button class="button subtle small" @click="copy(c)">Copy share text</button></div></div></article></div><section v-if="!data.campaigns.length" class="panel empty-state"><Icon name="Megaphone"/><h2>Your story starts here.</h2><p>Create your first promotional card for a free trial or a new intake.</p></section>
<section class="panel lead-panel"><div class="section-heading"><div><h2>From a little curiosity to a new learner</h2><p>Sample enquiry pipeline · Changing a status does not create a paid enrollment.</p></div></div><div class="lead-board"><div v-for="status in ['New','Contacted','Trial booked','Enrolled']" :key="status"><h3>{{status}} <span class="count-pill">{{leads.filter(l=>l.status===status).length}}</span></h3><article v-for="l in leads.filter(l=>l.status===status).slice(0,8)" :key="l.name"><strong>{{l.alias}}</strong><small>{{l.source}} · {{l.creation}}</small><label>Stage<select :value="l.status" @change="move(l,$event.target.value)"><option>New</option><option>Contacted</option><option>Trial booked</option><option>Enrolled</option></select></label></article><small v-if="leads.filter(l=>l.status===status).length>8">Showing 8 of {{leads.filter(l=>l.status===status).length}} enquiries</small></div></div></section>
<div v-if="preview" class="promo-overlay" @click.self="preview=null" @keydown.esc="preview=null"><section class="promo-dialog" role="dialog" aria-modal="true" aria-label="Campaign preview" tabindex="-1"><button class="promo-close icon-button" aria-label="Close promotion" @click="preview=null"><Icon name="X"/></button><div class="promo-poster" :style="{background:preview.color}"><span class="eyebrow">SISU LANKA DEMO ACADEMY · {{room(preview)?.category}}</span><span class="promo-decoration">✳</span><h2>{{preview.headline}}</h2><p>{{preview.description}}</p><div class="teacher-line"><span class="teacher-avatar white">{{room(preview)?.teacher_name?.[0]}}</span>{{room(preview)?.teacher_name}}</div><div class="inline wrap"><span class="badge white">{{room(preview)?.medium}} medium</span><span class="badge white">{{room(preview)?.branch}}</span><span class="badge white">Ref: {{preview.code}}</span></div></div><div class="promo-footer"><div><strong>A small step towards your next chapter.</strong><small>Local preview · no external publishing or contact collection.</small></div><button class="button primary" @click="trial(preview)">{{preview.cta_label}} <Icon name="ArrowRight" :size="16"/></button></div></section></div>
</template>
