<script setup>
import {computed,ref,onMounted,onBeforeUnmount,nextTick} from 'vue'
import Icon from './Icon.vue'
import Art from './Art.vue'
const props=defineProps({role:String,demo:Boolean})
const emit=defineEmits(['close','navigate'])
const step=ref(0),box=ref(null),dialog=ref(null)
const steps=computed(()=>[
 {title:'A little tour. A confident start.',body:'Welcome to your '+props.role.toLowerCase()+' workspace. Let’s find the things you’ll use every day.',icon:'Sprout',page:'dashboard',hint:'Built for institutes and independent teachers. Choose your country, education system and teaching languages when setting up your workspace.'},
 {title:props.role==='Admin'?'Your whole institute, together.':props.role==='Teacher'?'Your teaching day, organised.':'Your next lesson is right here.',body:props.role==='Admin'?'See active learners, teachers, course categories, collections and progress. Open a card to explore its records.':props.role==='Teacher'?'Find your own classrooms and students. Keep an eye on learning progress and plan the next session.':'Start with your timetable, learning progress and enrolled classrooms. Your exam countdown keeps the next milestone in view.',icon:'LayoutDashboard',page:'dashboard',target:'.page-heading',hint:props.demo?'All people, payments and results in this preview are synthetic.':'Your account permissions determine what you can see.'},
 {title:'A home for every classroom.',body:props.role==='Student'?'Open a classroom to find sessions, recordings, materials and teacher announcements. A payment or access rule may need to be settled first.':'Create a classroom profile with a title, teacher, cover image and teaching language. Set exam dates and a short motivation line.',icon:'BookOpen',page:'classrooms',target:'.page-heading',hint:'Classroom titles support English, සිංහල and தமிழ். Motivation lines allow up to 30 visible characters.'},
 {title:'The right class. The right time.',body:props.role==='Student'?'Choose a day to see your physical and online classes. Open the classroom to join an available YouTube session.':'Schedule physical or online sessions and attach a YouTube video. Class updates can queue notifications for opted-in learners.',icon:'CalendarDays',page:'schedule',target:'.page-heading',hint:'Times are shown in Asia/Colombo. YouTube channel and video restrictions still apply.'},
 {title:'Clear fees. Fewer surprises.',body:props.role==='Student'?'Check paid, unpaid and overdue installments. A verified payment updates classroom access and creates a receipt.':'Review collections, outstanding installments and payment history. Grace periods and manual overrides keep exceptional cases manageable.',icon:'Wallet',page:'payments',target:'.payment-summary',hint:'payments.lk is the planned primary gateway. Merchant setup and sandbox verification are required; the demo collects no money.'},
 ...(props.demo&&props.role!=='Student'?[{title:'Help the right learners find you.',body:'Create a promotional card, preview a free-trial offer, copy share text and organise enquiries by stage. Campus updates supports image carousels.',icon:'Megaphone',page:'marketing',target:'.page-heading',hint:'Preview campaigns stay in this browser. No marketing messages are sent automatically.'}]:[{title:'Stay connected to your campus.',body:'Browse new intakes, teacher announcements and campus opportunities. Your notification preferences stay under your control in Settings.',icon:'Newspaper',page:'news',target:'.page-heading',hint:'Class updates and promotional communication should use separate consent preferences.'}]),
 {title:'You’re ready for your next chapter.',body:'You can replay this tour anytime from the top bar. Visit Getting started for short walkthroughs tailored to your role.',icon:'CircleCheck',page:'dashboard',hint:'Use Tab to move between controls, Enter to activate them, and Escape to close dialogs.'}
])
const current=computed(()=>steps.value[step.value])
function measure(){const el=current.value.target?document.querySelector(current.value.target):null;const r=el?.getBoundingClientRect();box.value=r&&r.width?{left:r.left-7,top:r.top-7,width:r.width+14,height:r.height+14}:null}
async function show(n){step.value=n;emit('navigate',current.value.page);await nextTick();await nextTick();document.querySelector(current.value.target||'main')?.scrollIntoView({block:'start',behavior:'instant'});measure();dialog.value?.focus()}
function key(e){if(e.key==='Escape')emit('close');if(e.key==='Tab'){const items=[...dialog.value.querySelectorAll('button')].filter(x=>!x.disabled),first=items[0],last=items.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===dialog.value)){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}
let previousFocus,oldOverflow
onMounted(()=>{previousFocus=document.activeElement;oldOverflow=document.body.style.overflow;document.body.style.overflow='hidden';document.querySelector('.app-shell')?.setAttribute('inert','');window.addEventListener('resize',measure);show(0)})
onBeforeUnmount(()=>{document.querySelector('.app-shell')?.removeAttribute('inert');document.body.style.overflow=oldOverflow;window.removeEventListener('resize',measure);previousFocus?.focus()})
</script>
<template><Teleport to="body"><div class="tour-overlay" @keydown="key"><div v-if="box" class="tour-highlight" :style="{left:box.left+'px',top:box.top+'px',width:box.width+'px',height:box.height+'px'}"></div><section ref="dialog" class="tour-dialog" :class="{welcome:step===0||step===steps.length-1}" role="dialog" aria-modal="true" aria-labelledby="tour-title" aria-describedby="tour-body" tabindex="-1"><div class="tour-top"><span class="eyebrow">YOUR {{role.toUpperCase()}} PRODUCT TOUR</span><button class="icon-button" aria-label="Close product tour" @click="$emit('close')"><Icon name="X"/></button></div><div v-if="step===0||step===steps.length-1" class="tour-art"><Art/></div><span v-else class="stat-icon violet"><Icon :name="current.icon" :size="25"/></span><h2 id="tour-title">{{current.title}}</h2><p id="tour-body">{{current.body}}</p><div class="tour-hint"><Icon name="Globe2" :size="18"/><span>{{current.hint}}</span></div><div class="tour-progress" aria-live="polite"><div><i v-for="(_,i) in steps" :class="{done:i<=step}"></i></div><span>Step {{step+1}} of {{steps.length}}</span></div><div class="tour-footer"><button class="text-button" @click="$emit('close')">Skip tour</button><div class="inline"><button class="button subtle" :disabled="step===0" @click="show(step-1)">Back</button><button class="button primary" @click="step===steps.length-1?$emit('close'):show(step+1)">{{step===steps.length-1?'Let’s get started':step===0?'Show me around':'Next'}}<Icon name="ArrowRight" :size="16"/></button></div></div></section></div></Teleport></template>
