<script setup>
import {computed,ref,onMounted} from 'vue'
import Icon from './Icon.vue'
import {call} from './service'
const props=defineProps({rooms:Array,member:Object})
const emit=defineEmits(['notify'])
const state=ref(null),room=ref(props.rooms[0]?.name||''),lesson=ref(''),title=ref('A little practice after your lesson'),questions=ref([{kind:'True / False',prompt:'',options:['True','False'],answer:0}]),busy=ref(false),error=ref('')
const manager=computed(()=>props.member.role!=='Student')
const lessons=computed(()=>state.value?.sessions.filter(s=>s.classroom===room.value)||[])
async function refresh(){state.value=await call('quiz_workspace');if(!lesson.value||!lessons.value.some(s=>s.name===lesson.value))lesson.value=lessons.value[0]?.name||''}
async function unlock(){try{await call('quiz_unlock');await refresh();emit('notify','Demo AI Quiz entitlement unlocked. No charge made; no AI provider was called.')}catch(e){emit('notify',e.message)}}
async function publish(){error.value='';busy.value=true;try{await call('save_manual_quiz',{data:{classroom:room.value,session:lesson.value,title:title.value,questions:questions.value}});emit('notify','Manual lesson quiz published.');questions.value=[{kind:'True / False',prompt:'',options:['True','False'],answer:0}];await refresh()}catch(e){error.value=e.message}finally{busy.value=false}}
function changeKind(q){q.options=q.kind==='True / False'?['True','False']:['','','',''];q.answer=0}
onMounted(refresh)
</script>
<template><div class="page-heading"><div><div class="eyebrow">A LITTLE PRACTICE MAKES LEARNING STICK</div><h1>Lesson quizzes.</h1><p>Keep it simple. Check understanding after every lesson.</p></div></div><template v-if="state"><section v-if="manager" class="quiz-upgrade"><Icon name="ClipboardCheck" :size="30"/><div><span class="badge peach">Coming soon</span><h2>AI-assisted quizzes</h2><p>AI generation is planned for a later release. Create your own questions below.</p></div></section>
<div v-if="manager" class="quiz-layout"><section class="panel quiz-editor"><span class="eyebrow">MANUAL QUIZZES · ALWAYS AVAILABLE</span><h2>Check what clicked.</h2><form @submit.prevent="publish"><p v-if="error" class="error" role="alert">{{error}}</p><label>Classroom<select v-model="room" @change="lesson=lessons[0]?.name||''"><option v-for="r in rooms" :value="r.name">{{r.title}}</option></select></label><label>Lesson<select v-model="lesson" required><option v-for="s in lessons" :value="s.name">{{s.title}}</option></select></label><label>Quiz title<input v-model="title" required maxlength="100"></label><div v-for="(q,i) in questions" :key="i" class="quiz-question-editor"><div class="inline spread"><h3>Question {{i+1}}</h3><button v-if="questions.length>1" type="button" class="icon-button" :aria-label="'Remove question '+(i+1)" @click="questions.splice(i,1)"><Icon name="X" :size="16"/></button></div><label>Question type<select v-model="q.kind" @change="changeKind(q)"><option>True / False</option><option>Multiple choice</option></select></label><label>Question<input v-model="q.prompt" required maxlength="300" placeholder="What should your students remember?"></label><div v-if="q.kind==='Multiple choice'" class="form-row"><label v-for="(_,j) in q.options">Option {{j+1}}<input v-model="q.options[j]" maxlength="150" required></label></div><label>Correct answer<select v-model.number="q.answer"><option v-for="(option,j) in q.options" :value="j">{{option||'Option '+(j+1)}}</option></select></label></div><button v-if="questions.length<10" type="button" class="button subtle" @click="questions.push({kind:'True / False',prompt:'',options:['True','False'],answer:0})"><Icon name="Plus" :size="16"/>Add question</button><button class="button primary" :disabled="busy||!lesson">{{busy?'Publishing…':'Publish manual quiz'}}</button></form></section><aside class="panel"><h2>Your published quizzes</h2><article v-for="q in state.quizzes" class="teacher-metric"><span class="stat-icon mint"><Icon name="ClipboardCheck"/></span><div><strong>{{q.title}}</strong><small>{{q.questions.length}} questions · {{q.source}}</small></div></article><p v-if="!state.quizzes.length">No manual quizzes yet. Create a short check-in for your next lesson.</p><p class="field-help">Publishing a new quiz for the same lesson replaces the draft shown to future attempts. Existing submitted scores keep their original quiz snapshot.</p></aside></div>
<section v-else class="panel"><h2>Finish a lesson. Try a little practice.</h2><p>Open an enrolled classroom, choose a completed lesson, and select “Complete lesson & open quiz”. Your teacher’s manual quiz takes priority. AI-generated quizzes are coming soon.</p><h3>Your attempts</h3><article v-for="a in state.attempts" class="teacher-metric"><span class="stat-icon mint"><Icon name="Award"/></span><div><strong>{{a.title}}</strong><small>{{a.correct}} / {{a.total}} correct · {{a.source}}</small></div><strong>{{a.score}}%</strong></article><p v-if="!state.attempts.length" class="field-help">Your first completed quiz will appear here.</p></section></template></template>
