<script setup>
import {onMounted,ref} from 'vue'
import {call,isDemo} from './service'
import SoulPet from './SoulPet.vue'
const data=ref({enabled:false,configured:false,model:'gpt-4.1-mini'}),key=ref(''),busy=ref(false),notice=ref(''),error=ref('')
async function refresh(){if(!isDemo)data.value=await call('status',{},'soul')}
async function save(remove=false){busy.value=true;error.value='';notice.value='';try{if(isDemo){notice.value='Preview only. Keys cannot be saved in this browser demo.';return}await call('configure',{api_key:key.value||null,model:data.value.model,enabled:!!data.value.enabled,remove_key:remove},'soul');key.value='';await refresh();notice.value=remove?'OpenAI key removed. Guided help remains available.':'SOUL settings saved securely on this institute site.'}catch(e){error.value=e.message}finally{busy.value=false}}
async function test(){busy.value=true;error.value='';try{await call('test_connection',{},'soul');notice.value='OpenAI model and moderation connection verified.'}catch(e){error.value=e.message}finally{busy.value=false}}
onMounted(()=>refresh().catch(e=>error.value=e.message))
</script>
<template><section class="panel soul-settings"><div class="section-heading"><div><span class="eyebrow">A SMALL COMPANION. A THOUGHTFUL CONNECTION.</span><h2>Meet SOUL · OpenAI connection</h2><p>Your animated LMS guide, with optional AI chat.</p></div><div style="width:82px;height:90px"><SoulPet/></div></div><p v-if="isDemo" class="form-note">This local preview uses prepared guidance. Paste your key only on the installed HTTPS Frappe site; this demo does not accept or save secrets.</p><p v-if="error" class="error" role="alert">{{error}}</p><p v-if="notice" class="form-note" role="status">{{notice}}</p><form @submit.prevent="save(false)"><div class="form-row"><label>OpenAI API key<input v-model="key" type="password" autocomplete="new-password" :disabled="isDemo" :placeholder="data.configured?'A key is stored. Leave blank to keep it.':'sk-…'" maxlength="512"><small>Encrypted using Frappe’s Password field. Never returned to the browser.</small></label><label>OpenAI model<input v-model="data.model" maxlength="80" placeholder="gpt-4.1-mini" :disabled="isDemo"><small>Use a text model available in your OpenAI project.</small></label></div><label class="checkbox-label"><input v-model="data.enabled" type="checkbox" :disabled="isDemo">Enable OpenAI chat for eligible accounts</label><div class="inline wrap"><button class="button primary" :disabled="isDemo||busy">Save connection</button><button type="button" class="button subtle" :disabled="isDemo||busy||!data.configured" @click="test">Test connection · small API request</button><button type="button" class="text-button" :disabled="isDemo||busy||!data.configured" @click="save(true)">Remove stored key</button></div></form><p class="field-help">Guided help works without OpenAI. AI receives only messages, recent conversation, role, language and the page name. No grades, invoices, teacher records, cameras or screen captures are shared automatically.</p><p class="field-help">Student AI access starts disabled. Your deployment operator must complete the age/consent and child-safety review, verify Zero Data Retention for the project, and approve each eligible learner. Ordinary navigation help remains available to every learner. No classroom tutoring, AI course creation or automatic account actions are included.</p></section></template>
<style scoped>.soul-settings{margin-top:24px}.soul-settings h2{margin-top:9px}.soul-settings label{display:block;font-size:12px;margin:15px 0;color:#746681}.soul-settings input:not([type=checkbox]){display:block;width:100%;border:1px solid #e4dcea;border-radius:10px;padding:12px;margin:8px 0;background:#fff}.soul-settings small{font-size:10px;line-height:1.6;display:block}.soul-settings .checkbox-label{display:flex;align-items:center;gap:8px}.soul-settings input:disabled{background:#f7f4fa}.soul-settings .field-help{max-width:850px;line-height:1.9}</style>
