export const soulPages={study:'Your pace matters. Let’s make space for a pause.',plans:'Optional extras. Your learning comes first.',videos:'Your own pace. One lesson at a time.',dashboard:'Your learning, one small step at a time.',classrooms:'Your next little discovery is waiting.',schedule:'A little planning leaves room to breathe.',payments:'Let’s find the right payment information.',discover:'So many ways to grow. Find your people.',results:'Progress is bigger than a single number.',quizzes:'Take your time. You can do one step at a time.',live:'Settle in. Your classroom is right here.',setup:'A lovely home for your teaching community.'}
export const soulCopy={en:{hello:'A little help. A little heart.',intro:'Hi, I’m SOUL.',body:'Your little guide to this learning space. Where shall we go?',placeholder:'Ask about using your LMS…',send:'Send',chat:'Chat with SOUL',guide:'Guided help',thinking:'Thinking it through…'},ar:{hello:'مساعدة صغيرة، باهتمام كبير',intro:'مرحباً، أنا SOUL',body:'دليلك الصغير في مساحة التعلم. إلى أين نذهب؟',placeholder:'اسأل عن استخدام المنصة…',send:'إرسال',chat:'تحدث مع SOUL',guide:'مساعدة إرشادية',thinking:'أفكر في سؤالك…'}}
export function guidedReply(message,page){
 const m=message.toLowerCase()
 if(/video course|recorded course|self.paced/.test(m))return {text:'Open Video courses, choose a course, and enroll. Free courses open immediately. Paid courses open after the required payment. Follow the module outline and mark each lesson complete.',route:'videos',label:'Explore video courses'}
 if(/pay|invoice|fee|unlock/.test(m))return {text:'Open Payments to check your invoices and deadlines. If a paid class stays locked, contact your institute with the invoice reference. I cannot change payments or access.',route:'payments',label:'Open payments'}
 if(/enrol|teacher|institute|discover/.test(m))return {text:'Open Discover, choose an institute or teacher, then select your class and Enroll. Each provider keeps its own classes and payments.',route:'discover',label:'Explore providers'}
 if(/password|reset|sign.in/.test(m))return {text:'Use Forgot password on the sign-in page. A reset link goes to your account email. Never share your password or reset link with me.'}
 if(/quiz|lesson|class|video/.test(m))return {text:'Open My classrooms, choose a class, and look in Sessions or Materials. Completed lessons may include a teacher’s quiz. YouTube playback follows the video owner’s privacy settings.',route:'classrooms',label:'Find my classrooms'}
 if(/gpa|grade|result/.test(m))return {text:'Your published results are available in Results & GPA. The optional calculator helps explore credit-weighted scenarios, using your institute’s grading rules.',route:'results',label:'See results'}
 if(/sad|stress|worried|break|tired/.test(m))return {text:'It is okay to pause. Take a little break, and talk with your teacher or a trusted adult if something is worrying you. Your learning can wait a moment.'}
 return {text:'I can help you find classrooms, payments, results or your schedule. This is guided help with prepared answers. Try a shortcut below, or open the product tour.',route:page==='schedule'?'schedule':'guide',label:page==='schedule'?'Open schedule':'Getting started'}
}
