<script setup>
import {ref} from 'vue'
import Icon from './Icon.vue'
import {isDemo} from './service'
import {palettes,readAppearance,saveAppearance} from './study/appearance'
const props=defineProps({member:Object})
const emit=defineEmits(['notify','study'])
const form=ref(readAppearance(props.member.name,isDemo))
function save(){saveAppearance(props.member.name,form.value);emit('notify','Your cozy profile style is saved in this browser.')}
</script>
<template><section class="panel student-appearance"><span class="eyebrow">WELCOME TO YOUR LITTLE CORNER</span><h2>Make your profile feel like you.</h2><p>Cozy is your default. Choose the light and colors that help you feel at home.</p><div class="appearance-modes"><button v-for="m in [{id:'cozy',name:'Cozy daylight',icon:'Coffee'},{id:'dark',name:'Cozy moonlight',icon:'Moon'}]" :class="m.id" :aria-pressed="form.mode===m.id" @click="form.mode=m.id"><Icon :name="m.icon" :size="24"/><strong>{{m.name}}</strong><small>{{m.id==='cozy'?'Warm paper, gentle lavender':'Soft plum, warm low light'}}</small></button></div><h3>Your accent color <span class="badge violet">Study Plus</span></h3><div class="appearance-swatches"><button v-for="p in palettes" :style="{'--swatch':p.color}" :aria-pressed="form.accent===p.id" :aria-label="p.title+' profile color'" @click="form.plus||p.id==='lavender'?form.accent=p.id:$emit('study')"><span></span>{{p.title}}<Icon v-if="!form.plus&&p.id!=='lavender'" name="LockKeyhole" :size="11"/></button></div><p class="field-help">Light and dark modes are free. Extra accent colors are part of the optional Study Plus subscription. Preference is personal; institute branding stays recognizable.</p><button class="button primary" @click="save">Save profile style</button></section></template>
<style>.student-appearance{margin:22px 0}.student-appearance>p{font-size:12px;line-height:1.8}.student-appearance h2{margin:12px 0}.appearance-modes{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin:20px 0}.appearance-modes>button{display:flex;flex-direction:column;gap:9px;align-items:flex-start;border:2px solid transparent;border-radius:17px;padding:22px;background:#f6eee8;color:#735c73;cursor:pointer}.appearance-modes>button.dark{background:#302936;color:#e8d6e3}.appearance-modes>button[aria-pressed=true]{border-color:#aa87bf}.appearance-modes strong{font-size:14px}.appearance-modes small{font-size:10px;color:inherit}.appearance-swatches{display:flex;gap:9px;flex-wrap:wrap;margin:16px 0}.appearance-swatches>button{display:flex;gap:7px;align-items:center;padding:10px;border:1px solid #d9c9df;border-radius:10px;background:transparent;color:inherit;cursor:pointer;font-size:11px}.appearance-swatches span{background:var(--swatch);width:16px;height:16px;border-radius:50%}.appearance-swatches>button[aria-pressed=true]{outline:2px solid var(--swatch);outline-offset:2px}.student-appearance h3{font-size:13px}.student-appearance h3 span{margin-inline-start:7px}@media(max-width:500px){.appearance-modes{grid-template-columns:1fr}}</style>
