<script setup>
import {computed,ref} from 'vue'
import Icon from './Icon.vue'
import Art from './Art.vue'
import {remaining} from './rules'
const props=defineProps({data:Object,marketplace:Object,rooms:Array,sessions:Array,invoices:Array,member:Object,institute:Object})
const emit=defineEmits(['navigate','room','marketclass','video'])
const space=ref('all')
const providers=computed(()=>[{name:'home',title:props.institute.title,code:props.institute.code,color:'#e5def9',count:props.rooms.length},...props.marketplace.providers.filter(p=>props.marketplace.enrollments.some(e=>e.provider===p.name)).map(p=>({...p,count:props.marketplace.enrollments.filter(e=>e.provider===p.name).length}))])
const nativeRooms=computed(()=>['all','home'].includes(space.value)?props.rooms:[])
const external=computed(()=>props.marketplace.enrollments.filter(e=>space.value==='all'||e.provider===space.value).map(e=>({...props.marketplace.classes.find(c=>c.name===e.classroom),enrollment:e,providerInfo:props.marketplace.providers.find(p=>p.name===e.provider)})))
const balances=computed(()=>{const result={};const add=(currency,amount)=>result[currency]=(result[currency]||0)+Number(amount);if(['all','home'].includes(space.value))props.invoices.filter(i=>i.status!=='Paid').forEach(i=>add('LKR',i.amount));external.value.filter(c=>c.enrollment.status!=='Paid').forEach(c=>add(c.currency,c.fee));return Object.entries(result)})
const upcoming=computed(()=>['all','home'].includes(space.value)?props.sessions.filter(s=>new Date(s.ends_at.replace(' ','T')+'+05:30')>new Date()).sort((a,b)=>a.starts_at.localeCompare(b.starts_at)).slice(0,3):[])
const money=(value,currency)=>new Intl.NumberFormat('en',{style:'currency',currency,maximumFractionDigits:0}).format(value)
</script>
<template><div class="page-heading"><div><div class="eyebrow">MANY PLACES TO LEARN. ONE PLACE TO BELONG.</div><h1>Hello, {{member.full_name.split(' ')[0]}} <span class="greeting-spark">✺</span></h1><p>Your classes, across every institute and teacher. All together, all yours.</p></div><button class="button primary" @click="$emit('navigate','discover')"><Icon name="Search" :size="16"/>Find a new class</button></div><section class="student-home-hero"><div><span class="eyebrow">YOUR LEARNING HOME</span><h2>Different teachers.<br>One extraordinary you.</h2><p>{{providers.length}} learning {{providers.length===1?'space':'spaces'}} · {{rooms.length+marketplace.enrollments.length}} enrolled classes</p><button class="button dark" @click="$emit('video')"><Icon name="Play" :size="16"/>Watch classroom video</button></div><Art/></section>
<div class="learning-space-heading"><div><h2>Your learning spaces</h2><p>Focus on one provider, or bring every class together.</p></div><button class="text-button" @click="$emit('navigate','discover')">+ Add a learning space</button></div><div class="learning-spaces" role="group" aria-label="Filter learning provider"><button :class="{chosen:space==='all'}" @click="space='all'"><span class="space-symbol"><Icon name="Globe2"/></span><span><b>All learning spaces</b><small>{{providers.length}} providers · one overview</small></span></button><button v-for="p in providers" :key="p.name" :class="{chosen:space===p.name}" @click="space=p.name"><span class="space-symbol" :style="{background:p.color}">{{p.code.slice(0,2)}}</span><span><b>{{p.title}}</b><small>{{p.count}} classes · {{p.code}}</small></span></button></div>
<div class="student-home-grid"><div><div class="section-heading"><h2>Ready for your next little step?</h2><span class="count-pill">{{nativeRooms.length+external.length}} classes</span></div><div class="student-class-grid"><article v-for="(r,i) in nativeRooms" :key="r.name" class="room-card"><button class="student-class-cover" :class="r.color" @click="$emit('room',r)"><span class="badge white">{{institute.code}} · {{r.tag}}</span><strong>{{r.subject==='Combined Mathematics'?'ƒ(x)':r.subject==='Physics'?'⚛':'✳'}}</strong></button><div class="room-body"><small class="provider-handle">{{institute.title}}</small><button class="room-title" :class="r.font" @click="$emit('room',r)">{{r.title}}</button><div class="teacher-line"><span class="teacher-avatar">{{r.teacher_name?.[0]}}</span>{{r.teacher_name}}</div><div class="room-card-footer"><span class="badge" :class="r.access.allowed?'green':'amber'">{{r.access.allowed?'Ready to learn':'Payment required'}}</span><button class="arrow-button" :aria-label="'Open '+r.title" @click="$emit('room',r)"><Icon name="ArrowRight" :size="17"/></button></div></div></article><article v-for="c in external" :key="c.name" class="room-card"><button class="student-class-cover" :style="{background:c.providerInfo.color}" @click="$emit('marketclass',c.name)"><span class="badge white">{{c.providerInfo.code}} · {{c.level}}</span><strong>✳</strong></button><div class="room-body"><small class="provider-handle">{{c.providerInfo.title}}</small><button class="room-title" @click="$emit('marketclass',c.name)">{{c.title}}</button><div class="teacher-line"><span class="teacher-avatar">{{c.teacher[0]}}</span>{{c.teacher}}</div><div class="room-card-footer"><span class="badge" :class="c.enrollment.status==='Paid'?'green':'amber'">{{c.enrollment.status==='Paid'?'Ready to learn':'Payment required'}}</span><button class="arrow-button" :aria-label="'Open '+c.title" @click="$emit('marketclass',c.name)"><Icon name="ArrowRight" :size="17"/></button></div></div></article></div>
<section v-if="nativeRooms.length" class="panel student-progress"><div class="section-heading"><h3>One lesson closer.</h3><button class="text-button" @click="$emit('navigate','quizzes')">My quiz attempts <Icon name="ArrowRight" :size="14"/></button></div><div v-for="p in data.progress" class="category-meter"><div><strong>{{p.subject}}</strong><span>{{p.completed}} / {{p.total}} lessons</span></div><div class="meter-track"><i :style="{width:p.completed/p.total*100+'%'}"></i></div></div></section></div>
<aside><section class="panel"><span class="eyebrow">NEXT ON YOUR TIMETABLE</span><article v-for="s in upcoming" class="home-agenda"><small>{{s.starts_at.slice(0,10)}} · {{s.starts_at.slice(11,16)}} · Asia/Colombo</small><h3>{{s.title}}</h3><p>{{institute.code}} · {{s.mode}}</p><button class="text-button" @click="$emit('room',rooms.find(r=>r.name===s.classroom))">Open classroom <Icon name="ArrowRight" :size="14"/></button></article><p v-if="!upcoming.length" class="field-help">No upcoming sessions are published for this view.</p><p v-if="external.length" class="field-help">Your newly selected providers will appear here when they publish session dates. Their local time zone will be shown with each session.</p></section><section class="panel home-balances"><div class="section-heading"><h3>Your class fees</h3><Icon name="Wallet" :size="20"/></div><div v-for="[currency,value] in balances" class="balance-row"><span>{{currency}}</span><strong>{{money(value,currency)}}</strong></div><p v-if="!balances.length">You’re all caught up.</p><p class="field-help">See receipts, total spending and upcoming class payments in Class fees.</p><button class="text-button" @click="$emit('navigate',space==='home'||space==='all'?'payments':'discover')">View class fees <Icon name="ArrowRight" :size="14"/></button></section><section v-if="nativeRooms.find(r=>r.exam_date)" class="exam-card"><span class="eyebrow">YOUR NEXT BIG CHAPTER</span><div class="countdown">{{remaining(nativeRooms.find(r=>r.exam_date).exam_date)}}<span>days to go</span></div><p>{{nativeRooms.find(r=>r.exam_date).subject}} · Demo exam date</p><strong>{{nativeRooms.find(r=>r.exam_date).motivation}}</strong></section></aside></div></template>
