<script setup>
import {computed,ref,onMounted} from 'vue'
import {call} from './service'
import Icon from './Icon.vue'
const props=defineProps({member:Object,institute:Object,rooms:Array,marketplace:Object})
defineEmits(['room','profile','setup'])
const memberships=ref([]),selected=ref('all')
onMounted(async()=>memberships.value=(await call('teacher_memberships')).memberships)
const spaces=computed(()=>[{name:'home',title:props.institute.title,code:props.institute.code,type:'Institute teacher',classes:props.rooms.map(r=>({...r,internal:true}))},...props.marketplace.providers.filter(p=>p.owner===props.member.name||memberships.value.some(m=>m.provider===p.name&&m.status==='Active')).map(p=>({...p,type:p.type==='Independent teacher'?'Independent teacher':'Institute teacher',classes:props.marketplace.classes.filter(c=>c.provider===p.name&&c.teacher_account===props.member.name)}))])
const shown=computed(()=>spaces.value.filter(s=>selected.value==='all'||s.name===selected.value))
</script>
<template><section class="teaching-spaces"><div class="section-heading"><div><span class="eyebrow">ONE TEACHER IDENTITY. SEVERAL PLACES TO MAKE A DIFFERENCE.</span><h2>Your teaching spaces</h2><p>Independent classes and institute assignments stay separately organised.</p></div><button class="text-button" @click="$emit('setup')">Join another institute <Icon name="ArrowRight" :size="15"/></button></div><div class="learning-spaces"><button :class="{chosen:selected==='all'}" @click="selected='all'"><span class="space-symbol"><Icon name="Globe2"/></span><span><b>All teaching spaces</b><small>{{spaces.length}} workspaces</small></span></button><button v-for="s in spaces" :key="s.name" :class="{chosen:selected===s.name}" @click="selected=s.name"><span class="space-symbol">{{s.code.slice(0,2)}}</span><span><b>{{s.title}}</b><small>{{s.type}} · {{s.classes.length}} classes</small></span></button></div><div class="teaching-space-grid"><section v-for="s in shown" :key="s.name" class="panel"><div class="section-heading"><div><span class="badge violet">{{s.type}}</span><h3>{{s.title}}</h3></div><span class="eyebrow">{{s.code}}</span></div><article v-for="c in s.classes" :key="c.name" class="teacher-metric"><span class="stat-icon mint"><Icon name="BookOpen"/></span><div><strong>{{c.title}}</strong><small>{{c.duration_months?c.duration_months+' month course':c.category||c.level}} · {{c.medium}}</small><small v-if="c.schedule">{{c.schedule}}</small></div><button class="text-button" @click="c.internal?$emit('room',c):$emit('profile',s.name)">{{c.internal?'Open':'View listing'}} <Icon name="ArrowRight" :size="14"/></button></article><p v-if="!s.classes.length" class="field-help">Membership is active. This institute has not assigned you a course in the demo yet.</p></section></div><p class="field-help">Each institute controls its own enrollments, prices and access. Institute membership grants no rights in another workspace. Your personal teaching profile remains independent.</p></section></template>
