<script setup>
import {computed,ref,onMounted} from 'vue'
import {call} from './service'
import Icon from './Icon.vue'
import HelpTip from './HelpTip.vue'
import LessonQuiz from './LessonQuiz.vue'
const props=defineProps({member:Object,teachers:Array})
const emit=defineEmits(['notify','payments','quizzes','refresh'])
const data=ref(null),selected=ref(null),lesson=ref(null),creating=ref(false),busy=ref(false),error=ref(''),query=ref('')
const form=ref({title:'',description:'',medium:'English',fee:0,teacher:props.member.role==='Teacher'?props.member.name:props.teachers[0]?.name,lessons:[{module:'Getting started',title:'Welcome to the course',url:'',description:''}]})
const courses=computed(()=>data.value?.courses.filter(c=>(c.title+' '+c.subject+' '+c.teacher_name).toLowerCase().includes(query.value.toLowerCase()))||[])
const completed=computed(()=>data.value?.completions.filter(c=>selected.value?.lessons.some(l=>l.name===c.session)).length||0)
async function refresh(){data.value=await call('video_courses');if(selected.value){selected.value=data.value.courses.find(c=>c.name===selected.value.name);lesson.value=selected.value?.lessons.find(l=>l.name===lesson.value?.name)||selected.value?.lessons[0]||null}}
function open(course){selected.value=course;lesson.value=course.lessons[0]||null;error.value=''}
async function save(){busy.value=true;error.value='';try{await call('create_video_course',{data:form.value});creating.value=false;await refresh();emit('refresh');emit('notify','Your demo video course is published. Add lesson quizzes from Lesson quizzes.')}catch(e){error.value=e.message}finally{busy.value=false}}
async function enroll(){try{await call('enroll_video_course',{classroom:selected.value.name});await refresh();emit('refresh');emit('notify',selected.value.access.allowed?'Course enrolled. Ready when you are.':'Enrollment saved. Open Payments to settle the course fee.')}catch(e){error.value=e.message}}
async function complete(){try{await call('complete_lesson',{session:lesson.value.name});await refresh();emit('notify','Lesson completed. A little progress, every day.')}catch(e){error.value=e.message}}
onMounted(refresh)
</script>
<template><div class="page-heading"><div><span class="eyebrow">YOUR PACE. YOUR NEXT POSSIBILITY.</span><h1>Online video courses.</h1><p>Recorded lessons, thoughtful practice, and a little progress whenever it suits you.</p></div><button v-if="member.role!=='Student'" class="button primary" @click="creating=!creating;selected=null"><Icon name="Plus" :size="17"/>Create video course</button></div><p v-if="error" class="error" role="alert">{{error}}</p><form v-if="creating" class="panel video-course-form" @submit.prevent="save"><h2>Build a course students can return to.</h2><div class="form-row"><label>Course title<input v-model="form.title" maxlength="120" required></label><label>Teacher<select v-model="form.teacher"><option v-for="t in teachers" :value="t.name">{{t.full_name}}</option></select></label></div><label>What will students learn?<textarea v-model="form.description" maxlength="1000" required></textarea></label><div class="form-row"><label>Teaching language<input v-model="form.medium" maxlength="60" required></label><label>Full course price · LKR<input v-model.number="form.fee" type="number" min="0" max="1000000" step="0.01"><small>0 makes the course free. This preview does not collect payments.</small></label></div><h3>Modules & recorded lessons</h3><article v-for="(l,i) in form.lessons" class="course-lesson-editor"><div class="inline spread"><b>Lesson {{i+1}}</b><button v-if="form.lessons.length>1" type="button" class="text-button" @click="form.lessons.splice(i,1)">Remove lesson</button></div><div class="form-row"><label>Module name<input v-model="l.module" maxlength="80" required></label><label>Lesson title<input v-model="l.title" maxlength="120" required></label></div><label>YouTube video URL <HelpTip text="Public or unlisted YouTube videos play when embedding is allowed. Private videos require invited Google accounts; course payment cannot override YouTube privacy. Unlisted links can still be shared."/><input v-model="l.url" type="url" placeholder="https://youtu.be/…" required></label><label>Lesson notes<textarea v-model="l.description" maxlength="1000"></textarea></label></article><div class="inline wrap"><button type="button" class="button subtle" :disabled="form.lessons.length>=30" @click="form.lessons.push({module:'Next module',title:'',url:'',description:''})">Add lesson</button><button class="button primary" :disabled="busy">Publish demo course</button><button type="button" class="text-button" @click="creating=false">Cancel</button></div></form>
<template v-else-if="selected"><button class="text-button" @click="selected=null;lesson=null">← Back to video courses</button><div class="video-course-layout"><aside class="panel course-outline"><span class="badge violet">Self-paced course</span><h2>{{selected.title}}</h2><p>{{selected.teacher_name}} · {{selected.medium}}</p><div v-if="member.role==='Student'&&selected.enrolled" class="course-progress"><strong>{{completed}} / {{selected.lessons.length}} lessons completed</strong><progress :value="completed" :max="selected.lessons.length||1"></progress></div><template v-for="module in [...new Set(selected.lessons.map(l=>l.module||'Course lessons'))]"><h3>{{module}}</h3><button v-for="l in selected.lessons.filter(l=>(l.module||'Course lessons')===module)" :class="{chosen:lesson?.name===l.name}" @click="lesson=l"><Icon :name="data.completions.some(c=>c.session===l.name)?'CircleCheck':'Play'" :size="18"/><span>{{l.title}}</span><Icon v-if="!selected.access.allowed" name="LockKeyhole" :size="14"/></button></template></aside><section class="panel video-lesson"><template v-if="selected.access.allowed&&lesson"><iframe :key="lesson.name" :src="'https://www.youtube.com/embed/'+lesson.youtube_id+'?rel=0'" title="Online course lesson video" referrerpolicy="strict-origin-when-cross-origin" allow="encrypted-media; picture-in-picture; fullscreen" allowfullscreen></iframe><span class="eyebrow">{{lesson.module||'RECORDED LESSON'}}</span><h2>{{lesson.title}}</h2><p>{{lesson.description}}</p><p v-if="lesson.youtube_id==='YSul9yrAvN4'" class="field-help">The supplied stock video demonstrates playback. It is not the subject’s teaching content.</p><template v-if="member.role==='Student'"><button class="button primary" :disabled="data.completions.some(c=>c.session===lesson.name)" @click="complete">{{data.completions.some(c=>c.session===lesson.name)?'Lesson completed':'Mark lesson complete'}}</button><LessonQuiz :key="lesson.name" :session="lesson" @completed="refresh"/></template><button v-else class="button subtle" @click="$emit('quizzes')">Add a lesson quiz</button></template><div v-else class="course-access"><span class="stat-icon violet"><Icon name="LockKeyhole" :size="30"/></span><h2>{{selected.enrolled?'Your next step is payment.':'Ready to start something new?'}}</h2><p>{{selected.description}}</p><strong>{{selected.fee?'LKR '+selected.fee.toLocaleString()+' · full course':'Free course'}}</strong><button v-if="!selected.enrolled" class="button primary" @click="enroll">Enroll in this course</button><button v-else class="button primary" @click="$emit('payments')">View course payment</button></div></section></div></template>
<template v-else><label class="search"><Icon name="Search" :size="17"/><input v-model="query" aria-label="Search video courses" placeholder="Find your next course"></label><div class="video-course-grid"><article v-for="c in courses" class="panel video-course-card"><div class="video-course-cover"><Icon name="Clapperboard" :size="64"/><span>LEARN AT YOUR OWN PACE</span></div><span class="badge mint">{{c.lessons.length}} recorded lessons · {{c.medium}}</span><h2>{{c.title}}</h2><p>{{c.teacher_name}}</p><p>{{c.description}}</p><div class="inline spread"><strong>{{c.fee?'LKR '+c.fee.toLocaleString():'Free'}}</strong><button class="button primary small" @click="open(c)">{{c.enrolled?'Continue course':'View course'}} <Icon name="ArrowRight" :size="15"/></button></div></article></div><p v-if="!courses.length" class="empty-state">No matching courses yet.</p></template><p class="field-help">Interactive preview: course purchases and progress are saved in this browser. On the installed site, native Frappe LMS manages course chapters, lessons, quizzes and certificates; its payment access needs the documented enrollment bridge.</p></template>
<style>.video-course-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:22px;margin:24px 0}.video-course-card{padding:16px}.video-course-cover{display:flex;flex-direction:column;align-items:center;justify-content:center;gap:20px;height:175px;background:linear-gradient(125deg,#e8def8,#dfeee5);border-radius:14px;color:#957cbb;margin-bottom:20px}.video-course-cover span{font-size:8px;letter-spacing:2px}.video-course-card h2{font-size:19px;line-height:1.5}.video-course-card p{font-size:11px;color:#92839c;line-height:1.8}.video-course-card>.inline{margin-top:20px}.video-course-layout{display:grid;grid-template-columns:300px minmax(0,1fr);gap:22px;margin-top:24px}.course-outline h2{font-size:20px;line-height:1.6}.course-outline p{font-size:11px;color:#8d7b98}.course-outline h3{font-size:12px;margin-top:25px}.course-outline>button{display:flex;gap:10px;align-items:center;width:100%;border:0;background:#f8f4fc;border-radius:12px;padding:14px;text-align:start;font-size:11px;color:#826496;cursor:pointer;margin-top:8px}.course-outline>button.chosen{background:#e9def7}.course-outline>button span{flex:1}.video-lesson iframe{width:100%;aspect-ratio:16/9;border:0;border-radius:14px;margin-bottom:25px}.video-lesson h2{font-size:23px}.video-lesson p{font-size:13px;line-height:1.9;color:#8b7699}.course-progress{margin:20px 0}.course-progress strong{font-size:10px}.course-progress progress{width:100%;height:8px;accent-color:#9271b9}.course-access{padding:45px 20px;text-align:center}.course-access .stat-icon{margin:auto}.course-access .button,.course-access strong{display:block;margin:22px auto}.video-course-form label{display:block;font-size:12px;margin:15px 0}.video-course-form input,.video-course-form select,.video-course-form textarea{display:block;width:100%;border:1px solid #e0d6e9;padding:12px;border-radius:10px;margin-top:7px}.video-course-form small{display:block;font-size:10px;margin-top:7px}.course-lesson-editor{background:#faf7fc;border-radius:15px;padding:20px;margin-bottom:16px}.course-lesson-editor b{font-size:12px}@media(max-width:1100px){.video-course-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.video-course-layout{grid-template-columns:240px minmax(0,1fr)}}@media(max-width:760px){.video-course-grid,.video-course-layout{grid-template-columns:1fr}.course-access{padding:20px 0}}
</style>
