<script setup>
import {ref,computed,onBeforeUnmount} from 'vue'
import Icon from '../Icon.vue'
import PersonalTools from '../study/PersonalTools.vue'
import {isDemo} from '../service'
import {readTools,saveTools,toolActive} from '../study/tools'
const props=defineProps({member:Object}),emit=defineEmits(['navigate','notify'])
const activeApp=ref(''),now=ref(Date.now()),cardConsent=ref(false),message=ref('')
const tick=setInterval(()=>now.value=Date.now(),1000);onBeforeUnmount(()=>clearInterval(tick))
const products=[{id:'study',title:'Study Space',icon:'Headphones',tag:'Find your focus',body:'A living little world. Video scenery, gentle music and a focus clock.',price:'Premium · price coming soon',art:'sanctuary'},{id:'todo',title:'My little to-do',icon:'CheckCheck',tag:'One small step',body:'Plan your days, keep tiny promises and connect tasks to your calendar.',price:'US$1 / month',art:'tasks'},{id:'journal',title:'A page for me',icon:'NotebookPen',tag:'Room to reflect',body:'Thoughts, gratitude and small wins. A quiet space that is yours.',price:'US$1 / month',art:'pages'}]
const entitlement=id=>{now.value;if(!isDemo)return false;let trial;try{trial=JSON.parse(localStorage.getItem('sisu-card-trial:'+props.member.name))}catch{}if(!trial||trial.expires<=now.value)return false;if(id==='study'){try{return JSON.parse(localStorage.getItem('sisu-study-v1:'+props.member.name))?.entitlement?.expiresAt>now.value}catch{return false}}return toolActive(readTools(props.member.name),id,now.value)}
const claimed=computed(()=>{now.value;return !!localStorage.getItem('sisu-card-trial:'+props.member.name)})
function claim(){if(!isDemo||!cardConsent.value||claimed.value)return;const expires=Date.now()+3*86400000;const tools=readTools(props.member.name);for(const id of ['todo','journal'])tools.entitlements[id]=expires;saveTools(props.member.name,tools);let study={};try{study=JSON.parse(localStorage.getItem('sisu-study-v1:'+props.member.name))||{}}catch{}study.entitlement={product:'study_plus',expiresAt:expires};localStorage.setItem('sisu-study-v1:'+props.member.name,JSON.stringify(study));localStorage.setItem('sisu-card-trial:'+props.member.name,JSON.stringify({expires,card:'fictional-token-only'}));now.value=Date.now();message.value='Your three-day preview is ready. No card was collected and no charge or renewal was created.'}
function open(p){if(!entitlement(p.id)){message.value='Claim the card-qualified trial below. Real subscription checkout is not connected yet.';return}if(p.id==='study')emit('navigate','study');else activeApp.value=p.id}
</script>
<template><section class="apps-page"><template v-if="!activeApp"><div class="page-heading"><div><span class="eyebrow">LITTLE APPS. MORE ROOM FOR YOU.</span><h1>Your everyday companions.</h1><p>For busy mornings, curious afternoons and quiet evenings. Make a little space for yourself.</p></div><span class="badge violet"><Icon name="Sparkles" :size="14"/>Sisu Premium</span></div><div class="cozy-app-grid"><article v-for="p in products" class="cozy-app-card"><div class="app-art" :class="p.art" aria-hidden="true"><span class="app-orbit"></span><div class="app-object"><Icon :name="p.icon" :size="64"/></div><span class="app-star">✧</span><span class="app-dot">✦</span></div><div class="app-card-copy"><small>{{p.tag}}</small><h2>{{p.title}} <span class="premium-mark" title="Optional paid app"><Icon name="Sparkles" :size="14"/></span></h2><p>{{p.body}}</p><strong>{{p.price}}</strong><button class="button primary" @click="open(p)">{{entitlement(p.id)?'Open app':'Unlock app'}}<Icon name="ArrowUpRight" :size="17"/></button></div></article></div><section class="card-trial panel"><div><span class="eyebrow">TRY A LITTLE OF EVERYTHING</span><h2>Three days, just for you.</h2><p>Try all available premium apps after adding a verified card. Choose only what you want to keep. Class fees and teacher payouts are separate.</p></div><div><p v-if="claimed" class="badge violet">Trial already claimed for this preview account</p><template v-else><label class="checkbox-label"><input v-model="cardConsent" type="checkbox" :disabled="!isDemo">{{isDemo?'Use a fictional verified card for this preview.':'Card verification is required to begin.'}}</label><button class="button primary" :disabled="!isDemo||!cardConsent" @click="claim">{{isDemo?'Claim 3-day preview':'Secure card setup coming soon'}}</button></template><p class="field-help">{{isDemo?'Do not enter card numbers here. This preview does not charge or auto-renew.':'Use hosted checkout when the payment provider is connected. Card numbers and CVC never belong in the LMS.'}}</p></div></section><p class="field-help">A three-day trial covers available premium functionality, not future features or platform approval privileges. Each app remains a separate optional subscription after trial.</p></template><template v-else><button class="text-button" @click="activeApp=''">← All apps</button><div class="personal-app-host"><PersonalTools :member="member" :tab="activeApp" @navigate="$event==='unlock'?activeApp='':$emit('navigate',$event)" @notify="$emit('notify',$event)"/></div></template><p v-if="message" role="status" class="form-note">{{message}}</p></section></template>
<style>.cozy-app-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:25px}.cozy-app-card{background:var(--student-card);border:1px solid var(--student-border);border-radius:30px;overflow:hidden;box-shadow:0 12px 38px #70539c0a}.app-art{height:220px;background:radial-gradient(at 20% 0%,#f5efff,#dacdf1);display:grid;place-items:center;position:relative;overflow:hidden}.app-art.tasks{background:radial-gradient(at 20% 0%,#f3eefc,#c8ccec)}.app-art.pages{background:radial-gradient(at 20% 0%,#fff2ed,#e4cce7)}.app-orbit{position:absolute;width:250px;height:250px;border:1px solid #fff9;border-radius:50%;transform:rotate(-25deg) scaleY(.58)}.app-object{width:116px;height:122px;background:linear-gradient(145deg,#faf6ff,#ccb8ed);border:5px solid #ffffffb0;border-radius:32px;box-shadow:12px 18px 25px #7c63a32b,inset -5px -5px 0 #9a7ab826;display:grid;place-items:center;color:#7656a6;transform:rotate(-9deg)}.app-star{position:absolute;right:22%;top:20%;font-size:42px;color:#fff}.app-dot{position:absolute;left:18%;bottom:20%;color:#9272bd;font-size:22px}.app-card-copy{padding:28px;display:flex;flex-direction:column;gap:18px}.app-card-copy h2{font-size:24px}.app-card-copy p{font-size:13px;line-height:1.8;min-height:70px}.app-card-copy small{letter-spacing:1px}.app-card-copy strong{font-size:13px}.premium-mark{display:inline-grid;place-items:center;width:24px;height:24px;border-radius:8px;background:#e6d8fa;color:#7857aa;vertical-align:middle}.card-trial{display:grid;grid-template-columns:1fr 1fr;gap:50px;padding:35px;margin-top:28px}.card-trial h2{margin:12px 0}.card-trial p{font-size:12px;line-height:1.9}.card-trial .button{margin:18px 0}.personal-app-host{margin-top:24px;--study-card:var(--student-card);--study-border:var(--student-border);--study-ink:var(--student-ink);--study-muted:var(--student-muted);--study-soft:var(--student-soft);--study-accent:var(--student-accent)}.personal-app-host .study-start{padding:13px 22px;background:var(--student-accent);border-radius:12px;color:white}.personal-app-host .study-link{color:var(--student-accent)}@media(max-width:950px){.cozy-app-grid{grid-template-columns:1fr}.cozy-app-card{display:grid;grid-template-columns:35% 1fr}.app-art{height:100%;min-height:220px}.card-trial{grid-template-columns:1fr;gap:20px}}@media(max-width:550px){.cozy-app-card{display:block}.app-art{height:200px}.app-card-copy{padding:24px}.card-trial{padding:24px}}
</style>
