<script setup>
import {ref,onBeforeUnmount} from 'vue'
import {community,storeCommunity} from './community'
import {isDemo,call} from '../service'
import {safeLink} from '../rules'
const props=defineProps({member:Object,profile:Object}),rows=ref([]),headline=ref(''),body=ref(''),url=ref(''),message=ref(''),busy=ref(false)
async function load(){try{if(!isDemo){rows.value=await call('followed_updates',{},'profiles');return}const c=community(),ids=new Set(c.links.filter(l=>l.user===props.member.name&&l.kind==='Follow'&&l.status==='Active').map(l=>l.profile));rows.value=(c.updates||[]).filter(u=>Date.parse(u.expires_at)>Date.now()&&(props.profile?u.profile===props.profile.name:ids.has(u.profile))).map(u=>({...u,display_name:c.profiles.find(p=>p.name===u.profile)?.display_name})).slice(0,25)}catch(e){message.value=e.message}}
async function publish(){busy.value=true;message.value='';try{if(!headline.value.trim()||!body.value.trim())throw Error('Add a headline and description.');if(url.value&&!safeLink(url.value))throw Error('Use a valid HTTPS link.');if(isDemo){const c=community();c.updates=(c.updates||[]).filter(u=>Date.parse(u.expires_at)>Date.now());c.updates.unshift({name:crypto.randomUUID(),profile:props.profile.name,headline:headline.value,body:body.value,url:url.value,expires_at:new Date(Date.now()+30*86400000).toISOString()});storeCommunity(c)}else await call('publish_update',{headline:headline.value,body:body.value,url:url.value},'profiles');headline.value='';body.value='';url.value='';message.value='Update published for followers. It expires after 30 days.';await load()}catch(e){message.value=e.message}finally{busy.value=false}}
load();const timer=setInterval(load,60000);onBeforeUnmount(()=>clearInterval(timer))
</script>
<template><section class="panel follow-updates"><h2>{{profile?'A little news for your followers':'From the people you follow'}}</h2><form v-if="profile" @submit.prevent="publish"><label>Headline · 80 characters<input v-model="headline" required maxlength="80"></label><label>Description · 240 characters<textarea v-model="body" required maxlength="240"></textarea></label><label>Optional link<input v-model="url" type="url" maxlength="500" placeholder="https://…"></label><button class="button primary" :disabled="busy">Publish to followers</button></form><p v-if="message" role="status">{{message}}</p><article v-for="u in rows" :key="u.name"><small>{{u.display_name}} · expires {{new Date(u.expires_at).toLocaleDateString()}}</small><h3>{{u.headline}}</h3><p>{{u.body}}</p><a v-if="safeLink(u.url)" :href="safeLink(u.url)" target="_blank" rel="noopener noreferrer">Learn more ↗</a></article><p v-if="!rows.length&&!profile">Follow an institute or teacher in Profiles & connections. Their new updates will appear here.</p></section></template>
<style>.follow-updates{padding:28px;margin:25px 0}.follow-updates h2{margin-bottom:18px}.follow-updates p{font-size:13px;line-height:1.8;margin:12px 0}.follow-updates article{padding:22px 0;border-top:1px solid var(--student-border)}.follow-updates small{font-size:11px}.follow-updates h3{margin-top:12px}.follow-updates label{display:flex;flex-direction:column;gap:8px;margin:18px 0;font-size:12px}.follow-updates :is(input,textarea){padding:13px;background:var(--student-card);color:var(--student-ink);border:1px solid var(--student-border);border-radius:12px}.follow-updates a{color:var(--student-accent)}</style>
