<script setup>
import {ref,computed,onMounted} from 'vue'
import {request} from '../native/client'
import ContactSettings from '../ContactSettings.vue'
import {previewMode} from '../preview/mode'
const props=defineProps({member:Object})
const form=ref({date_of_birth:'',gender:'Prefer not to say',gender_description:'',contact_phone:'',city:'',address:'',guardian_name:'',guardian_relationship:'',guardian_phone:'',guardian_email:'',guardian_permission:false,whatsapp_phone:'',whatsapp_opt_in:false,notification_language:'en'})
const verified=ref(''),code=ref(''),pending=ref(false),busy=ref(false),error=ref(''),message=ref(''),loginEmail=ref('')
const today=new Date().toLocaleDateString('en-CA')
const age=computed(()=>{if(!form.value.date_of_birth)return null;const b=new Date(form.value.date_of_birth+'T12:00:00'),n=new Date();return n.getFullYear()-b.getFullYear()-((n.getMonth()<b.getMonth()||n.getMonth()===b.getMonth()&&n.getDate()<b.getDate())?1:0)})
const minor=computed(()=>props.member.role==='Student'&&age.value!==null&&age.value<16)
const guardianReady=computed(()=>minor.value&&!!form.value.guardian_phone&&form.value.whatsapp_phone===form.value.guardian_phone&&form.value.guardian_permission)
const matching=computed(()=>!!verified.value&&verified.value===form.value.whatsapp_phone)
async function run(fn){busy.value=true;error.value='';try{await fn()}catch(e){error.value=e.message}finally{busy.value=false}}
async function load(){const r=await request('private_contact','get_details');Object.assign(form.value,r.data);verified.value=r.verified_phone;loginEmail.value=r.login_email;for(const k of ['guardian_permission','whatsapp_opt_in'])form.value[k]=!!form.value[k]}
async function save(){await run(async()=>{await request('private_contact','save_details',{data:form.value});message.value='Private details and notification preferences saved.'})}
async function sendCode(){await run(async()=>{await request('private_contact','request_whatsapp_code',{phone:form.value.whatsapp_phone});pending.value=true;message.value=previewMode?'Preview only: use 123456. No WhatsApp message was sent.':'Verification code requested on WhatsApp. It expires in 10 minutes.'})}
async function verify(){await run(async()=>{await request('mobile_verification','verify',{code:code.value});verified.value=(await request('private_contact','get_details')).verified_phone;pending.value=false;message.value='Number verified. Choose your notification preference and save.'})}
onMounted(()=>run(load))
</script>
<template><section class="private-contact panel" id="private-contact"><span class="eyebrow">JUST BETWEEN YOU AND YOUR LEARNING SPACE</span><h2>Contact & personal details</h2><p>Your birthday, gender, address and guardian details are private. They never appear on teacher cards or public profiles.</p><form @submit.prevent="save"><label>Login email<input :value="loginEmail" type="email" readonly><small>Use the email section below to verify a notification address.</small></label><div class="contact-field-grid"><label>Contact number<input v-model="form.contact_phone" type="tel" autocomplete="tel" placeholder="+94771234567" maxlength="16"></label><label>City / town<input v-model="form.city" autocomplete="address-level2" maxlength="100"></label><template v-if="member.role!=='Admin'"><label>Birthday<input v-model="form.date_of_birth" type="date" :max="today" :required="member.role==='Student'" autocomplete="bday"></label><label>Age<input :value="age===null?'Add your birthday':age+' years'" readonly><small>Calculated automatically from your birthday.</small></label><label>Gender<select v-model="form.gender"><option>Prefer not to say</option><option>Female</option><option>Male</option><option>Non-binary</option><option>Self-described</option></select></label><label v-if="form.gender==='Self-described'">Describe your gender (optional)<input v-model="form.gender_description" maxlength="100"></label></template></div><label>Address (optional)<textarea v-model="form.address" autocomplete="street-address" maxlength="500" rows="2"></textarea></label>
<fieldset v-if="minor" class="guardian-fields"><legend>A parent or guardian, close at hand</legend><p>Because you are under 16, add a parent or guardian who can help with class updates.</p><div class="contact-field-grid"><label>Parent / guardian name<input v-model="form.guardian_name" required maxlength="120"></label><label>Relationship<select v-model="form.guardian_relationship" required><option value="">Choose relationship</option><option>Mother</option><option>Father</option><option>Legal guardian</option><option>Other guardian</option></select></label><label>Guardian phone<input v-model="form.guardian_phone" @input="form.guardian_permission=false;form.whatsapp_opt_in=false" required type="tel" placeholder="+94771234567" maxlength="16"></label><label>Guardian email (optional)<input v-model="form.guardian_email" type="email" maxlength="254"></label></div><label class="contact-check"><input type="checkbox" v-model="form.guardian_permission">My guardian has agreed to receive class updates on this number.</label><button type="button" class="button subtle small" @click="form.whatsapp_phone=form.guardian_phone;form.whatsapp_opt_in=false">Use guardian number for WhatsApp</button><small>No verification code is required for a parent or guardian number. Check the number carefully before saving.</small></fieldset>
<fieldset class="whatsapp-fields"><legend>Your class updates on WhatsApp</legend><p>Schedules, session changes, new materials and payment confirmations. You can turn these updates off anytime.</p><label>{{minor?'Guardian WhatsApp number':'WhatsApp number'}}<input v-model="form.whatsapp_phone" type="tel" placeholder="+94771234567" maxlength="16" @input="form.whatsapp_opt_in=false"></label><div v-if="!minor" class="inline wrap"><button type="button" class="button subtle" :disabled="busy||!form.whatsapp_phone" @click="sendCode">Send WhatsApp verification code</button><span v-if="matching" class="badge green">{{previewMode?'Verified in preview':'Verified number'}}</span></div><small v-if="minor">Parent or guardian numbers do not need verification. Use the guardian number above and confirm their permission.</small><div v-if="pending&&!minor" class="contact-code"><label>WhatsApp verification code<input v-model="code" inputmode="numeric" maxlength="6" autocomplete="one-time-code" placeholder="000000"></label><button type="button" class="button primary small" :disabled="busy||code.length!==6" @click="verify">Verify number</button></div><label>Notification language<select v-model="form.notification_language"><option value="en">English</option><option value="si">සිංහල</option><option value="ta">தமிழ்</option></select><small>Each language needs an approved WhatsApp message template.</small></label><label class="contact-check"><input v-model="form.whatsapp_opt_in" type="checkbox" :disabled="minor?!guardianReady:!matching">{{minor?'Send class updates to my guardian number':'Send class updates to my verified WhatsApp number'}}</label></fieldset>
<p v-if="error" class="error" role="alert">{{error}}</p><p v-if="message" role="status">{{message}}</p><button class="button primary" :disabled="busy">Save private details</button></form><ContactSettings :member="member" @notify="message=$event"/></section></template>
<style>.private-contact{max-width:760px;padding:30px;margin:24px 0}.private-contact h2{font-size:24px;margin:12px 0}.private-contact p{font-size:13px;line-height:1.8;margin:12px 0 20px}.contact-field-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 20px}.private-contact label{display:flex;flex-direction:column;gap:9px;margin:18px 0;font-size:12px}.private-contact :is(input:not([type=checkbox]),textarea,select){padding:12px;border:1px solid var(--student-border);border-radius:12px;background:var(--student-card);color:var(--student-ink);font:inherit;width:100%;min-width:0}.private-contact small{font-size:11px;line-height:1.7;color:var(--student-muted);display:block}.private-contact fieldset{border:1px solid var(--student-border);border-radius:18px;padding:22px;margin:24px 0;background:#ac8cc908}.private-contact legend{font-size:15px;font-weight:650;padding:0 8px}.private-contact .contact-check{flex-direction:row;align-items:flex-start;line-height:1.6}.contact-check input{margin-top:3px}.private-contact input[readonly]{opacity:.75}.contact-code{max-width:300px}@media(max-width:560px){.contact-field-grid{grid-template-columns:1fr}.private-contact{padding:20px}.private-contact fieldset{padding:15px}}</style>
