<script setup>
import {computed} from 'vue'
import SocialIcon from './SocialIcon.vue'
import {socialNetworks,providerSocials} from './socials.js'
const props=defineProps({profile:Object})
const links=computed(()=>providerSocials(props.profile?.kind,props.profile?.socials))
</script>
<template><div role="group" v-if="['Teacher','Institute'].includes(profile?.kind)" class="provider-social-links" :aria-label="(profile.display_name||'Provider')+' social media'"><template v-for="(label,key) in socialNetworks" :key="key"><a v-if="links[key]" :href="links[key]" :class="'social-'+key" target="_blank" rel="noopener noreferrer" :aria-label="(profile.display_name||'Provider')+' on '+label+' (opens in a new tab)'" :title="label+' · opens in a new tab'"><SocialIcon :network="key"/></a><button v-else type="button" class="social-unavailable" :class="'social-'+key" aria-disabled="true" :aria-label="label+' · link not added'" :title="label+' · link not added'"><SocialIcon :network="key"/></button></template></div></template>
<style>.provider-social-links{display:flex;flex-direction:row;flex-wrap:wrap;gap:8px;align-items:center}.provider-social-links a,.provider-social-links button{display:grid;place-items:center;padding:0;flex:0 0 auto;width:42px;min-height:44px;border:1px solid var(--student-border,#e5d9ef);border-radius:13px;background:var(--student-card,#fff);box-shadow:0 3px 10px #5d437009;transition:transform .15s,box-shadow .15s}.provider-social-links svg{width:22px;height:22px}.provider-social-links .social-facebook{color:#1877f2}.provider-social-links .social-youtube{color:#e62117}.provider-social-links .social-linkedin{color:#0a66c2}.provider-social-links .social-instagram{color:#c13584}.provider-social-links .social-twitter,.provider-social-links .social-tiktok{color:var(--student-ink,#443650)}.provider-social-links a:hover{transform:translateY(-2px);box-shadow:0 5px 14px #76539120}.provider-social-links a:focus-visible,.provider-social-links button:focus-visible{outline:3px solid var(--student-accent,#906aaf);outline-offset:3px}@media(prefers-reduced-motion:reduce){.provider-social-links a{transition:none}.provider-social-links a:hover{transform:none}}.provider-social-links .social-unavailable{opacity:.55;cursor:default}.provider-social-links .social-unavailable:hover{opacity:.8}</style>
