<script setup>
import {ref} from 'vue'
import {uploadDocument} from './client'
const props=defineProps({form:Object,member:Object});const emit=defineEmits(['busy'])
const error=ref(''),busy=ref(false)
async function upload(e,purpose){const target=props.form;const file=e.target.files[0];if(!file)return;busy.value=true;emit('busy',true);error.value='';try{const result=await uploadDocument(file,props.form.classroom,props.member,purpose);if(props.form!==target)return;if(purpose==='preview'){props.form.preview_file_id=result.file_id;props.form.preview_filename=result.filename}else{Object.assign(props.form,result);props.form.preview_file_id='';props.form.preview_filename='';props.form.url=''}}catch(e){error.value=e.message}finally{busy.value=false;emit('busy',false)}}
</script>
<template><div class="material-upload"><label>Learning document <input type="file" accept=".pdf,.ppt,.pptx,.doc,.docx" :disabled="busy" @change="upload($event,'original')"></label><p class="field-help">PDF, PowerPoint or Word · up to 10 MB each. Files remain private to the classroom.</p><p v-if="form.filename" class="upload-file-summary">{{form.filename}} · {{(form.file_size/1024/1024).toFixed(2)}} MB</p><label>Student access<select v-model="form.download_policy"><option>View only</option><option>Downloadable</option></select></label><template v-if="form.file_id&&form.file_type!=='pdf'"><label>Matching PDF preview {{form.download_policy==='View only'?'(required)':'(optional)'}}<input type="file" accept=".pdf" :disabled="busy" @change="upload($event,'preview')"></label><p v-if="form.preview_filename" class="upload-file-summary">{{form.preview_filename}}</p><p class="field-help">In PowerPoint or Word, export the same lesson as PDF and add it here. Students see that preview inside Sisu. Your Office file is available only when downloads are allowed.</p></template><p class="field-help">View only hides download controls and blocks the original Office download. Visible content can still be captured; this is not copy protection.</p><p v-if="busy" role="status">Uploading your classroom document…</p><p v-if="error" class="error" role="alert">{{error}}</p></div></template>
<style>.material-upload{padding:18px;border:1px solid var(--line);border-radius:14px;margin:18px 0;background:#a58bb508}.upload-file-summary{font-size:12px;overflow-wrap:anywhere;padding:10px;border-radius:8px;background:#a58bb514}</style>
