<script setup>
import {ref,computed,onBeforeUnmount,nextTick} from 'vue'
import Icon from '../Icon.vue'
import {materialBlob} from './client'
const props=defineProps({material:Object,member:Object})
const open=ref(false),busy=ref(false),error=ref(''),page=ref(1),pages=ref(0),canvas=ref(null),pageText=ref('')
const canDownload=computed(()=>props.member.role!=='Student'||props.material.download_policy==='Downloadable')
const hasPreview=computed(()=>props.material.file_type==='pdf'||!!props.material.preview_file_id)
let task,document,renderTask,generation=0
async function render(){if(!document||!canvas.value)return;renderTask?.cancel();const n=generation;pageText.value='';const sheet=await document.getPage(page.value);if(n!==generation)return;const natural=sheet.getViewport({scale:1});const scale=Math.min(1.8,900/natural.width);const view=sheet.getViewport({scale});if(view.width*view.height>6000000)throw Error('This page is too large to display');canvas.value.width=view.width;canvas.value.height=view.height;renderTask=sheet.render({canvasContext:canvas.value.getContext('2d'),viewport:view});try{await renderTask.promise;const text=await sheet.getTextContent();if(n===generation)pageText.value=text.items.map(item=>item.str+(item.hasEOL?'\n':' ')).join('')}catch(e){if(e.name!=='RenderingCancelledException')throw e}finally{sheet.cleanup()}}
async function view(){open.value=true;busy.value=true;error.value='';const n=++generation;try{const blob=await materialBlob(props.material,'view',props.member);const pdf=await import('pdfjs-dist');pdf.GlobalWorkerOptions.workerSrc=(await import('pdfjs-dist/build/pdf.worker.min.mjs?url')).default;if(n!==generation)return;task=pdf.getDocument({data:new Uint8Array(await blob.arrayBuffer()),isEvalSupported:false,useSystemFonts:true,stopAtErrors:true});task.onPassword=()=>{error.value='Ask your teacher for an unlocked PDF preview.';task.destroy()};document=await task.promise;if(n!==generation)return;if(document.numPages>200)throw Error('Use a PDF preview with at most 200 pages.');pages.value=document.numPages;page.value=1;await nextTick();await render()}catch(e){if(n===generation)error.value=e.message||'Preview could not be opened'}finally{if(n===generation)busy.value=false}}
async function turn(delta){if(busy.value)return;page.value+=delta;busy.value=true;try{await render()}catch(e){error.value=e.message}finally{busy.value=false}}
function close(){generation++;renderTask?.cancel();task?.destroy();task=null;document=null;pages.value=0;pageText.value='';open.value=false;busy.value=false}
async function download(){busy.value=true;error.value='';try{const blob=await materialBlob(props.material,'download',props.member);const url=URL.createObjectURL(blob),a=window.document.createElement('a');a.href=url;a.download=props.material.filename||'class-document';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){error.value=e.message}finally{busy.value=false}}
onBeforeUnmount(close)
</script>
<template><section class="class-document"><div class="document-summary"><span class="stat-icon violet"><Icon :name="['ppt','pptx'].includes(material.file_type)?'Presentation':'FileText'"/></span><div class="grow"><h3>{{material.title}}</h3><p>{{material.description||material.filename}}</p><small>{{material.file_type?.toUpperCase()}} · {{material.download_policy==='Downloadable'?'Downloads allowed':'View only'}} · {{(material.file_size/1024/1024).toFixed(2)}} MB</small></div><button v-if="hasPreview" class="button subtle small" :disabled="busy" @click="open?close():view()">{{open?'Close preview':'View document'}}</button><button v-if="canDownload" class="button subtle small" :disabled="busy" @click="download"><Icon name="Download" :size="15"/>Download</button></div><div v-if="open" class="document-reader" :aria-label="material.title+' preview'"><div class="reader-toolbar"><strong>{{material.title}}</strong><span>Page {{page}} / {{pages||'…'}}</span><button class="button subtle small" :disabled="busy||page<=1" @click="turn(-1)" aria-label="Previous document page"><Icon name="ChevronLeft" :size="16"/></button><button class="button subtle small" :disabled="busy||page>=pages" @click="turn(1)" aria-label="Next document page"><Icon name="ChevronRight" :size="16"/></button></div><p v-if="busy" role="status">Opening your lesson…</p><div class="document-page"><canvas ref="canvas" role="img" :aria-label="material.title+', page '+page"></canvas></div><details class="page-transcript"><summary>Read page text</summary><p>{{pageText||'This page has no selectable text. Ask your teacher for an accessible text version.'}}</p></details><p class="field-help">PDF preview · {{material.download_policy==='Downloadable'?'Use Download for the original file.':'View-only material; no student download control.'}}</p></div><p v-if="!hasPreview" class="field-help">Your teacher has not added a PDF preview. Download the original document to open it in Office.</p><p v-if="error" class="error" role="alert">{{error}}</p></section></template>
<style>.class-document{padding:16px 0;border-bottom:1px solid var(--line)}.document-summary{display:flex;align-items:center;gap:12px;flex-wrap:wrap}.document-summary .grow{min-width:150px}.document-summary p{font-size:11px;margin:5px 0;overflow-wrap:anywhere}.document-summary small{font-size:10px}.document-reader{margin-top:16px;padding:15px;background:#9a88b212;border:1px solid var(--line);border-radius:14px}.reader-toolbar{display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin-bottom:15px;font-size:11px}.reader-toolbar strong{flex:1}.document-page{overflow:auto;max-height:70vh;text-align:center}.document-page canvas{max-width:100%;height:auto;background:white;box-shadow:0 4px 18px #281b3020}.page-transcript{margin-top:14px;font-size:12px}.page-transcript summary{cursor:pointer}.page-transcript p{white-space:pre-wrap;line-height:1.8;overflow-wrap:anywhere}.document-reader>.field-help{margin-top:12px}@media(max-width:600px){.document-reader{padding:8px}.document-summary .stat-icon{display:none}.document-summary .grow{flex-basis:100%}}</style>
