<script setup>
import {ref,computed,onBeforeUnmount} from 'vue'
import Icon from '../Icon.vue'
import {isDemo} from '../service'
import {readTools,saveTools,toolActive,toolProducts,calendarFile} from './tools'
const props=defineProps({member:Object,tab:String,plus:Boolean})
const emit=defineEmits(['studyplus','navigate','notify'])
const data=ref(readTools(props.member.name)),now=ref(Date.now()),title=ref(''),due=ref(''),entry=ref(''),mood=ref('Peaceful'),editing=ref(''),notice=ref('')
const entitlementClock=setInterval(()=>now.value=Date.now(),1000)
onBeforeUnmount(()=>clearInterval(entitlementClock))
const active=id=>isDemo&&toolActive(data.value,id,now.value)
const product=computed(()=>toolProducts.find(p=>p.id===props.tab))
const tasks=computed(()=>data.value.todos.filter(t=>!t.archived).sort((a,b)=>Number(a.done)-Number(b.done)||(a.due||'9999').localeCompare(b.due||'9999')))
function save(){try{saveTools(props.member.name,data.value)}catch{notice.value='Your device could not save this. Export or copy your text before leaving.'}}
function unlock(id){if(!isDemo)return;data.value.entitlements[id]=Date.now()+30*86400000;save();notice.value='30-day preview unlocked. No charge or automatic renewal.'}
function addTask(){if(!active('todo')||!title.value.trim())return;if(data.value.todos.length>=200){notice.value='This preview stores up to 200 tasks, including archived tasks. Export your calendar to keep a copy.';return}data.value.todos.push({id:crypto.randomUUID(),title:title.value.trim().slice(0,160),due:due.value,done:false,archived:false});title.value='';save()}
function saveEntry(){if(!active('journal')||!entry.value.trim())return;const existing=data.value.journal.find(j=>j.id===editing.value);if(existing){existing.body=entry.value;existing.mood=mood.value;existing.updated=new Date().toISOString()}else{if(data.value.journal.length>=200){notice.value='Your journal has reached the 200-entry preview limit.';return}data.value.journal.unshift({id:crypto.randomUUID(),body:entry.value,mood:mood.value,date:new Date().toISOString(),archived:false})}entry.value='';editing.value='';save();notice.value='Your reflection is saved on this device.'}
function exportTasks(){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([calendarFile(tasks.value)],{type:'text/calendar'}));a.href=url;a.download='sisu-study-tasks.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function cancel(id){delete data.value.entitlements[id];save();notice.value='Preview ended. Your saved content is retained.'}
</script>
<template><section class="personal-tools">
<template v-if="tab==='unlock'"><div class="tools-intro"><span class="eyebrow">LITTLE EXTRAS. YOUR CHOICE.</span><h2>Make this space yours.</h2><p>Your timer and light/dark modes are always free. Add only what you love.</p></div><div class="tools-products"><article class="tool-product featured"><Icon name="Sparkles"/><span class="badge violet">{{plus?'Unlocked':'Optional'}}</span><h3>Study Plus</h3><p>Living video wallpapers, soft music and a little extra coziness.</p><strong>Price coming soon</strong><button class="study-button" @click="$emit('studyplus')">{{plus?'Manage Study Plus':'Unlock me'}} <Icon name="ArrowRight" :size="15"/></button></article><article v-for="p in toolProducts" class="tool-product"><Icon :name="p.icon"/><span class="badge mint">{{active(p.id)?'Preview active':'Optional'}}</span><h3>{{p.title}}</h3><p>{{p.description}}</p><strong>Assigned price at checkout</strong><button v-if="!active(p.id)" class="study-button unlock-glow" :disabled="!isDemo" @click="unlock(p.id)">{{isDemo?'Unlock 30-day preview':'Coming soon'}}</button><template v-else><button class="study-button" @click="$emit('navigate',p.id)">Open {{p.id==='todo'?'to-do list':'journal'}}</button><button class="study-link" @click="cancel(p.id)">End preview access</button></template></article></div><p class="field-help">Preview activation does not create a payment or renewal. Your administrator assigns pricing; checkout shows the full amount before any payment.</p></template>
<template v-else-if="product"><div class="tools-intro"><Icon :name="product.icon" :size="28"/><h2>{{product.title}}</h2><p>{{product.description}}</p></div><div v-if="!active(tab)" class="tool-locked"><Icon name="LockKeyhole"/><h3>A little more room for you.</h3><p>Optional premium app. Your existing entries are retained when access ends.</p><button class="study-button unlock-glow" @click="$emit('navigate','unlock')">Unlock me</button></div>
<template v-else-if="tab==='todo'"><form class="task-compose" @submit.prevent="addTask"><label>Your next small step<input v-model="title" required maxlength="160" placeholder="Revise one chapter…"></label><label>Due date<input v-model="due" type="date"></label><button class="study-start">Add task</button></form><div class="task-calendar-note"><Icon name="CalendarDays" :size="18"/><p>Dated tasks appear in My schedule, alongside your classes.</p><button class="study-link" @click="$emit('navigate','schedule')">Open calendar</button><button class="study-link" @click="exportTasks">Export calendar file</button></div><article v-for="task in tasks" class="personal-task"><label><input type="checkbox" v-model="task.done" @change="save"><span :class="{done:task.done}">{{task.title}}</span></label><span>{{task.due||'Anytime'}}</span><button class="study-link" @click="task.archived=true;save()">Archive</button></article><p v-if="!tasks.length" class="tool-empty">A clear page. One small step is enough.</p><details v-if="data.todos.some(t=>t.archived)"><summary>Archived tasks</summary><article v-for="task in data.todos.filter(t=>t.archived)" class="personal-task">{{task.title}}<button class="study-link" @click="task.archived=false;save()">Restore</button></article></details></template>
<template v-else><form class="journal-compose" @submit.prevent="saveEntry"><label>How are you arriving today?<select v-model="mood"><option>Peaceful</option><option>Hopeful</option><option>Proud</option><option>Tired</option><option>A little overwhelmed</option></select></label><label>A little space to reflect<textarea v-model="entry" maxlength="10000" rows="8" required placeholder="Today, I’m proud of…"></textarea></label><span>{{entry.length}} / 10,000</span><button class="study-start">{{editing?'Save reflection':'Keep this moment'}}</button></form><p class="field-help">Saved only in this browser for your preview account. This is not an encrypted journal; avoid sensitive information on shared devices.</p><article v-for="j in data.journal.filter(j=>!j.archived)" class="journal-entry"><small>{{new Date(j.date).toLocaleDateString()}} · {{j.mood}}</small><p>{{j.body}}</p><button class="study-link" @click="editing=j.id;entry=j.body;mood=j.mood">Edit</button><button class="study-link" @click="j.archived=true;save()">Archive</button></article><details v-if="data.journal.some(j=>j.archived)"><summary>Archived reflections</summary><article v-for="j in data.journal.filter(j=>j.archived)" class="journal-entry"><p>{{j.body}}</p><button class="study-link" @click="j.archived=false;save()">Restore</button></article></details></template></template><p v-if="notice" role="status">{{notice}}</p></section></template>
<style>
.personal-tools{padding:30px;border-radius:24px;background:var(--study-card);border:1px solid var(--study-border)}.tools-intro{max-width:620px;margin-bottom:26px}.tools-intro h2{font-size:30px;margin:14px 0}.tools-intro p,.tool-product p{font-size:13px;line-height:1.8;color:var(--study-muted)}.tools-products{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px}.tool-product{padding:26px;border:1px solid var(--study-border);border-radius:20px;display:flex;flex-direction:column;align-items:flex-start;gap:16px;background:var(--study-card)}.tool-product.featured{background:var(--study-soft)}.tool-product p{flex:1;margin:0}.tool-product h3{font-size:22px;margin:0}.tool-product strong{font-size:23px}.tool-product small{font-size:12px}.tool-product .badge{margin-left:auto}.tool-locked,.tool-empty{padding:40px;text-align:center;background:var(--study-soft);border-radius:18px}.task-compose{display:flex;gap:16px;align-items:end}.task-compose label:first-child{flex:1}.personal-tools label{display:flex;flex-direction:column;gap:9px;font-size:12px}.personal-tools :is(input:not([type=checkbox]),textarea,select){padding:13px;border:1px solid var(--study-border);border-radius:12px;color:var(--study-ink);background:var(--study-soft);font:inherit}.personal-task{display:flex;gap:14px;align-items:center;padding:20px 0;border-bottom:1px solid var(--study-border);font-size:12px}.personal-task label{flex-direction:row;align-items:center;flex:1;font-size:14px}.personal-task input{accent-color:var(--study-accent);width:18px;height:18px}.personal-task .done{text-decoration:line-through;opacity:.6}.personal-task .study-link,.task-calendar-note .study-link{margin:0}.task-calendar-note{display:flex;gap:16px;align-items:center;margin:20px 0;flex-wrap:wrap;font-size:12px}.journal-compose{display:grid;gap:18px;max-width:800px}.journal-compose>span{font-size:11px}.journal-entry{padding:25px 0;border-top:1px solid var(--study-border);margin-top:25px}.journal-entry p{white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.9}.journal-entry .study-link{display:inline-block;margin-right:20px}.unlock-glow{box-shadow:0 0 0 3px #b69cd71a,0 0 24px #b69cd738;animation:unlock-breathe 3s ease-in-out infinite}@keyframes unlock-breathe{50%{box-shadow:0 0 0 5px #caa65c18,0 0 25px #caa65c45}}@media(prefers-reduced-motion:reduce){.unlock-glow{animation:none}}@media(max-width:850px){.tools-products{grid-template-columns:1fr}.task-compose{flex-wrap:wrap}.task-compose label:first-child{flex-basis:100%}}@media(max-width:600px){.personal-tools{padding:20px}.personal-task{flex-wrap:wrap}.tools-intro h2{font-size:25px}}
</style>
